# Generated by reflaxe.ruby
require "active_job/railtie"
$LOAD_PATH.unshift(__dir__)
require_relative "app/lib/railshx/runtime/hxruby/core"
require_relative "app/lib/railshx/runtime/hxruby/hx_exception"
require_relative "app/jobs/discard_probe_job"
require_relative "app/jobs/retry_probe_job"
require_relative "app/jobs/send_welcome_email_job"
require_relative "app/lib/railshx/generated/main"
Main.main
