package routes;

import rails.routing.RouteParam;

// Generated by HXRuby::Generators::Routes from Rails route output.
//
// Demonstrates: Rails-owned routes converted into typed Haxe extern methods.
// Type safety: Haxe callers use named route helpers instead of hand-written
// path strings; helper arity and required route params are checked at compile time.
// IntelliSense: editors should complete named route helpers from this extern.
// Ruby/Rails output: direct calls to Rails route helpers such as `todos_path`.
@:native("self")
extern class ComplexRoutes {
	@:native("root_path")
	public static function rootPath():String;

	@:native("root_url")
	public static function rootUrl():String;

	@:native("admin_posts_path")
	public static function adminPostsPath():String;

	@:native("admin_posts_url")
	public static function adminPostsUrl():String;

	@:native("admin_post_path")
	public static function adminPostPath(id:RouteParam):String;

	@:native("admin_post_url")
	public static function adminPostUrl(id:RouteParam):String;

	@:native("edit_admin_post_path")
	public static function editAdminPostPath(id:RouteParam):String;

	@:native("edit_admin_post_url")
	public static function editAdminPostUrl(id:RouteParam):String;

	@:native("publish_admin_post_path")
	public static function publishAdminPostPath(id:RouteParam):String;

	@:native("publish_admin_post_url")
	public static function publishAdminPostUrl(id:RouteParam):String;

	@:native("search_admin_posts_path")
	public static function searchAdminPostsPath():String;

	@:native("search_admin_posts_url")
	public static function searchAdminPostsUrl():String;

	@:native("post_comments_path")
	public static function postCommentsPath(postId:RouteParam):String;

	@:native("post_comments_url")
	public static function postCommentsUrl(postId:RouteParam):String;

	@:native("post_comment_path")
	public static function postCommentPath(postId:RouteParam, id:RouteParam):String;

	@:native("post_comment_url")
	public static function postCommentUrl(postId:RouteParam, id:RouteParam):String;

	@:native("preview_post_path")
	public static function previewPostPath(id:RouteParam):String;

	@:native("preview_post_url")
	public static function previewPostUrl(id:RouteParam):String;

	@:native("optional_report_path")
	public static function optionalReportPath():String;

	@:native("optional_report_url")
	public static function optionalReportUrl():String;

	@:native("asset_path")
	public static function assetPath(path:RouteParam):String;

	@:native("asset_url")
	public static function assetUrl(path:RouteParam):String;

	@:native("health_path")
	public static function healthPath():String;

	@:native("health_url")
	public static function healthUrl():String;

	@:native("sidekiq_path")
	public static function sidekiqPath():String;

	@:native("sidekiq_url")
	public static function sidekiqUrl():String;

	@:native("legacy_redirect_path")
	public static function legacyRedirectPath():String;

	@:native("legacy_redirect_url")
	public static function legacyRedirectUrl():String;

	@:native("duplicate_path")
	public static function duplicatePath(id:RouteParam):String;

	@:native("duplicate_url")
	public static function duplicateUrl(id:RouteParam):String;
}
