# Generated by reflaxe.ruby
require "active_record"
require "active_storage/engine"
$LOAD_PATH.unshift(__dir__)
require_relative "app/lib/railshx/generated/main"
require_relative "app/models/profile"
Main.main
