# Generated by RailsHx from @:railsMigration.
class UpdateUsers < ActiveRecord::Migration[7.1]
  def change
    add_column :users, :email, :string, null: false, default: "owner@example.test"
    add_column :users, :role, :string, null: false, default: "member"
    add_index :users, :email, unique: true
    add_index :users, :role, if_not_exists: true
  end
end
