# Generated by RailsHx from @:railsMigration.
class UpdateTodos < ActiveRecord::Migration[7.1]
  def change
    add_column :todos, :priority, :integer, null: false, default: 0
    add_index :todos, :priority
    remove_index :todos, :priority
    remove_column :todos, :priority
  end
end
