# Generated by RailsHx from @:railsMigration.
class UpdateTodos < ActiveRecord::Migration[7.1]
  def change
    reversible do |dir|
      dir.up do
        change_column :todos, :title, :string, null: false
        add_foreign_key :todos, :users, column: :user_id, on_delete: :cascade
      end
      dir.down do
        remove_foreign_key :todos, :users
        change_column :todos, :title, :string
      end
    end
    add_column :todos, :priority, :integer, null: false, default: 0
    add_index :todos, :priority, name: "index_todos_on_priority"
    reversible do |dir|
      dir.up do
        add_index :todos, [:user_id, :priority], name: "index_todos_on_user_id_and_priority"
      end
      dir.down do
        remove_index :todos, column: [:user_id, :priority]
      end
    end
    reversible do |dir|
      dir.up do
        execute "UPDATE todos SET priority = 0 WHERE priority IS NULL"
      end
      dir.down do
        execute "UPDATE todos SET priority = NULL WHERE priority = 0"
      end
    end
  end
end
