# Generated by RailsHx from @:railsMigration.
class UpdateTodos < ActiveRecord::Migration[7.1]
  def change
    reversible do |dir|
      dir.up do
        change_column :todos, :title, :string, null: false
        add_foreign_key :todos, :users, column: :user_id, on_delete: :cascade
      end
      dir.down do
        remove_foreign_key :todos, :users
        change_column :todos, :title, :string
      end
    end
    add_column :todos, :priority, :integer, null: false, default: 0
    add_index :todos, :priority
  end
end
