# Generated by RailsHx from @:railsMigration.
class CreateChatMessages < ActiveRecord::Migration[7.1]
  def change
    create_table :chat_messages do |t|
      t.text :body, null: false
      t.references :user, null: false, foreign_key: true
      t.index [:user_id, :id]

      t.timestamps
    end
  end
end
