# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require "active_support/isolated_execution_state"
require "active_support/notifications"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    subscription__hx0 = ActiveSupport::Notifications.subscribe("todo.shipped") { |event__hx0| puts(HXRuby.stringify(((event__hx0.payload[:list_id] + ":") + HXRuby.stringify(event__hx0.payload[:count])))) }
    label__hx0 = ActiveSupport::Notifications.instrument("todo.shipped", {list_id: "open", count: 2}) { "instrumented" }
    puts(HXRuby.stringify(label__hx0))
    ActiveSupport::Notifications.unsubscribe(subscription__hx0)
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
