# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    value__hx19488 = MaybeInt.some(41)
    empty__hx19489 = MaybeInt.none()
    puts(HXRuby.stringify("constructed"))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
