# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.main()
    value = MaybeInt.some(41)
    empty = MaybeInt.none()
    puts(HXRuby.stringify("constructed"))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
