# Generated by reflaxe.ruby
# Enum constructors use hxruby/data_define.rb for Data.define compatibility.
module MaybeInt
  def self.__hx_name()
    "MaybeInt"
  end
  def self.__hx_constructs()
    [{name: "None", index: 0, method: :none, arity: 0}, {name: "Some", index: 1, method: :some, arity: 1}, {name: "Optional", index: 2, method: :optional, arity: 1}]
  end
  None = Data.define(:__hx_tag, :__hx_index)
  def self.none()
    None.new("None", 0)
  end
  Some = Data.define(:value, :__hx_tag, :__hx_index)
  def self.some(value)
    Some.new(value, "Some", 1)
  end
  Optional = Data.define(:value, :__hx_tag, :__hx_index)
  def self.optional(value = nil)
    Optional.new(value, "Optional", 2)
  end
end
