# Generated by reflaxe.ruby
# Enum constructors use hxruby/data_define.rb for Data.define compatibility.
module MaybeInt
  None = Data.define(:__hx_tag, :__hx_index)
  def self.none()
    None.new("None", 0)
  end
  Some = Data.define(:value, :__hx_tag, :__hx_index)
  def self.some(value)
    Some.new(value, "Some", 1)
  end
end
