package tools;

import shared.TodoHooks;
import sys.io.File;

/**
	Exports the Haxe-owned todo hook constants for Playwright.

	This keeps the browser sentinel on the same source of truth as HHX and Haxe
	JS. If a behavior hook is renamed, the generated TypeScript changes in one
	place instead of leaving silent selector drift.
**/
class ExportTodoHooks {
	public static function main():Void {
		File.saveContent("examples/todoapp_rails/e2e/todo_hooks.ts", [
			"// Generated by examples/todoapp_rails/tools/ExportTodoHooks.hx.",
			"// Do not edit by hand; change shared/TodoHooks.hx and rerun npm run test:todoapp-rails.",
			"export const hooks = {",
			"  attrs: {",
			line("bound", TodoHooks.boundAttr, ","),
			line("scroll", TodoHooks.scrollAttr, ","),
			line("flash", TodoHooks.flashAttr, ","),
			line("session", TodoHooks.sessionAttr, ","),
			line("sessionZone", TodoHooks.sessionZoneAttr, ","),
			line("chat", TodoHooks.chatAttr, ","),
			line("chatForm", TodoHooks.chatFormAttr, ","),
			line("chatMessageKey", TodoHooks.chatMessageKeyAttr, ""),
			"  },",
			"  classes: {",
			line("shell", TodoHooks.shellClass, ","),
			line("form", TodoHooks.formClass, ","),
			line("sessionForm", TodoHooks.sessionFormClass, ","),
			line("sessionFooter", TodoHooks.sessionFooterClass, ","),
			line("chatForm", TodoHooks.chatFormClass, ","),
			line("chatList", TodoHooks.chatListClass, ","),
			line("chatMessage", TodoHooks.chatMessageClass, ","),
			line("list", TodoHooks.listClass, ","),
			line("item", TodoHooks.itemClass, ","),
			line("dot", TodoHooks.dotClass, ""),
			"  },",
			"  ids: {",
			line("openWork", TodoHooks.openWorkId, ","),
			line("chatPanel", TodoHooks.chatPanelId, ","),
			line("chatList", TodoHooks.chatListId, ""),
			"  },",
			"  meta: {",
			line("templateName", TodoHooks.templateMetaName, ","),
			line("templateContent", TodoHooks.templateMetaContent, ""),
			"  },",
			"  selectors: {",
			line("shell", TodoHooks.classSelector(TodoHooks.shellClass), ","),
			line("form", TodoHooks.classSelector(TodoHooks.formClass), ","),
			line("listItems", TodoHooks.classSelector(TodoHooks.listClass) + " " + TodoHooks.classSelector(TodoHooks.itemClass), ","),
			line("items", TodoHooks.classSelector(TodoHooks.itemClass), ","),
			line("dots", TodoHooks.classSelector(TodoHooks.itemClass) + " " + TodoHooks.classSelector(TodoHooks.dotClass), ","),
			line("scrollLinks", TodoHooks.attrSelector(TodoHooks.scrollAttr), ","),
			line("sessionForms", TodoHooks.classSelector(TodoHooks.sessionFormClass), ","),
			line("sessionFooter", TodoHooks.classSelector(TodoHooks.sessionFooterClass), ","),
			line("sessionZone", TodoHooks.attrSelector(TodoHooks.sessionZoneAttr), ","),
			line("chatPanel", TodoHooks.idSelector(TodoHooks.chatPanelId), ","),
			line("chatList", TodoHooks.idSelector(TodoHooks.chatListId), ","),
			line("chatForms", TodoHooks.classSelector(TodoHooks.chatFormClass), ","),
			line("chatMessages", TodoHooks.classSelector(TodoHooks.chatMessageClass), ","),
			line("openWork", TodoHooks.idSelector(TodoHooks.openWorkId), ""),
			"  }",
			"} as const",
			"",
		].join("\n"));
	}

	static function line(name:String, value:String, suffix:String):String {
		return "    " + name + ": " + haxe.Json.stringify(value) + suffix;
	}
}
