# Generated by reflaxe.ruby
# Rails controller output; Zeitwerk path should match the Ruby constant.
require "action_controller/railtie"
module Controllers
  class MixedController < ActionController::Base
    def initialize()
      super()
    end
    def haxe_shell()
      surfaces__hx0 = ["legacy ERB partial", "typed Haxe service", "RailsHx HHX partial"]
      self.render(template: "mixed/haxe_shell", locals: {title: "Haxe shell, legacy Rails parts.", legacy_badge_label: LegacyPriceFormatter.badge_label("poc", 1299), formatted_price: LegacyPriceFormatter.call(1299), typed_summary: Services::TypedStats.summary(surfaces__hx0)}, layout: "application")
    end
  end
end
