package rails.active_record;

/**
	Typed reference to an ActiveRecord-backed model field.

	RailsHx emits these as Rails-native field names/symbols, while Haxe keeps the
	model and value type available at authoring time.
**/
// `to String` lets compiler lowering erase a typed Haxe field ref to the Rails
// column name when emitting Ruby. There is intentionally no `from String`:
// model-owned refs such as `Todo.f.title` should be generated by macros, not
// replaced by unchecked strings that bypass owner/value-type checks.
abstract Field<TModel, TValue>(String) to String {
	public var name(get, never):String;

	public inline function new(name:String) {
		this = name;
	}

	inline function get_name():String {
		return this;
	}

	public static inline function named<TModel, TValue>(name:String):Field<TModel, TValue> {
		return new Field(name);
	}

	public function asc():Order<TModel> {
		return Order.named(this, "asc");
	}

	public function desc():Order<TModel> {
		return Order.named(this, "desc");
	}
}
