# Generated by reflaxe.ruby
$LOAD_PATH.unshift(__dir__)
require "action_cable/engine"
require_relative "app/lib/railshx/runtime/hxruby/core"
require_relative "app/channels/application_cable/connection"
require_relative "app/channels/todos_channel"
require_relative "app/lib/railshx/generated/main"
Main.main
