# Generated by reflaxe.ruby
require "action_cable/engine"
$LOAD_PATH.unshift(__dir__)
require_relative "app/channels/application_cable/connection"
require_relative "app/channels/todos_channel"
require_relative "app/lib/railshx/generated/main"
Main.main
