# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "hxruby/core"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.__hx_fields()
    {instance: [], static: ["main"]}
  end
  def self.main()
    puts(HXRuby.stringify(BlogEngine::Services::EngineGreeting.message("host app")))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  Main.main()
end
