require "json"

metadata = JSON.parse(File.read(File.expand_path("haxelib.json", __dir__)))

Gem::Specification.new do |spec|
  spec.name = "hxruby"
  spec.version = metadata.fetch("version")
  spec.summary = "Runtime helpers for reflaxe.ruby generated output."
  spec.description = "Runtime helpers and Rails rake tasks for Ruby code generated by the reflaxe.ruby Haxe target."
  spec.authors = metadata.fetch("contributors")
  spec.homepage = metadata.fetch("url")
  spec.license = metadata.fetch("license")
  spec.required_ruby_version = ">= 3.2"

  spec.files = [
    "haxelib.json",
    "LICENSE",
    "README.md",
    "hxruby.gemspec",
    *Dir["release-provenance.json"],
    *Dir["artifact-manifest.json"],
    *Dir["lib/**/*.rb"],
    *Dir["runtime/hxruby/**/*.rb"],
    *Dir["scripts/rails/*.rb"],
    *Dir["std/**/*.hx"],
    *Dir["vendor/genes/src/**/*.hx"],
    "vendor/genes/haxelib.json",
    "vendor/genes/readme.md",
  ].sort
  spec.require_paths = ["lib"]
end
