# Generated by reflaxe.ruby
# Rails controller output; Zeitwerk path should match the Ruby constant.
require "action_controller/railtie"
class ApplicationController < ActionController::Base
  # Rails controller generated by reflaxe.ruby
end
