# Generated by reflaxe.ruby
# Rails controller output; Zeitwerk path should match the Ruby constant.
require "action_controller/railtie"
require "turbo-rails"
class ChatMessagesController < ApplicationController
  before_action :authenticate_user!
  def index()
    self.respond_to() do |format|
      format.turbo_stream() { self.render(turbo_stream: turbo_stream.replace("railshx-chat-panel", partial: "todos/chat_panel", locals: {messages: ChatMessage.latest().to_a(), current_user: current_user(), users: User.order(name: :asc).to_a()})) }
      format.html() { self.redirect_to(self.todos_path(), status: :see_other) }
    end
  end
  def create()
    current_user = current_user()
    attrs = self.params().require("chat_message").permit([:body])
    attrs = attrs.merge(user_id: current_user.id)
    message = ChatMessage.create(attrs)
    Turbo::StreamsChannel.broadcast_prepend_to("todoapp:chat", target: "railshx-chat-list", partial: "todos/chat_message", locals: {message: message})
    self.respond_to() do |format|
      format.turbo_stream() { self.head(:no_content) }
      format.html() { self.redirect_to(self.todos_path(), status: :see_other) }
    end
  end
end
