# Generated by reflaxe.ruby
# Rails controller output; Zeitwerk path should match the Ruby constant.
require "action_controller/railtie"
class SessionsController < ApplicationController
  def create_guest()
    guest = User.find_by(email: "guest@example.test")
    if (guest == nil)
      guest = User.create(name: "Guest Workspace", email: "guest@example.test", role: "guest", password: "password123", password_confirmation: "password123")
    end
    if ((guest == nil) || (!guest.persisted?()))
      self.flash()[:alert] = "The guest workspace could not be prepared. Please sign in with the seeded demo account."
      self.redirect_to(self.new_user_session_path(), status: :see_other)
      return
    end
    sign_in(:user, guest)
    self.flash()[:notice] = "Signed in as the guest workspace"
    self.redirect_to(self.todos_path(), status: :see_other)
  end
end
