# Generated by reflaxe.ruby
# Rails controller output; Zeitwerk path should match the Ruby constant.
require "action_controller/railtie"
require "turbo-rails"
require_relative "../lib/railshx/runtime/hxruby/core"
class TodosController < ApplicationController
  before_action :authenticate_user!
  def index()
    current_user = current_user()
    todos = Todo.where(is_completed: false, user_id: current_user.id).includes(:user).order(title: :asc).limit(10).to_a()
    users = User.order(name: :asc).to_a()
    chat_messages = ChatMessage.latest().to_a()
    self.render(template: "todos/index", locals: {todos: todos, users: users, chat_messages: chat_messages, todo_count: todos.length, typed_column_count: 5, current_user: current_user}, layout: "application")
  end
  def create()
    current_user = current_user()
    attrs = self.params().require("todo").permit([:title, :notes])
    attrs = attrs.merge(user_id: current_user.id)
    todo = Todo.create(attrs)
    self.respond_to() do |format|
      format.turbo_stream() { self.render(turbo_stream: turbo_stream.replace("railshx-todo-list", partial: "todos/list", locals: {todos: Todo.where(is_completed: false, user_id: current_user.id).includes(:user).order(title: :asc).limit(10).to_a()})) }
      format.html() { self.redirect_to(self.todos_path(), status: :see_other) }
    end
  end
  def completed()
    current_user = current_user()
    titles = Todo.where(is_completed: true, user_id: current_user.id).order(title: :asc).pluck(:title)
    self.render(plain: ("Completed todos: " + titles.join(", ")), status: :ok)
  end
  def complete()
    current_user = current_user()
    todo = Todo.where(id: self.param_id(), user_id: current_user.id).first()
    if (todo == nil)
      self.render(plain: "Todo not found", status: :not_found)
      return
    end
    todo.update(is_completed: true)
    self.flash()[:notice] = "Todo completed"
    self.redirect_to(self.todos_path(), status: :see_other)
  end
  def optional_report()
    current_user = current_user()
    year = self.params()[:year]
    label = ((year == nil) ? "all years" : year)
    count = Todo.where(user_id: current_user.id).count()
    self.render(plain: (((("Todo report for " + HXRuby.stringify(label)) + ": ") + HXRuby.stringify(count)) + " todos"), status: :ok)
  end
  def file()
    path = self.params()[:path]
    label = ((path == nil) ? "root" : path)
    self.send_data((("RailsHx file route: " + HXRuby.stringify(label)) + "\n"), filename: "todoapp-route.txt", type: "text/plain", disposition: "inline", status: :ok)
  end
  def param_id()
    raw = self.params()[:id]
    parsed = ((raw == nil) ? nil : HXRuby.parse_int(raw))
    return ((parsed == nil) ? 0 : parsed)
  end
end
