# Generated by reflaxe.ruby
# Rails controller output; Zeitwerk path should match the Ruby constant.
require "action_controller/railtie"
require_relative "../lib/railshx/runtime/hxruby/core"
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index()
    current_user = self.require_admin()
    if (current_user == nil)
      return
    end
    self.render_index(current_user, User.new(role: "member"))
  end
  def create()
    current_user = self.require_admin()
    if (current_user == nil)
      return
    end
    attrs = self.params().require("user").permit([:name, :email, :role, :password, :password_confirmation])
    user = User.create(attrs)
    if (!user.persisted?())
      self.flash().now[:alert] = "Could not save user. Review the highlighted details and try again."
      self.render_index_unprocessable(current_user, user)
      return
    end
    self.flash()[:notice] = "User saved"
    self.redirect_to(self.users_path(), status: :see_other)
  end
  def update()
    current_user = self.require_admin()
    if (current_user == nil)
      return
    end
    attrs = self.params().require("user").permit([:name, :email, :role])
    user = User.find(self.param_id())
    if (!user.update(attrs))
      self.flash().now[:alert] = "Could not update user. Review the details and try again."
      self.render_index_unprocessable(current_user, User.new(role: "member"))
      return
    end
    self.flash()[:notice] = "User updated"
    self.redirect_to(self.users_path(), status: :see_other)
  end
  def destroy()
    current_user = self.require_admin()
    if (current_user == nil)
      return
    end
    user = User.find(self.param_id())
    if (user.id == current_user.id)
      self.flash()[:alert] = "Admins cannot delete their own active session"
    else
      user.destroy()
      self.flash()[:notice] = "User removed"
    end
    self.redirect_to(self.users_path(), status: :see_other)
  end
  def render_index(current_user, form_user)
    users = User.order(name: :asc).to_a()
    self.render(template: "users/index", locals: {users: users, current_user: current_user, form_user: form_user}, layout: "application")
  end
  def render_index_unprocessable(current_user, form_user)
    users = User.order(name: :asc).to_a()
    self.render(template: "users/index", locals: {users: users, current_user: current_user, form_user: form_user}, layout: "application", status: :unprocessable_entity)
  end
  def require_admin()
    current_user = current_user()
    if current_user.can_manage_users()
      return current_user
    end
    self.flash()[:alert] = "Admin access is required for user management"
    self.redirect_to(self.todos_path(), status: :see_other)
    return nil
  end
  def param_id()
    raw = self.params()[:id]
    parsed = ((raw == nil) ? nil : HXRuby.parse_int(raw))
    return ((parsed == nil) ? 0 : parsed)
  end
end
