# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class HaxeOnlyLibrary
  def self.__hx_name()
    "HaxeOnlyLibrary"
  end
  def self.headline(value)
    return ("haxe:" + value)
  end
end
