# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
module DecoratedFromHaxe
  def self.__hx_name()
    "HaxeAuthoredDecorated"
  end
  def self.__hx_fields()
    {instance: ["haxeBadge"], static: []}
  end
  def haxe_badge(value)
    return ("haxe-module:" + value)
  end
end
