# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class HaxeRawBackedPost
  def self.__hx_name()
    "HaxeRawBackedPost"
  end
  def self.__hx_fields()
    {instance: ["rawDecorated", "rubyClassName", "title"], static: []}
  end
  include RawDecorated
  attr_accessor :title
  def initialize(title)
    self.title = title
  end
  def ruby_class_name()
    return self.class.name
  end
end
