# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class HaxeOwnedPost
  def self.__hx_name()
    "HaxeOwnedPost"
  end
  def self.__hx_fields()
    {instance: ["decorated", "displayTitle", "title"], static: ["buildLabel"]}
  end
  include Decorated
  extend Decorated
  attr_accessor :title
  def initialize(title)
    self.title = title
  end
  def display_title()
    return ("title:" + self.title)
  end
end
