# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class HaxeOnlyLibrary
  def self.__hx_name()
    "HaxeOnlyLibrary"
  end
  def self.headline(value__hx19559)
    return ("haxe:" + value__hx19559)
  end
end
