# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
module ClassMethodsFromHaxe
  def self.__hx_name()
    "HaxeAuthoredClassMethods"
  end
  def haxe_class_badge(value__hx19221)
    return ("haxe-class:" + value__hx19221)
  end
end
