# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class HaxeModulePost
  def self.__hx_name()
    "HaxeModulePost"
  end
  include DecoratedFromHaxe
  extend ClassMethodsFromHaxe
  def initialize()
    nil
  end
end
