# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class HaxeRawBackedPost
  def self.__hx_name()
    "HaxeRawBackedPost"
  end
  include RawDecorated
  attr_accessor :title
  def initialize(title__hx19558)
    self.title = title__hx19558
  end
  def ruby_class_name()
    return self.class.name
  end
end
