# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class HaxeOwnedPost
  def self.__hx_name()
    "HaxeOwnedPost"
  end
  include Decorated
  extend Decorated
  attr_accessor :title
  def initialize(title__hx19737)
    self.title = title__hx19737
  end
  def display_title()
    return ("title:" + self.title)
  end
end
