# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
module DecoratedFromHaxe
  def self.__hx_name()
    "HaxeAuthoredDecorated"
  end
  def haxe_badge(value__hx19263)
    return ("haxe-module:" + value__hx19263)
  end
end
