# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "./support/extensions"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    legacy = LegacyPost.new("Ship Typed Mixins")
    puts(legacy.slug().to_s())
    puts(LegacyPost.find_by_slug("ship-typed-mixins").slug().to_s())
    owned = HaxeOwnedPost.new("Owned Type")
    puts(owned.decorated().to_s())
    puts(HaxeOwnedPost.build_label("abc").to_s())
    puts(owned.display_title().to_s())
    module_post = HaxeModulePost.new()
    puts(module_post.haxe_badge("typed").to_s())
    puts(HaxeModulePost.haxe_class_badge("typed").to_s())
    raw_backed = HaxeRawBackedPost.new("Raw Island")
    puts(raw_backed.raw_decorated().to_s())
    puts(raw_backed.ruby_class_name().to_s())
    puts("typed patch".headline().to_s())
    puts("typed patch".surround("[", "]").to_s())
    puts("direct patch".headline().to_s())
    puts(HaxeOnlyLibrary.headline("library").to_s())
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
