# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "./support/extensions"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    legacy__hx0 = LegacyPost.new("Ship Typed Mixins")
    puts(HXRuby.stringify(legacy__hx0.slug()))
    puts(HXRuby.stringify(LegacyPost.find_by_slug("ship-typed-mixins").slug()))
    owned__hx0 = HaxeOwnedPost.new("Owned Type")
    puts(HXRuby.stringify(owned__hx0.decorated()))
    puts(HXRuby.stringify(HaxeOwnedPost.build_label("abc")))
    puts(HXRuby.stringify(owned__hx0.display_title()))
    module_post__hx0 = HaxeModulePost.new()
    puts(HXRuby.stringify(module_post__hx0.haxe_badge("typed")))
    puts(HXRuby.stringify(HaxeModulePost.haxe_class_badge("typed")))
    raw_backed__hx0 = HaxeRawBackedPost.new("Raw Island")
    puts(HXRuby.stringify(raw_backed__hx0.raw_decorated()))
    puts(HXRuby.stringify(raw_backed__hx0.ruby_class_name()))
    puts(HXRuby.stringify("typed patch".headline()))
    puts(HXRuby.stringify("typed patch".surround("[", "]")))
    puts(HXRuby.stringify("direct patch".headline()))
    puts(HXRuby.stringify(HaxeOnlyLibrary.headline("library")))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
