# Generated by reflaxe.ruby
require "action_controller/railtie"
$LOAD_PATH.unshift(__dir__)
require_relative "app/lib/railshx/runtime/hxruby/core"
require_relative "app/controllers/todos_controller"
require_relative "app/lib/railshx/generated/main"
Main.main
