# Generated by reflaxe.ruby
$LOAD_PATH.unshift(__dir__)
require "action_controller/railtie"
require_relative "app/haxe_gen/hxruby/core"
require_relative "app/haxe_gen/hxruby/data_define"
require_relative "app/haxe_gen/hxruby/hx_exception"
require_relative "app/haxe_gen/controllers/todos_controller"
require_relative "app/haxe_gen/main"
require_relative "app/haxe_gen/reflaxe/ruby/naming/ruby_naming"
Main.main
