# Generated by reflaxe.ruby
# Rails job output; Zeitwerk path should match the Ruby constant.
require "active_job/railtie"
module Jobs
  class RetryProbeJob < ActiveJob::Base
    queue_as :critical
    retry_on StandardError, wait: 5.seconds, attempts: 2, queue: :retries
    def initialize()
      super()
    end
    def perform(attempt__hx0)
      raise HxException.new(("retry:" + HXRuby.stringify(attempt__hx0)))
    end
  end
end
