# Generated by reflaxe.ruby
# Rails job output; Zeitwerk path should match the Ruby constant.
require "active_job/railtie"
module Jobs
  class SendWelcomeEmailJob < ActiveJob::Base
    queue_as :mailers
    retry_on StandardError, wait: 5.seconds, attempts: 3
    discard_on ActiveJob::DeserializationError
    def initialize()
      super()
    end
    def perform(user_id__hx0, email__hx0)
      payload__hx0 = ("welcome:" + email__hx0)
      Haxe::Log.trace(payload__hx0, {"fileName" => "jobs/SendWelcomeEmailJob.hx", "lineNumber" => 32, "className" => "jobs.SendWelcomeEmailJob", "methodName" => "perform"})
    end
  end
end
