# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class CallableApi
  def self.__hx_name()
    "CallableApi"
  end
  def self.__hx_fields()
    {instance: [], static: ["capture", "decorate", "direct", "forward", "optional"]}
  end
  def self.direct(value)
    return yield(value)
  end
  def self.capture(&block)
    if (block == nil)
      raise(ArgumentError, "required block missing for self.capture")
    end
    return block
  end
  def self.forward(value, &block)
    if (block == nil)
      raise(ArgumentError, "required block missing for self.forward")
    end
    return CallableApi.direct(value, &block)
  end
  def self.optional(value, &block)
    return ((block == nil) ? value : block.call(value))
  end
  def self.decorate(value, prefix:, suffix:)
    return yield(((prefix + value) + suffix))
  end
end
