# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require "tempfile"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.__hx_fields()
    {instance: [], static: ["main"]}
  end
  def self.main()
    Kernel.puts(CallableApi.direct(3) { |value| (value * 2) })
    captured_callback = CallableApi.capture { |value__hx1| (value__hx1 + 10) }
    Kernel.puts(captured_callback.call(1))
    Kernel.puts(CallableApi.forward(4) { |value__hx2| (value__hx2 * 3) })
    Kernel.puts(CallableApi.optional(7))
    Kernel.puts(CallableApi.optional(7) { |value__hx3| (value__hx3 + 5) })
    Kernel.puts(CallableApi.decorate("ruby", prefix: "typed-", suffix: "!") { |value__hx4| value__hx4.upcase() })
    tempfile_result = Tempfile.create("rubyhx-callable-") do |file|
      file.write("extern-block")
      file.rewind()
      file.read()
    end
    Kernel.puts(tempfile_result)
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  Main.main()
end
