# Generated by RailsHx from @:railsRoutes.
# Source: routes.AppRoutes
# Do not edit directly unless you intend to take RailsHx ownership.

Rails.application.routes.draw do
  devise_for :users, class_name: "Models::User", only: [:sessions]
  root "controllers/todos#index"
  resources :todos, controller: "controllers/todos", only: [:index, :create] do
    collection do
      get "completed", to: "controllers/todos#completed"
    end
    member do
      patch "complete", to: "controllers/todos#complete"
    end
  end
  resources :chat_messages, controller: "controllers/chat_messages", only: [:index, :create]
  resources :users, controller: "controllers/users", only: [:index, :create, :update, :destroy]
  post "guest", to: "controllers/sessions#create_guest", as: :guest_sign_in
  get "reports(/:year)", to: "controllers/todos#optional_report", as: :optional_report
  get "files/*path", to: "controllers/todos#file", as: :file
end
