# Generated by RailsHx from @:railsRoutes.
# Source: routes.AppRoutes
# Do not edit directly unless you intend to take RailsHx ownership.

Rails.application.routes.draw do
  root "controllers/todos#index"
  resources :todos, controller: "controllers/todos", only: [:index, :create]
  get "users", to: "controllers/users#index", as: :users
  post "session", to: "controllers/sessions#create", as: :sign_in
  delete "session", to: "controllers/sessions#destroy", as: :sign_out
end
