# Generated by RailsHx from @:railsRoutes.
# Source: routes.AppRoutes
# Do not edit directly unless you intend to take RailsHx ownership.

Rails.application.routes.draw do
  root "controllers/todos#index"
  resources :todos, controller: "controllers/todos", only: [:index, :create] do
    collection do
      get "completed", to: "controllers/todos#completed"
    end
    member do
      patch "complete", to: "controllers/todos#complete"
    end
  end
  resources :chat_messages, controller: "controllers/chat_messages", only: [:index, :create]
  get "users", to: "controllers/users#index", as: :users
  post "session", to: "controllers/sessions#create", as: :sign_in
  delete "session", to: "controllers/sessions#destroy", as: :sign_out
  namespace :admin do
    get "users", to: "controllers/users#index"
  end
  get "reports(/:year)", to: "controllers/todos#optional_report", as: :optional_report
  get "files/*path", to: "controllers/todos#file", as: :file
end
