# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
module Migrations
  class CreateTodos
    def self.__hx_name()
      "migrations.CreateTodos"
    end
    class << self
      attr_accessor :user_model
    end
    @user_model = nil
    class << self
      attr_accessor :todo_model
    end
    @todo_model = nil
  end
end
