# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
module Migrations
  class CreateTodos
    def self.__hx_name()
      "migrations.CreateTodos"
    end
    class << self
      attr_accessor :operations
    end
    @operations = nil
  end
end
