// Generated by examples/todoapp_rails/tools/ExportTodoHooks.hx.
// Do not edit by hand; change shared/TodoHooks.hx and rerun npm run test:todoapp-rails.
export const hooks = {
  attrs: {
    bound: "data-railshx-bound",
    scroll: "data-railshx-scroll",
    flash: "data-railshx-flash"
  },
  classes: {
    shell: "todo-shell",
    form: "todo-form",
    list: "todo-list",
    item: "todo-item",
    dot: "todo-dot"
  },
  ids: {
    openWork: "open-work"
  },
  meta: {
    templateName: "railshx-template",
    templateContent: "todo-index"
  },
  selectors: {
    shell: ".todo-shell",
    form: ".todo-form",
    listItems: ".todo-list .todo-item",
    items: ".todo-item",
    dots: ".todo-item .todo-dot",
    scrollLinks: "[data-railshx-scroll]",
    openWork: "#open-work"
  }
} as const
