# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "../../haxe/io/output"
class Sys
  module Io
    class FileOutput < Haxe::Io::Output
      def self.__hx_name()
        "sys.io.FileOutput"
      end
      def self.__hx_fields()
        {instance: ["close", "flush", "handle", "seek", "tell", "writeByte", "writeBytes"], static: ["seekWhence"]}
      end
      attr_accessor :handle
      def initialize(handle)
        self.handle = handle
      end
      def seek(p, pos)
        self.handle.seek(p, Sys::Io::FileOutput.seek_whence(pos))
      end
      def tell()
        return self.handle.pos()
      end
      def write_byte(value)
        self.handle.write([value & 255].pack('C'))
      end
      def write_bytes(bytes, pos, len)
        if (((pos < 0) || (len < 0)) || ((pos + len) > bytes.length))
          raise HxException.new(Haxe::Io::Error.outside_bounds())
        end
        return self.handle.write(bytes.get_data().slice(pos, len).pack('C*'))
      end
      def flush()
        self.handle.flush()
      end
      def close()
        self.handle.close()
      end
      def self.seek_whence(pos)
        return case pos.__hx_index
when 0
  0
when 1
  1
when 2
  2
end
      end
    end
  end
end
