# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "../../haxe/io/input"
class Sys
  module Io
    class FileInput < Haxe::Io::Input
      def self.__hx_name()
        "sys.io.FileInput"
      end
      def self.__hx_fields()
        {instance: ["close", "eof", "handle", "reachedEof", "readByte", "readBytes", "seek", "tell"], static: ["seekWhence"]}
      end
      attr_accessor :handle
      attr_accessor :reached_eof
      def initialize(handle)
        self.reached_eof = false
        self.handle = handle
      end
      def seek(p, pos)
        self.handle.seek(p, Sys::Io::FileInput.seek_whence(pos))
        self.reached_eof = false
      end
      def tell()
        return self.handle.pos()
      end
      def eof()
        return self.reached_eof
      end
      def read_byte()
        value = self.handle.getbyte()
        if (value == nil)
          self.reached_eof = true
          raise HxException.new(Haxe::Io::Eof.new())
        end
        return value
      end
      def read_bytes(bytes, pos, len)
        if self.reached_eof
          raise HxException.new(Haxe::Io::Eof.new())
        end
        if (((pos < 0) || (len < 0)) || ((pos + len) > bytes.length))
          raise HxException.new(Haxe::Io::Error.outside_bounds())
        end
        remaining = len
        begin
          while (remaining > 0)
            bytes.set((pos).tap { pos = pos + 1 }, self.read_byte())
            remaining = (remaining - 1)
          end
        rescue StandardError => __hx_ex
          hx_tmp = __hx_ex.is_a?(HxException) ? __hx_ex.value : __hx_ex
          nil
        end
        return (len - remaining)
      end
      def close()
        self.handle.close()
      end
      def self.seek_whence(pos)
        return case pos.__hx_index
when 0
  0
when 1
  1
when 2
  2
end
      end
    end
  end
end
