# Generated by reflaxe.ruby
# Enum constructors use hxruby/data_define.rb for Data.define compatibility.
class Sys
  module Io
    module FileSeek
      def self.__hx_name()
        "sys.io.FileSeek"
      end
      def self.__hx_constructs()
        [{name: "SeekBegin", index: 0, method: :seek_begin, arity: 0}, {name: "SeekCur", index: 1, method: :seek_cur, arity: 0}, {name: "SeekEnd", index: 2, method: :seek_end, arity: 0}]
      end
      SeekBegin = Data.define(:__hx_tag, :__hx_index)
      def self.seek_begin()
        SeekBegin.new("SeekBegin", 0)
      end
      SeekCur = Data.define(:__hx_tag, :__hx_index)
      def self.seek_cur()
        SeekCur.new("SeekCur", 1)
      end
      SeekEnd = Data.define(:__hx_tag, :__hx_index)
      def self.seek_end()
        SeekEnd.new("SeekEnd", 2)
      end
    end
  end
end
