#!/usr/bin/env node

const { existsSync, mkdirSync, readFileSync, writeFileSync } = require("node:fs");
const { dirname, resolve } = require("node:path");

const args = process.argv.slice(2);
const inputPath = valueAfter("--input");
const outputPath = resolve(valueAfter("--output") ?? "src_haxe/routes/Routes.hx");
const packageName = valueAfter("--package") ?? "routes";
const className = valueAfter("--class") ?? "Routes";

const input = inputPath ? readFileSync(resolve(inputPath), "utf8") : readStdin();
const helpers = parseRoutes(input);
const output = renderRoutes(packageName, className, helpers);

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output);

function valueAfter(name) {
  const index = args.indexOf(name);
  if (index === -1) {
    return null;
  }
  return args[index + 1] ?? null;
}

function readStdin() {
  try {
    return readFileSync(0, "utf8");
  } catch (_) {
    return "";
  }
}

function parseRoutes(input) {
  const verbs = new Set(["GET", "POST", "PATCH", "PUT", "DELETE", "OPTIONS", "HEAD"]);
  const seen = new Set();
  const helpers = [];

  for (const rawLine of input.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("Prefix ") || line.startsWith("rails_")) {
      continue;
    }

    const tokens = line.split(/\s+/);
    let prefix = null;
    let verb = null;
    let uri = null;
    if (verbs.has(tokens[0])) {
      verb = tokens[0];
      uri = tokens[1];
    } else if (verbs.has(tokens[1])) {
      prefix = tokens[0];
      verb = tokens[1];
      uri = tokens[2];
    }
    if (!prefix || !verb || !uri || seen.has(prefix)) {
      continue;
    }

    seen.add(prefix);
    helpers.push({ prefix, params: routeParams(uri) });
  }

  return helpers;
}

function routeParams(uri) {
  const cleaned = uri.replace(/\(\.:format\)/g, "");
  const params = [];
  const seen = new Set();
  const matcher = /:([A-Za-z_][A-Za-z0-9_]*)/g;
  let match = matcher.exec(cleaned);
  while (match) {
    if (!seen.has(match[1])) {
      seen.add(match[1]);
      params.push(match[1]);
    }
    match = matcher.exec(cleaned);
  }
  return params;
}

function renderRoutes(packageName, className, helpers) {
  const lines = [
    "package " + packageName + ";",
    "",
    "// Generated by scripts/rails/generate-routes.js from Rails route output.",
    '@:native("self")',
    "extern class " + className + " {",
  ];

  for (const helper of helpers) {
    appendHelper(lines, helper.prefix + "_path", helper.params);
    appendHelper(lines, helper.prefix + "_url", helper.params);
  }

  if (helpers.length === 0) {
    lines.push("\t// No named Rails routes found.");
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function appendHelper(lines, rubyName, params) {
  lines.push('\t@:native("' + rubyName + '")');
  lines.push("\tpublic static function " + haxeMethodName(rubyName) + "(" + params.map(paramArg).join(", ") + "):String;");
  lines.push("");
}

function haxeMethodName(rubyName) {
  return rubyName.replace(/_([a-z0-9])/g, (_, char) => char.toUpperCase());
}

function paramArg(name) {
  return haxeMethodName(name) + ":Dynamic";
}
