#!/usr/bin/env node

const { mkdirSync, writeFileSync } = require("node:fs");
const { dirname, join, resolve } = require("node:path");

const args = process.argv.slice(2);
const modelName = required("--model");
const outputDir = resolve(valueAfter("--output") ?? ".");
const fields = parseFields(valueAfter("--fields") ?? "");
const validations = new Set((valueAfter("--validate") ?? "").split(",").map((value) => value.trim()).filter(Boolean));
const withController = args.includes("--controller");

const tableName = pluralize(fileName(modelName));
const controllerName = pluralize(modelName) + "Controller";
const resourceName = fileName(modelName);
const controllerFile = fileName(controllerName);

write("src_haxe/models/" + modelName + ".hx", renderModel());
write("src_haxe/routes/Routes.hx", renderRoutes());
write("src_haxe/Main.hx", renderMain());
write("db/migrate/20260101000000_create_" + tableName + ".rb", renderMigration());
write("build.hxml", renderBuild());
if (withController) {
  write("src_haxe/controllers/" + controllerName + ".hx", renderController());
}

function valueAfter(name) {
  const index = args.indexOf(name);
  if (index === -1) {
    return null;
  }
  return args[index + 1] ?? null;
}

function required(name) {
  const value = valueAfter(name);
  if (!value) {
    console.error(`Missing required argument ${name}`);
    process.exit(1);
  }
  return value;
}

function parseFields(raw) {
  if (!raw.trim()) {
    return [];
  }
  return raw.split(",").map((entry) => {
    const [name, type] = entry.split(":").map((part) => part.trim());
    if (!name || !type) {
      console.error(`Invalid field "${entry}". Expected name:Type.`);
      process.exit(1);
    }
    return { name, type };
  });
}

function renderModel() {
  const lines = [
    "package models;",
    "",
    '@:railsModel("' + tableName + '")',
    "class " + modelName + " extends rails.active_record.Base<" + modelName + "> {",
  ];
  for (const field of fields) {
    lines.push("\t@:railsColumn public var " + field.name + ":" + field.type + ";");
  }
  for (const fieldName of validations) {
    lines.push("");
    lines.push("\t@:validates({presence: true})");
    lines.push("\tpublic var " + fieldName + "Validation:rails.ActiveRecord.Validation<String>;");
  }
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function renderController() {
  const permitted = fields.map((field) => '"' + field.name + '"').join(", ");
  return [
    "package controllers;",
    "",
    "import models." + modelName + ";",
    "import rails.macros.ParamsMacro;",
    "import routes.Routes;",
    "",
    "@:railsController",
    "class " + controllerName + " extends rails.action_controller.Base {",
    "\tpublic function index() {",
    "\t\tvar " + tableName + " = " + modelName + ".where({});",
    "\t\trender({json: " + tableName + "});",
    "\t}",
    "",
    "\tpublic function create() {",
    "\t\tvar attrs = ParamsMacro.requirePermit(this.params(), " + JSON.stringify(resourceName) + ", [" + permitted + "]);",
    "\t\tvar " + resourceName + " = " + modelName + ".create(attrs);",
    "\t\tredirectTo(Routes." + pluralize(modelName.charAt(0).toLowerCase() + modelName.slice(1)) + "Path());",
    "\t}",
    "}",
    "",
  ].join("\n");
}

function renderRoutes() {
  const methodPrefix = pluralize(modelName.charAt(0).toLowerCase() + modelName.slice(1));
  return [
    "package routes;",
    "",
    "// Generated by scripts/rails/scaffold.js.",
    '@:native("self")',
    "extern class Routes {",
    '\t@:native("' + tableName + '_path")',
    "\tpublic static function " + methodPrefix + "Path():String;",
    "",
    '\t@:native("' + tableName + '_url")',
    "\tpublic static function " + methodPrefix + "Url():String;",
    "",
    "}",
    "",
  ].join("\n");
}

function renderMain() {
  const imports = withController ? ["import controllers." + controllerName + ";", "import models." + modelName + ";"] : ["import models." + modelName + ";"];
  const controllerLine = withController ? "\t\tvar controller:" + controllerName + " = null;\n\t\tSys.println(controller == null);" : "";
  return [
    ...imports,
    "",
    "class Main {",
    "\tstatic function main() {",
    "\t\tvar model:" + modelName + " = null;",
    "\t\tSys.println(model == null);",
    controllerLine,
    "\t}",
    "}",
    "",
  ].join("\n");
}

function renderMigration() {
  const lines = [
    "class Create" + pluralize(modelName) + " < ActiveRecord::Migration[7.1]",
    "  def change",
    "    create_table :" + tableName + " do |t|",
  ];
  for (const field of fields) {
    lines.push("      t." + migrationType(field.type) + " :" + fileName(field.name));
  }
  lines.push("");
  lines.push("      t.timestamps");
  lines.push("    end");
  lines.push("  end");
  lines.push("end");
  lines.push("");
  return lines.join("\n");
}

function renderBuild() {
  return [
    "-D reflaxe_runtime",
    "-D reflaxe_ruby_rails",
    "-cp src_haxe",
    "-main Main",
    "",
  ].join("\n");
}

function migrationType(type) {
  switch (type) {
    case "String": return "string";
    case "Bool": return "boolean";
    case "Int": return "integer";
    case "Float": return "float";
    default: return "string";
  }
}

function write(relativePath, content) {
  const fullPath = join(outputDir, relativePath);
  mkdirSync(dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, content);
}

function pluralize(value) {
  return value.endsWith("s") ? value : value + "s";
}

function fileName(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[-\s]+/g, "_")
    .toLowerCase();
}
