# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
module Shared
  class TodoHooks
    def self.__hx_name()
      "shared.TodoHooks"
    end
    def self.class_selector(value__hx21144)
      return ("." + value__hx21144)
    end
    def self.id_selector(value__hx21145)
      return ("#" + value__hx21145)
    end
    def self.attr_selector(value__hx21146)
      return (("[" + value__hx21146) + "]")
    end
    def self.anchor_href(value__hx21147)
      return ("#" + value__hx21147)
    end
  end
end
