# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
module Shared
  class TodoHooks
    def self.__hx_name()
      "shared.TodoHooks"
    end
    def self.class_selector(value__hx0)
      return ("." + value__hx0)
    end
    def self.id_selector(value__hx0)
      return ("#" + value__hx0)
    end
    def self.attr_selector(value__hx0)
      return (("[" + value__hx0) + "]")
    end
    def self.anchor_href(value__hx0)
      return ("#" + value__hx0)
    end
  end
end
