# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    Jobs::SendWelcomeEmailJob.perform_later(42, "reader@example.test")
    Jobs::SendWelcomeEmailJob.perform_now(7, "now@example.test")
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
