# Generated by reflaxe.ruby
# Enum constructors use hxruby/data_define.rb for Data.define compatibility.
module Color
  def self.__hx_name()
    "Color"
  end
  def self.__hx_constructs()
    [{name: "Red", index: 0, method: :red, arity: 0}, {name: "Green", index: 1, method: :green, arity: 0}, {name: "Blue", index: 2, method: :blue, arity: 0}]
  end
  Red = Data.define(:__hx_tag, :__hx_index)
  def self.red()
    Red.new("Red", 0)
  end
  Green = Data.define(:__hx_tag, :__hx_index)
  def self.green()
    Green.new("Green", 1)
  end
  Blue = Data.define(:__hx_tag, :__hx_index)
  def self.blue()
    Blue.new("Blue", 2)
  end
end
