# Generated by reflaxe.ruby
# Enum constructors use hxruby/data_define.rb for Data.define compatibility.
module Color
  Red = Data.define(:__hx_tag, :__hx_index)
  def self.red()
    Red.new("Red", 0)
  end
  Green = Data.define(:__hx_tag, :__hx_index)
  def self.green()
    Green.new("Green", 1)
  end
  Blue = Data.define(:__hx_tag, :__hx_index)
  def self.blue()
    Blue.new("Blue", 2)
  end
end
