# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    number__hx18222 = 2
    case number__hx18222
    when 1
      puts(HXRuby.stringify("one"))
    when 2
      puts(HXRuby.stringify("two"))
    else
      puts(HXRuby.stringify("other"))
    end
    color__hx18295 = Color.green()
    case color__hx18295.__hx_index
    when 0
      puts(HXRuby.stringify("red"))
    when 1
      puts(HXRuby.stringify("green"))
    when 2
      puts(HXRuby.stringify("blue"))
    end
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
