# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "hxruby/core"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    number = 2
    case number
    when 1
      puts(HXRuby.stringify("one"))
    when 2
      puts(HXRuby.stringify("two"))
    else
      puts(HXRuby.stringify("other"))
    end
    color = Color.green()
    case color.__hx_index
    when 0
      puts(HXRuby.stringify("red"))
    when 1
      puts(HXRuby.stringify("green"))
    when 2
      puts(HXRuby.stringify("blue"))
    end
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  Main.main()
end
