# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    number = 2
    case number
    when 1
      puts("one".to_s())
    when 2
      puts("two".to_s())
    else
      puts("other".to_s())
    end
    color = Color.green()
    case color.__hx_index
    when 0
      puts("red".to_s())
    when 1
      puts("green".to_s())
    when 2
      puts("blue".to_s())
    end
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
