package controllers;

import app.auth.UserAuth;
import models.User;
import rails.action_controller.Status;
import routes.Routes;

// DeviseHx guest session controller.
//
// Demonstrates: a typed RailsHx convenience flow layered over real Devise.
// The regular login/logout routes are generated by `DeviseRoutes.deviseFor`;
// this action signs in a seeded guest through `UserAuth.signIn(...)`.
// Type safety: `UserAuth.signIn` only accepts `User`, and `User.f.email`
// keeps the lookup tied to a real model field.
// IntelliSense: editors should complete `UserAuth.signIn`, `User.f.email`, and
// typed route helpers.
// Ruby/Rails output: ordinary Devise/Rails `sign_in(:user, user)`, flash, and
// `redirect_to`.
@:railsController
class SessionsController extends ApplicationController {
	static final lifecycle = [];

	public function createGuest() {
		var guest:Null<User> = User.findBy({email: "guest@example.test"});
		if (guest == null) {
			guest = User.create({
				name: "Guest Workspace",
				email: "guest@example.test",
				role: "guest",
				password: "password123",
				passwordConfirmation: "password123"
			});
		}
		if (guest == null || !guest.persisted()) {
			this.flash.alert("The guest workspace could not be prepared. Please sign in with the seeded demo account.");
			redirectToLocation(Routes.newUserSessionPath(), {status: Status.seeOther});
			return;
		}
		UserAuth.signIn(this, guest);
		this.flash.notice("Signed in as the guest workspace");
		redirectToLocation(Routes.todosPath(), {status: Status.seeOther});
	}
}
