# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
module Views
  class WelcomeEmailHtmlView
    # Rails ActionView template marker. The ERB artifact is generated under app/views.
  end
end
