# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require "date"
require "json"
require "set"
require_relative "./support/native_date"
require_relative "./support/native_time"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    NativeJson.parse("{}")
    NativeDate.today()
    puts("require metadata".to_s())
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
