# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require "date"
require "json"
require "set"
require_relative "./support/native_date"
require_relative "./support/native_time"
require_relative "hxruby/core"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.__hx_fields()
    {instance: [], static: ["main"]}
  end
  def self.main()
    NativeJson.parse("{}")
    NativeDate.today()
    puts(HXRuby.stringify("require metadata"))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  Main.main()
end
