# Generated by reflaxe.ruby
$LOAD_PATH.unshift(__dir__)
require "date"
require "json"
require "set"
require_relative "./support/native_date"
require_relative "./support/native_time"
require_relative "hxruby/core"
require_relative "hxruby/data_define"
require_relative "main"
Main.main
