package routes;

import rails.routing.RouteParam;

// Generated by HXRuby::Generators::Routes from Rails route output.
//
// Demonstrates: Rails-owned routes converted into typed Haxe extern methods.
// Type safety: Haxe callers use named route helpers instead of hand-written
// path strings; helper arity and required route params are checked at compile time.
// IntelliSense: editors should complete named route helpers from this extern.
// Ruby/Rails output: direct calls to Rails route helpers such as `todos_path`.
@:native("self")
extern class DeviseRoutes {
	@:native("new_user_session_path")
	public static function newUserSessionPath():String;

	@:native("new_user_session_url")
	public static function newUserSessionUrl():String;

	@:native("user_session_path")
	public static function userSessionPath():String;

	@:native("user_session_url")
	public static function userSessionUrl():String;

	@:native("destroy_user_session_path")
	public static function destroyUserSessionPath():String;

	@:native("destroy_user_session_url")
	public static function destroyUserSessionUrl():String;

	@:native("new_user_password_path")
	public static function newUserPasswordPath():String;

	@:native("new_user_password_url")
	public static function newUserPasswordUrl():String;

	@:native("edit_user_password_path")
	public static function editUserPasswordPath():String;

	@:native("edit_user_password_url")
	public static function editUserPasswordUrl():String;

	@:native("user_password_path")
	public static function userPasswordPath():String;

	@:native("user_password_url")
	public static function userPasswordUrl():String;

	@:native("cancel_user_registration_path")
	public static function cancelUserRegistrationPath():String;

	@:native("cancel_user_registration_url")
	public static function cancelUserRegistrationUrl():String;

	@:native("new_user_registration_path")
	public static function newUserRegistrationPath():String;

	@:native("new_user_registration_url")
	public static function newUserRegistrationUrl():String;

	@:native("edit_user_registration_path")
	public static function editUserRegistrationPath():String;

	@:native("edit_user_registration_url")
	public static function editUserRegistrationUrl():String;

	@:native("user_registration_path")
	public static function userRegistrationPath():String;

	@:native("user_registration_url")
	public static function userRegistrationUrl():String;

	@:native("new_user_confirmation_path")
	public static function newUserConfirmationPath():String;

	@:native("new_user_confirmation_url")
	public static function newUserConfirmationUrl():String;

	@:native("user_confirmation_path")
	public static function userConfirmationPath():String;

	@:native("user_confirmation_url")
	public static function userConfirmationUrl():String;

	@:native("new_user_unlock_path")
	public static function newUserUnlockPath():String;

	@:native("new_user_unlock_url")
	public static function newUserUnlockUrl():String;

	@:native("user_unlock_path")
	public static function userUnlockPath():String;

	@:native("user_unlock_url")
	public static function userUnlockUrl():String;

	@:native("user_github_omniauth_authorize_path")
	public static function userGithubOmniauthAuthorizePath():String;

	@:native("user_github_omniauth_authorize_url")
	public static function userGithubOmniauthAuthorizeUrl():String;

	@:native("user_github_omniauth_callback_path")
	public static function userGithubOmniauthCallbackPath():String;

	@:native("user_github_omniauth_callback_url")
	public static function userGithubOmniauthCallbackUrl():String;
}
