# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "../hxruby/core"
class Main
  class FilesystemParityAssert
    def self.__hx_name()
      "_Main.FilesystemParityAssert"
    end
    def self.__hx_fields()
      {instance: [], static: ["equal", "isFalse", "isTrue", "raises"]}
    end
    def self.equal(expected, actual, label)
      if (actual != expected)
        raise HxException.wrap(((((("filesystem parity failed: " + label) + "; expected ") + HXRuby.stringify(expected)) + ", got ") + HXRuby.stringify(actual)))
      end
    end
    def self.is_true(condition, label)
      if (!condition)
        raise HxException.wrap(("filesystem parity failed: " + label))
      end
    end
    def self.is_false(condition, label)
      Main::FilesystemParityAssert.is_true((!condition), label)
    end
    def self.raises(action, label)
      raised = false
      begin
        action.call()
      rescue StandardError => haxe_exception
        haxe_thrown = (haxe_exception.is_a?(HxException) ? haxe_exception.value : haxe_exception)
        hx_tmp = haxe_thrown
        raised = true
      end
      Main::FilesystemParityAssert.is_true(raised, label)
    end
  end
end
