# Generated by reflaxe.ruby
# Rails model output; Zeitwerk path should match the Ruby constant.
require "active_record"
require "active_storage/engine"
class Profile < ApplicationRecord
  self.table_name = "profiles"
  has_one_attached :avatar
  has_many_attached :gallery
  # haxe column id: Int
  # haxe column name: String
  def initialize(*args, **kwargs)
    args = args + [kwargs] unless kwargs.empty?
    super(*args)
  end
end
