# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "./support/native_interop"
class Main
  def self.main()
    count = 2
    puts(HXRuby.stringify(NativeInterop.describe(name: "ruby", count: 2)))
    puts(HXRuby.stringify(NativeInterop.describe_details(name: "ruby", tags: [:fast, :typed], count: count)))
    NativeInterop.each([1, 2]) { |value| puts(HXRuby.stringify(value)) }
    NativeInterop.with_options([3, 4], prefix: "item", tags: [:safe], count: count) do |value|
      Kernel.print("item=")
      puts(HXRuby.stringify(value))
    end
    puts(HXRuby.stringify(NativeInterop.accept_symbol(:ready)))
    Kernel.puts("kernel")
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
