# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "./support/native_interop"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    count__hx18909 = 2
    puts(HXRuby.stringify(NativeInterop.describe(name: "ruby", count: 2)))
    puts(HXRuby.stringify(NativeInterop.describe_details(name: "ruby", tags: [:fast, :typed], count: count__hx18909)))
    NativeInterop.each([1, 2]) { |value__hx18982| puts(HXRuby.stringify(value__hx18982)) }
    NativeInterop.with_options([3, 4], prefix: "item", tags: [:safe], count: count__hx18909) do |value__hx18983|
      Kernel.print("item=")
      puts(HXRuby.stringify(value__hx18983))
    end
    puts(HXRuby.stringify(NativeInterop.accept_symbol(:ready)))
    Kernel.puts("kernel")
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
