# Generated by reflaxe.ruby
$LOAD_PATH.unshift(__dir__)
require_relative "./support/native_interop"
require_relative "hxruby/core"
require_relative "hxruby/data_define"
require_relative "main"
Main.main
