# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    total = 7
    if (total > 5)
      puts("big".to_s())
    else
      puts("small".to_s())
    end
    i = 0
    while (i < 2)
      puts("loop".to_s())
      i = (i + 1)
    end
    puts([1, 2, 3].to_s())
    puts({"name" => "ruby", "count" => 3}.to_s())
    puts("done".to_s())
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
