# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    total__hx17340 = 7
    if (total__hx17340 > 5)
      puts(HXRuby.stringify("big"))
    else
      puts(HXRuby.stringify("small"))
    end
    i__hx17413 = 0
    while (i__hx17413 < 2)
      puts(HXRuby.stringify("loop"))
      i__hx17413 = (i__hx17413 + 1)
    end
    puts(HXRuby.stringify([1, 2, 3]))
    puts(HXRuby.stringify({"name" => "ruby", "count" => 3}))
    puts(HXRuby.stringify("done"))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
