# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    found__hx20504 = Models::Todo.includes(:user).where(title: "ship", status: "open").where(completed: false).joins(:user).order(title: :asc).limit(10)
    scoped__hx20505 = Models::Todo.incomplete().includes(:user).limit(5)
    users__hx20506 = Models::User.includes(:todos).joins(:todos).where(name: "owner")
    made__hx20507 = Models::Todo.create(title: "ship", user_id: 1)
    logs__hx20508 = Models::AuditLog.where(event_count: 1).order(event_count: :desc)
    loaded__hx20509 = Models::Todo.find(1)
    found_by__hx20510 = Models::Todo.find_by(external_id: "ship-1")
    relation_found_by__hx20511 = Models::Todo.where(title: "ship").find_by(completed: false)
    assigned__hx20512 = Models::Todo.where(title: "assigned").order(title: :asc).limit(5)
    assigned_found_by__hx20513 = assigned__hx20512.find_by(external_id: "assigned-1")
    first__hx20514 = found__hx20504.first()
    puts(HXRuby.stringify((found__hx20504 == nil)))
    puts(HXRuby.stringify((scoped__hx20505 == nil)))
    puts(HXRuby.stringify((users__hx20506 == nil)))
    puts(HXRuby.stringify((made__hx20507 == nil)))
    puts(HXRuby.stringify((logs__hx20508 == nil)))
    puts(HXRuby.stringify((loaded__hx20509 == nil)))
    puts(HXRuby.stringify((found_by__hx20510 == nil)))
    puts(HXRuby.stringify((relation_found_by__hx20511 == nil)))
    puts(HXRuby.stringify((assigned_found_by__hx20513 == nil)))
    puts(HXRuby.stringify((first__hx20514 == nil)))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
