# Generated by reflaxe.ruby
# Placeholder output; lowering is implemented by later compiler beads.
class Main
  def self.main()
    found = Models::Todo.where(title: "ship")
    made = Models::Todo.create(title: "ship")
    puts(HXRuby.stringify((found == nil)))
    puts(HXRuby.stringify((made == nil)))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
