# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    found__hx19042 = Models::Todo.where(title: "ship").order(title: :asc).limit(10)
    made__hx19043 = Models::Todo.create(title: "ship")
    logs__hx19044 = Models::AuditLog.where(event_count: 1).order(event_count: :desc)
    first__hx19045 = found__hx19042.first()
    puts(HXRuby.stringify((found__hx19042 == nil)))
    puts(HXRuby.stringify((made__hx19043 == nil)))
    puts(HXRuby.stringify((logs__hx19044 == nil)))
    puts(HXRuby.stringify((first__hx19045 == nil)))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
