# Generated by reflaxe.ruby
# Rails ActionCable connection output; Zeitwerk path should match the Ruby constant.
require "action_cable/engine"
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user
    class << self
      attr_accessor :auth_token
    end
    @auth_token = "token"
    def connect()
      if (request.params["token"] == "reject")
        self.reject_unauthorized_connection()
        return
      end
      self.current_user = {"id" => 42}
    end
  end
end
