# Generated by reflaxe.ruby
require "active_support/isolated_execution_state"
require "active_support/notifications"
$LOAD_PATH.unshift(__dir__)
require_relative "app/lib/railshx/runtime/hxruby/core"
require_relative "app/lib/railshx/generated/main"
Main.main
