# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    add_one__hx18769 = ->(x__hx18768) { (x__hx18768 + 1) }
    puts(HXRuby.stringify(add_one__hx18769.call(2)))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
