# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.main()
    add_one__hx16591 = ->(x__hx16590) { (x__hx16590 + 1) }
    puts(HXRuby.stringify(add_one__hx16591.call(2)))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
