# Generated by reflaxe.ruby
$LOAD_PATH.unshift(__dir__)
require_relative "app/haxe_gen/hxruby/core"
require_relative "app/haxe_gen/hxruby/data_define"
require_relative "app/haxe_gen/admin/todo_item"
require_relative "app/haxe_gen/main"
Main.main
