package app.auth;

import devisehx.Auth;
import devisehx.AuthFilter;
import devisehx.DeviseScope;
import devisehx.RouteResource;
import devisehx.ScopeName;
import models.User;
import rails.action_controller.Base;

// Generated by DeviseHx from deterministic Bundler, route, model, and schema metadata.
// Runtime ownership stays with Devise/Rails; this class is an app-local typed
// contract that gives Haxe completion for the concrete Devise scope helpers.
final class UserAuth {
	public static final scope:DeviseScope<User> = DeviseScope.of(ScopeName.named("user"), RouteResource.named("users"), User);

	public static final authenticate:AuthFilter<User> = Auth.require(scope);

	public static inline function current(controller:Base):Null<User> {
		return Auth.current(controller, scope);
	}

	public static inline function currentRequired(controller:Base):User {
		return Auth.currentRequired(controller, scope);
	}

	public static inline function signedIn(controller:Base):Bool {
		return Auth.signedIn(controller, scope);
	}

	public static inline function signIn(controller:Base, resource:User):Void {
		Auth.signIn(controller, scope, resource);
	}

	public static inline function signOut(controller:Base):Void {
		Auth.signOut(controller, scope);
	}
}
