package views;

import rails.action_view.HtmlNode;

// Typed Rails layout authored as HHX.
//
// Demonstrates: Rails layout primitives (`csrf_meta_tags`, `rails_yield`,
// `yield_content`) written as typed inline HHX rather than hand-authored ERB.
// Type safety: `@:railsTemplateAst("render")` requires `render()` to return an
// `HtmlNode`; unknown helper tags fail in the HHX macro/compiler path.
// IntelliSense: editors should complete imported Haxe types and show this class
// as usable via `Template.layout(ApplicationLayoutView)`.
// Ruby/Rails output: `app/views/layouts/application.html.erb` generated by the
// compiler.
@:railsTemplate("layouts/application")
@:railsTemplateAst("render")
class ApplicationLayoutView {
	public static function render():HtmlNode {
		return <>
			<doctype_html />
			<html>
				<head>
					<title>RailsHx Interop</title>
					<meta name="viewport" content="width=device-width,initial-scale=1" />
					<csrf_meta_tags />
					<csp_meta_tag />
					<yield_content name="head" />
					<stylesheet_link_tag name="application" />
				</head>
				<body>
					<rails_yield />
				</body>
			</html>
		</>;
	}
}
