# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    profile__hx0 = Models::Profile.new()
    has_avatar__hx0 = profile__hx0.avatar().attached?()
    profile__hx0.avatar().attach("avatar.png")
    profile__hx0.avatar().purge()
    has_gallery__hx0 = profile__hx0.gallery().attached?()
    profile__hx0.gallery().attach(["one.png", "two.png"])
    profile__hx0.gallery().purge()
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
