# Generated by reflaxe.ruby
# Placeholder output; lowering is implemented by later compiler beads.
require "json"
require_relative "./support/ruby_interop"
class Main
  def self.main()
    count = 3
    puts(HXRuby.stringify(JSON.generate({"name" => "ruby", "count" => 2})))
    puts(HXRuby.stringify(File.basename("/tmp/reflaxe.rb")))
    puts(HXRuby.stringify(RubyInterop.describe(name: "interop", count: 3)))
    puts(HXRuby.stringify(RubyInterop.describe_details(name: "interop", tags: [:safe, :typed], count: count)))
    RubyInterop.each([4, 5]) { |value| puts(HXRuby.stringify(value)) }
    RubyInterop.with_options([6, 7], prefix: "interop", tags: [:block], count: count) do |value|
      Kernel.print("interop=")
      puts(HXRuby.stringify(value))
    end
    puts(HXRuby.stringify(RubyInterop.accept_symbol(:ready)))
    Kernel.puts("kernel")
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
