# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require "json"
require_relative "./support/ruby_interop"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    count__hx17242 = 3
    puts(HXRuby.stringify(JSON.generate({"name" => "ruby", "count" => 2})))
    puts(HXRuby.stringify(File.basename("/tmp/reflaxe.rb")))
    puts(HXRuby.stringify(RubyInterop.describe(name: "interop", count: 3)))
    puts(HXRuby.stringify(RubyInterop.describe_details(name: "interop", tags: [:safe, :typed], count: count__hx17242)))
    RubyInterop.each([4, 5]) { |value__hx17315| puts(HXRuby.stringify(value__hx17315)) }
    RubyInterop.with_options([6, 7], prefix: "interop", tags: [:block], count: count__hx17242) do |value__hx17316|
      Kernel.print("interop=")
      puts(HXRuby.stringify(value__hx17316))
    end
    puts(HXRuby.stringify(RubyInterop.accept_symbol(:ready)))
    Kernel.puts("kernel")
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
