# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require "json"
require_relative "./support/ruby_interop"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    count = 3
    puts(JSON.generate({"name" => "ruby", "count" => 2}).to_s())
    puts(File.basename("/tmp/reflaxe.rb").to_s())
    puts(RubyInterop.describe(name: "interop", count: 3).to_s())
    puts(RubyInterop.describe_details(name: "interop", tags: [:safe, :typed], count: count).to_s())
    RubyInterop.each([4, 5]) { |value| puts(value.to_s()) }
    RubyInterop.with_options([6, 7], prefix: "interop", tags: [:block], count: count) do |value__hx1|
      Kernel.print("interop=")
      puts(value__hx1.to_s())
    end
    puts(RubyInterop.accept_symbol(:ready).to_s())
    Kernel.puts("kernel")
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
