# frozen_string_literal: true

require "fileutils"
require "digest"
require "json"

module HXRuby
  module Generators
    module Common
      module_function

      GENERATED_HEADER = "# Generated by RailsHx."
      MANIFEST_VERSION = 1

      def write_file(path, content, force: false, executable: false, root: nil, kind: "file", source: nil, header: false)
        absolute_path = File.expand_path(path)
        absolute_root = root ? File.expand_path(root) : nil
        assert_inside_root!(absolute_path, absolute_root) if absolute_root

        body = header ? with_generated_header(content) : content
        if File.exist?(absolute_path) && !force && !owned_file?(absolute_path, absolute_root)
          raise Error, "Refusing to overwrite non-RailsHx-owned file #{absolute_path}. Re-run with --force only if you intend to take ownership."
        end

        FileUtils.mkdir_p(File.dirname(absolute_path))
        File.write(absolute_path, body)
        FileUtils.chmod(0o755, absolute_path) if executable
        record_manifest_entry(absolute_root, absolute_path, body, kind: kind, source: source) if absolute_root
      end

      def with_generated_header(content)
        text = content.to_s
        return text if text.start_with?(GENERATED_HEADER)

        "#{GENERATED_HEADER}\n# Do not edit this file directly unless you intend to take RailsHx ownership.\n#{text}"
      end

      def owned_file?(path, root = nil)
        generated_header?(path) || manifest_owned?(root, path)
      end

      def generated_header?(path)
        return false unless File.file?(path)

        first_line = File.open(path, &:readline).strip
        first_line.start_with?(GENERATED_HEADER)
      rescue EOFError
        false
      end

      def manifest_path(root)
        File.join(root, ".railshx", "manifest.json")
      end

      def read_manifest(root)
        path = manifest_path(root)
        return { "version" => MANIFEST_VERSION, "outputs" => [] } unless File.file?(path)

        parsed = JSON.parse(File.read(path))
        outputs = parsed["outputs"].is_a?(Array) ? parsed["outputs"] : []
        { "version" => parsed["version"] || MANIFEST_VERSION, "outputs" => outputs }
      rescue JSON::ParserError => error
        raise Error, "Invalid RailsHx manifest #{path}: #{error.message}"
      end

      def manifest_owned?(root, path)
        return false unless root

        relative = relative_path(root, path)
        read_manifest(root).fetch("outputs").any? { |entry| entry["output"] == relative }
      end

      def record_manifest_entry(root, path, content, kind:, source:)
        relative = relative_path(root, path)
        manifest = read_manifest(root)
        outputs = manifest.fetch("outputs").reject { |entry| entry["output"] == relative }
        outputs << {
          "output" => relative,
          "kind" => kind.to_s,
          "source" => source || "hxruby:generator",
          "sha256" => Digest::SHA256.hexdigest(content),
        }
        manifest["version"] = MANIFEST_VERSION
        manifest["outputs"] = outputs.sort_by { |entry| entry.fetch("output") }

        path = manifest_path(root)
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, JSON.pretty_generate(manifest) + "\n")
      end

      def clean_owned_outputs(root)
        absolute_root = File.expand_path(root)
        manifest = read_manifest(absolute_root)
        manifest.fetch("outputs").each do |entry|
          output = entry["output"].to_s
          next if output.empty?

          path = File.expand_path(output, absolute_root)
          assert_inside_root!(path, absolute_root)
          FileUtils.rm_f(path)
          prune_empty_dirs(File.dirname(path), absolute_root)
        end
        manifest["outputs"] = []
        path = manifest_path(absolute_root)
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, JSON.pretty_generate(manifest) + "\n")
      end

      def relative_path(root, path)
        expanded_root = File.expand_path(root)
        expanded_path = File.expand_path(path)
        assert_inside_root!(expanded_path, expanded_root)
        expanded_path.delete_prefix("#{expanded_root}#{File::SEPARATOR}")
      end

      def assert_inside_root!(path, root)
        unless path == root || path.start_with?("#{root}#{File::SEPARATOR}")
          raise Error, "Generated path #{path} must stay inside #{root}"
        end
      end

      def prune_empty_dirs(path, root)
        current = File.expand_path(path)
        while current != root && current.start_with?("#{root}#{File::SEPARATOR}") && Dir.exist?(current)
          break unless Dir.empty?(current)

          Dir.rmdir(current)
          current = File.dirname(current)
        end
      end

      def haxe_string(value)
        JSON.generate(value.to_s)
      end

      def haxe_method_name(ruby_name)
        ruby_name.to_s
          .sub(/[!?=]\z/, "")
          .gsub(/_([a-z0-9])/) { Regexp.last_match(1).upcase }
      end

      def haxe_identifier(value, fallback: "value")
        name = value.to_s.gsub(/[^A-Za-z0-9_]/, "_")
        name = fallback if name.empty?
        name = "_#{name}" unless name.match?(/\A[A-Za-z_]/)
        haxe_keywords.include?(name) ? "#{name}Value" : name
      end

      def haxe_keywords
        @haxe_keywords ||= %w[
          abstract break case cast catch class continue default do dynamic else enum
          extends extern false final for function if implements import in inline
          interface macro new null operator overload override package private public
          return static super switch this throw true try typedef untyped using var
          while
        ]
      end

      def file_name(value)
        value.to_s
          .gsub(/([a-z0-9])([A-Z])/, "\\1_\\2")
          .gsub(/[-\s]+/, "_")
          .downcase
      end

      def class_name_from_path(value)
        value.to_s.split(/[\/_:-]/).reject(&:empty?).map { |part| part[0].upcase + part[1..] }.join
      end

      def pluralize(value)
        value.to_s.end_with?("s") ? value.to_s : "#{value}s"
      end

      def package_path(package_name)
        package_name.to_s.tr(".", "/")
      end

      def safe_relative_path(value, label:)
        raw = value.to_s.strip
        if raw.include?("\\")
          raise Error, "#{label} must use forward-slash relative paths"
        end

        normalized = raw.sub(%r{/+\z}, "")
        if normalized.empty? || normalized.start_with?("/") || normalized.include?("//") || normalized.include?("..")
          raise Error, "#{label} must be a safe relative path"
        end

        segments = normalized.split("/")
        if segments.any? { |segment| segment.empty? || segment == "." || segment == ".." }
          raise Error, "#{label} must not contain empty, '.', or '..' segments"
        end

        normalized
      end

      def split_csv(value)
        value.to_s.split(",").map(&:strip).reject(&:empty?)
      end
    end

    class Error < StandardError; end
  end
end
