# frozen_string_literal: true

require "fileutils"
require "digest"
require "json"

module HXRuby
  module Generators
    module Common
      module_function

      GENERATED_HEADER = "# Generated by RailsHx."
      MANIFEST_VERSION = 1

      def write_file(path, content, force: false, executable: false, root: nil, kind: "file", source: nil, header: false)
        absolute_path = File.expand_path(path)
        absolute_root = root ? File.expand_path(root) : nil
        manifest = nil
        if absolute_root
          manifest = read_manifest(absolute_root)
          prepare_output_path!(absolute_path, absolute_root)
        else
          FileUtils.mkdir_p(File.dirname(absolute_path))
        end

        body = header ? with_generated_header(content) : content
        if File.exist?(absolute_path) && !force
          entry = manifest && manifest_entry(manifest, absolute_root, absolute_path)
          if entry && !manifest_checksum_matches?(entry, absolute_path)
            raise Error, "Refusing to overwrite modified RailsHx output #{absolute_path}. Re-run with --force to replace it, or remove its manifest entry and generated header to take Rails ownership."
          end
          unless generated_header?(absolute_path) || entry
            raise Error, "Refusing to overwrite non-RailsHx-owned file #{absolute_path}. Re-run with --force only if you intend to take ownership."
          end
        end

        write_without_following_symlinks(absolute_path, body, executable: executable)
        record_manifest_entry(absolute_root, absolute_path, body, kind: kind, source: source) if absolute_root
      end

      def with_generated_header(content)
        text = content.to_s
        return text if text.start_with?(GENERATED_HEADER)

        "#{GENERATED_HEADER}\n# Do not edit this file directly unless you intend to take RailsHx ownership.\n#{text}"
      end

      def owned_file?(path, root = nil)
        assert_canonical_inside_root!(path, root, reject_leaf_symlink: true) if root
        generated_header?(path) || manifest_owned?(root, path)
      end

      def generated_header?(path)
        return false unless File.file?(path)

        first_line = File.open(path, &:readline).strip
        first_line.start_with?(GENERATED_HEADER)
      rescue EOFError
        false
      end

      def manifest_path(root)
        File.join(root, ".railshx", "manifest.json")
      end

      # Reads the sole v1 ownership schema so every mutating caller fails before
      # it can guess how a missing, malformed, or future manifest should behave.
      def read_manifest(root)
        path = manifest_path(root)
        assert_canonical_inside_root!(path, root, reject_leaf_symlink: true) if File.exist?(root) || File.symlink?(root)
        return { "version" => MANIFEST_VERSION, "outputs" => [] } unless File.file?(path) || File.symlink?(path)

        parsed = JSON.parse(File.read(path))
        unless parsed.is_a?(Hash)
          raise Error, "Invalid RailsHx manifest #{path}: root must be an object"
        end
        unless parsed["version"] == MANIFEST_VERSION
          raise Error, "Unsupported RailsHx manifest version #{parsed["version"].inspect} in #{path}; this hxruby supports version #{MANIFEST_VERSION}"
        end

        outputs = parsed["outputs"]
        unless outputs.is_a?(Array)
          raise Error, "Invalid RailsHx manifest #{path}: outputs must be an array"
        end

        seen = {}
        outputs.each_with_index do |entry, index|
          unless entry.is_a?(Hash)
            raise Error, "Invalid RailsHx manifest #{path}: output entry #{index} must be an object"
          end

          output = entry["output"]
          unless output.is_a?(String)
            raise Error, "Invalid RailsHx manifest #{path}: output entry #{index} must contain a string output"
          end
          begin
            safe_relative_path(output, label: "manifest output")
          rescue Error => error
            raise Error, "Invalid RailsHx manifest #{path}: output entry #{index}: #{error.message}"
          end
          if seen[output]
            raise Error, "Invalid RailsHx manifest #{path}: duplicate output #{output.inspect}"
          end
          seen[output] = true

          sha256 = entry["sha256"]
          unless sha256.is_a?(String) && sha256.match?(/\A[0-9a-f]{64}\z/)
            raise Error, "Invalid RailsHx manifest #{path}: output entry #{index} must contain a lowercase SHA-256"
          end
        end

        { "version" => MANIFEST_VERSION, "outputs" => outputs }
      rescue JSON::ParserError => error
        raise Error, "Invalid RailsHx manifest #{path}: #{error.message}"
      end

      def manifest_owned?(root, path)
        return false unless root

        manifest_entry(read_manifest(root), root, path) != nil
      end

      def manifest_entry(manifest, root, path)
        relative = relative_path(root, path)
        manifest.fetch("outputs").find { |entry| entry.fetch("output") == relative }
      end

      # Checks the exact bytes RailsHx last wrote; a changed generated header is
      # still preserved until the user explicitly forces replacement.
      def manifest_checksum_matches?(entry, path)
        File.file?(path) && Digest::SHA256.file(path).hexdigest == entry.fetch("sha256")
      end

      def record_manifest_entry(root, path, content, kind:, source:)
        assert_canonical_inside_root!(path, root, reject_leaf_symlink: true)
        relative = relative_path(root, path)
        manifest = read_manifest(root)
        outputs = manifest.fetch("outputs").reject { |entry| entry["output"] == relative }
        outputs << {
          "output" => relative,
          "kind" => kind.to_s,
          "source" => source || "hxruby:generator",
          "sha256" => Digest::SHA256.hexdigest(content),
        }
        manifest["version"] = MANIFEST_VERSION
        manifest["outputs"] = outputs.sort_by { |entry| entry.fetch("output") }

        write_manifest(root, manifest)
      end

      def clean_owned_outputs(root)
        absolute_root = File.expand_path(root)
        manifest = read_manifest(absolute_root)
        owned_outputs = manifest.fetch("outputs").filter_map do |entry|
          output = entry["output"].to_s
          next if output.empty?

          path = File.expand_path(output, absolute_root)
          assert_inside_root!(path, absolute_root)
          assert_canonical_inside_root!(path, absolute_root, reject_leaf_symlink: true)
          [path, entry]
        end

        owned_outputs.each do |path, entry|
          next unless File.exist?(path)
          next if manifest_checksum_matches?(entry, path)

          raise Error, "Refusing to clean modified RailsHx output #{path}. Restore its recorded content, or remove its manifest entry and generated header to keep it under Rails ownership."
        end

        owned_outputs.each do |path, _entry|
          FileUtils.rm_f(path)
          prune_empty_dirs(File.dirname(path), absolute_root)
        end
        manifest["outputs"] = []
        write_manifest(absolute_root, manifest)
      end

      def relative_path(root, path)
        expanded_root = File.expand_path(root)
        expanded_path = File.expand_path(path)
        assert_inside_root!(expanded_path, expanded_root)
        expanded_path.delete_prefix("#{expanded_root}#{File::SEPARATOR}")
      end

      def assert_inside_root!(path, root)
        unless path == root || path.start_with?("#{root}#{File::SEPARATOR}")
          raise Error, "Generated path #{path} must stay inside #{root}"
        end
      end

      # Prepares a generator output without allowing an existing symlink or a
      # symlinked ancestor to redirect the write beyond the declared app root.
      def prepare_output_path!(path, root)
        expanded_path = File.expand_path(path)
        expanded_root = File.expand_path(root)
        assert_inside_root!(expanded_path, expanded_root)

        FileUtils.mkdir_p(expanded_root)
        assert_canonical_inside_root!(expanded_root, expanded_root)
        assert_canonical_inside_root!(File.dirname(expanded_path), expanded_root)
        FileUtils.mkdir_p(File.dirname(expanded_path))
        assert_canonical_inside_root!(File.dirname(expanded_path), expanded_root)
        assert_canonical_inside_root!(expanded_path, expanded_root, reject_leaf_symlink: true)
        expanded_path
      rescue SystemCallError => error
        raise Error, "Unsafe RailsHx generated path #{expanded_path}: #{error.message}"
      end

      # Canonicalizing the nearest existing ancestor also protects a new output
      # whose parent directory was replaced by a symlink.
      def assert_canonical_inside_root!(path, root, reject_leaf_symlink: false)
        expanded_path = File.expand_path(path)
        expanded_root = File.expand_path(root)
        assert_inside_root!(expanded_path, expanded_root)
        return expanded_path unless File.exist?(expanded_root) || File.symlink?(expanded_root)

        if reject_leaf_symlink && File.symlink?(expanded_path)
          raise Error, "RailsHx generated path #{expanded_path} must not be a symlink"
        end

        probe = expanded_path
        until File.exist?(probe) || File.symlink?(probe)
          parent = File.dirname(probe)
          break if parent == probe

          probe = parent
        end

        canonical_root = File.realpath(expanded_root)
        canonical_probe = File.realpath(probe)
        unless canonical_probe == canonical_root || canonical_probe.start_with?("#{canonical_root}#{File::SEPARATOR}")
          raise Error, "RailsHx generated path #{expanded_path} resolves outside #{expanded_root}"
        end

        expanded_path
      rescue Errno::EACCES, Errno::ELOOP, Errno::ENOENT => error
        raise Error, "Unsafe RailsHx generated path #{expanded_path}: #{error.message}"
      end

      def write_without_following_symlinks(path, content, executable: false)
        if File.symlink?(path)
          raise Error, "RailsHx generated path #{path} must not be a symlink"
        end

        flags = File::WRONLY | File::CREAT | File::TRUNC
        flags |= File::NOFOLLOW if File.const_defined?(:NOFOLLOW)
        File.open(path, flags, 0o666) do |file|
          file.write(content)
          file.chmod(0o755) if executable
        end
      rescue Errno::ELOOP => error
        raise Error, "RailsHx generated path #{path} must not be a symlink: #{error.message}"
      end

      def write_manifest(root, manifest)
        path = prepare_output_path!(manifest_path(root), root)
        write_without_following_symlinks(path, JSON.pretty_generate(manifest) + "\n")
      end

      def prune_empty_dirs(path, root)
        current = File.expand_path(path)
        while current != root && current.start_with?("#{root}#{File::SEPARATOR}") && Dir.exist?(current)
          break if File.symlink?(current)
          break unless Dir.empty?(current)

          Dir.rmdir(current)
          current = File.dirname(current)
        end
      end

      def haxe_string(value)
        JSON.generate(value.to_s)
      end

      def haxe_method_name(ruby_name)
        ruby_name.to_s
          .sub(/[!?=]\z/, "")
          .gsub(/_([a-z0-9])/) { Regexp.last_match(1).upcase }
      end

      def haxe_identifier(value, fallback: "value")
        name = value.to_s.gsub(/[^A-Za-z0-9_]/, "_")
        name = fallback if name.empty?
        name = "_#{name}" unless name.match?(/\A[A-Za-z_]/)
        haxe_keywords.include?(name) ? "#{name}Value" : name
      end

      def haxe_keywords
        @haxe_keywords ||= %w[
          abstract break case cast catch class continue default do dynamic else enum
          extends extern false final for function if implements import in inline
          interface macro new null operator overload override package private public
          return static super switch this throw true try typedef untyped using var
          while
        ]
      end

      def file_name(value)
        value.to_s
          .gsub(/([a-z0-9])([A-Z])/, "\\1_\\2")
          .gsub(/[-\s]+/, "_")
          .downcase
      end

      def class_name_from_path(value)
        value.to_s.split(/[\/_:-]/).reject(&:empty?).map { |part| part[0].upcase + part[1..] }.join
      end

      def pluralize(value)
        value.to_s.end_with?("s") ? value.to_s : "#{value}s"
      end

      def package_path(package_name)
        package_name.to_s.tr(".", "/")
      end

      def safe_relative_path(value, label:)
        raw = value.to_s.strip
        if raw.include?("\\")
          raise Error, "#{label} must use forward-slash relative paths"
        end

        normalized = raw.sub(%r{/+\z}, "")
        if normalized.empty? || normalized.start_with?("/") || normalized.include?("//") || normalized.include?("..")
          raise Error, "#{label} must be a safe relative path"
        end

        segments = normalized.split("/")
        if segments.any? { |segment| segment.empty? || segment == "." || segment == ".." }
          raise Error, "#{label} must not contain empty, '.', or '..' segments"
        end

        normalized
      end

      def split_csv(value)
        value.to_s.split(",").map(&:strip).reject(&:empty?)
      end
    end

    class Error < StandardError; end
  end
end
