# frozen_string_literal: true

require "optparse"
require_relative "common"

module HXRuby
  module Generators
    class Routes
      VERB_PATTERN = /\A(?:GET|POST|PATCH|PUT|DELETE|OPTIONS|HEAD)(?:\|(?:GET|POST|PATCH|PUT|DELETE|OPTIONS|HEAD))*\z/

      def self.run(argv, input: nil)
        new(parse(argv), input: input).run
      end

      def self.parse(argv)
        options = {
          input: nil,
          output: "src_haxe/routes/Routes.hx",
          package: "routes",
          class_name: "Routes",
          root: nil,
          force: false,
        }
        OptionParser.new do |parser|
          parser.on("--input PATH") { |value| options[:input] = value }
          parser.on("--output PATH") { |value| options[:output] = value }
          parser.on("--package NAME") { |value| options[:package] = value }
          parser.on("--class NAME") { |value| options[:class_name] = value }
          parser.on("--root PATH") { |value| options[:root] = value }
          parser.on("--force") { options[:force] = true }
        end.parse!(argv)
        options
      end

      def initialize(options, input: nil)
        @input = input
        @input_path = options.fetch(:input)
        @output_path = File.expand_path(options.fetch(:output))
        @output_root = File.expand_path(options.fetch(:root) || infer_output_root(@output_path))
        @package_name = options.fetch(:package)
        @class_name = options.fetch(:class_name)
        @force = options.fetch(:force)
      end

      def run
        input = @input || (@input_path ? File.read(File.expand_path(@input_path)) : $stdin.read)
        Common.write_file(@output_path, render_routes(parse_routes(input)), force: @force, root: @output_root, kind: "route_extern", source: "hxruby:routes")
      end

      private

      def infer_output_root(path)
        parts = File.expand_path(path).split(File::SEPARATOR)
        index = parts.index("src_haxe")
        return parts[0...index].join(File::SEPARATOR) unless index.nil?

        File.dirname(path)
      end

      def parse_routes(input)
        seen = {}
        helpers = []
        previous_prefix = nil

        input.each_line do |raw_line|
          route = parse_route_line(raw_line, previous_prefix)
          previous_prefix = route.fetch(:prefix) if route && !route.fetch(:prefix).to_s.empty?
          next unless route

          prefix = route.fetch(:prefix)
          uri = route.fetch(:uri)
          next if skip_prefix?(prefix)
          next if seen[prefix]

          seen[prefix] = true
          helpers << { prefix: prefix, params: route_params(uri) }
        end

        helpers
      end

      def parse_route_line(raw_line, previous_prefix)
        line = raw_line.strip
        return nil if line.empty? || line.start_with?("Prefix ")

        tokens = line.split(/\s+/)
        verb_index = tokens.index { |token| route_verb?(token) }
        return parse_mount_line(tokens) unless verb_index

        uri = tokens[verb_index + 1]
        return nil unless uri&.start_with?("/")

        raw_prefix = tokens[0...verb_index].join("_")
        prefix = raw_prefix.empty? ? previous_prefix : raw_prefix
        return nil if prefix.to_s.empty?

        { prefix: prefix, uri: uri }
      end

      def parse_mount_line(tokens)
        return nil unless tokens.length >= 2

        prefix = tokens[0]
        uri = tokens[1]
        return nil unless uri&.start_with?("/")

        { prefix: prefix, uri: uri }
      end

      def route_verb?(token)
        token.match?(VERB_PATTERN)
      end

      def skip_prefix?(prefix)
        prefix.nil? || prefix.empty? || prefix.start_with?("rails_")
      end

      def route_params(uri)
        required_path = uri
          .gsub(/\(\.:format\)/, "")
          .gsub(/\([^)]*\)/, "")

        params = required_path.scan(/:([A-Za-z_][A-Za-z0-9_]*)/).flatten
        params += required_path.scan(/\*([A-Za-z_][A-Za-z0-9_]*)/).flatten
        params.uniq
      end

      def render_routes(helpers)
        lines = [
          "package #{@package_name};",
          "",
          "import rails.routing.RouteParam;",
          "",
          "// Generated by HXRuby::Generators::Routes from Rails route output.",
          "//",
          "// Demonstrates: Rails-owned routes converted into typed Haxe extern methods.",
          "// Type safety: Haxe callers use named route helpers instead of hand-written",
          "// path strings; helper arity and required route params are checked at compile time.",
          "// IntelliSense: editors should complete named route helpers from this extern.",
          "// Ruby/Rails output: direct calls to Rails route helpers such as `todos_path`.",
          '@:native("self")',
          "extern class #{@class_name} {",
        ]

        helpers.each do |helper|
          append_helper(lines, "#{helper.fetch(:prefix)}_path", helper.fetch(:params))
          append_helper(lines, "#{helper.fetch(:prefix)}_url", helper.fetch(:params))
        end

        lines << "\t// No named Rails routes found." if helpers.empty?
        lines << "}"
        lines << ""
        lines.join("\n")
      end

      def append_helper(lines, ruby_name, params)
        lines << "\t@:native(\"#{ruby_name}\")"
        lines << "\tpublic static function #{Common.haxe_method_name(ruby_name)}(#{params.map { |param| param_arg(param) }.join(", ")}):String;"
        lines << ""
      end

      def param_arg(name)
        "#{Common.haxe_method_name(name)}:RouteParam"
      end
    end
  end
end
