# frozen_string_literal: true

require "optparse"
require_relative "common"

module HXRuby
  module Generators
    class Routes
      VERBS = %w[GET POST PATCH PUT DELETE OPTIONS HEAD].freeze

      def self.run(argv, input: nil)
        new(parse(argv), input: input).run
      end

      def self.parse(argv)
        options = {
          input: nil,
          output: "src_haxe/routes/Routes.hx",
          package: "routes",
          class_name: "Routes",
        }
        OptionParser.new do |parser|
          parser.on("--input PATH") { |value| options[:input] = value }
          parser.on("--output PATH") { |value| options[:output] = value }
          parser.on("--package NAME") { |value| options[:package] = value }
          parser.on("--class NAME") { |value| options[:class_name] = value }
        end.parse!(argv)
        options
      end

      def initialize(options, input: nil)
        @input = input
        @input_path = options.fetch(:input)
        @output_path = File.expand_path(options.fetch(:output))
        @package_name = options.fetch(:package)
        @class_name = options.fetch(:class_name)
      end

      def run
        input = @input || (@input_path ? File.read(File.expand_path(@input_path)) : $stdin.read)
        Common.write_file(@output_path, render_routes(parse_routes(input)), force: true)
      end

      private

      def parse_routes(input)
        seen = {}
        helpers = []

        input.each_line do |raw_line|
          line = raw_line.strip
          next if line.empty? || line.start_with?("Prefix ", "rails_")

          tokens = line.split(/\s+/)
          prefix = nil
          verb = nil
          uri = nil

          if VERBS.include?(tokens[0])
            verb = tokens[0]
            uri = tokens[1]
          elsif VERBS.include?(tokens[1])
            prefix = tokens[0]
            verb = tokens[1]
            uri = tokens[2]
          end

          next unless prefix && verb && uri
          next if seen[prefix]

          seen[prefix] = true
          helpers << { prefix: prefix, params: route_params(uri) }
        end

        helpers
      end

      def route_params(uri)
        cleaned = uri.gsub(/\(\.:format\)/, "")
        cleaned.scan(/:([A-Za-z_][A-Za-z0-9_]*)/).flatten.uniq
      end

      def render_routes(helpers)
        lines = [
          "package #{@package_name};",
          "",
          "// Generated by HXRuby::Generators::Routes from Rails route output.",
          '@:native("self")',
          "extern class #{@class_name} {",
        ]

        helpers.each do |helper|
          append_helper(lines, "#{helper.fetch(:prefix)}_path", helper.fetch(:params))
          append_helper(lines, "#{helper.fetch(:prefix)}_url", helper.fetch(:params))
        end

        lines << "\t// No named Rails routes found." if helpers.empty?
        lines << "}"
        lines << ""
        lines.join("\n")
      end

      def append_helper(lines, ruby_name, params)
        lines << "\t@:native(\"#{ruby_name}\")"
        lines << "\tpublic static function #{Common.haxe_method_name(ruby_name)}(#{params.map { |param| param_arg(param) }.join(", ")}):String;"
        lines << ""
      end

      def param_arg(name)
        "#{Common.haxe_method_name(name)}:Dynamic"
      end
    end
  end
end
