# frozen_string_literal: true

require "optparse"
require_relative "common"

module HXRuby
  module Generators
    class Template
      PACKAGE_PATTERN = /\A[A-Za-z_][A-Za-z0-9_]*(?:[.][A-Za-z_][A-Za-z0-9_]*)*\z/
      TEMPLATE_PATTERN = /\A[A-Za-z0-9_\/]+\z/
      LOCAL_PATTERN = /\A[A-Za-z_][A-Za-z0-9_]*:[A-Za-z_][A-Za-z0-9_.<>?, ]*\z/

      def self.run(argv)
        new(parse(argv)).run
      end

      def self.parse(argv)
        options = {
          path: nil,
          output: ".",
          haxe_dir: "src_haxe/views",
          package: "views",
          locals: "",
          force: false,
        }
        parser = OptionParser.new do |opts|
          opts.banner = "Usage: hxruby:template PATH [options]"
          opts.on("--output PATH") { |value| options[:output] = value }
          opts.on("--haxe-dir PATH") { |value| options[:haxe_dir] = value }
          opts.on("--package NAME") { |value| options[:package] = value }
          opts.on("--locals FIELDS", "Comma-separated typed locals, e.g. title:String,count:Int") { |value| options[:locals] = value }
          opts.on("--force") { options[:force] = true }
        end
        remaining = parser.parse!(argv)
        options[:path] = remaining.shift
        raise Error, "Missing required template PATH" if options[:path].to_s.empty?

        options
      end

      def initialize(options)
        @template_path = Common.safe_relative_path(options.fetch(:path), label: "template PATH")
        @output_dir = File.expand_path(options.fetch(:output))
        @haxe_dir = Common.safe_relative_path(options.fetch(:haxe_dir), label: "--haxe-dir")
        @package_name = options.fetch(:package)
        @locals = parse_locals(options.fetch(:locals))
        @force = options.fetch(:force)
        validate_static_options!
      end

      def run
        write(File.join(@haxe_dir, view_dir, "#{view_class}.hx"), render_view, kind: "haxe_view_source")
      end

      private

      def validate_static_options!
        raise Error, "Template path must use safe Rails path characters and no file extension" unless @template_path.match?(TEMPLATE_PATTERN)
        raise Error, "--package must be a safe Haxe package" unless @package_name.match?(PACKAGE_PATTERN)
      end

      def parse_locals(raw)
        Common.split_csv(raw).map do |entry|
          unless entry.match?(LOCAL_PATTERN)
            raise Error, "--locals entries must look like name:Type using safe Haxe identifiers"
          end
          name, type = entry.split(":", 2)
          { name: Common.haxe_identifier(name, fallback: "value"), type: type.strip }
        end
      end

      def write(relative_path, content, kind:)
        Common.write_file(
          File.join(@output_dir, relative_path),
          content,
          force: @force,
          root: @output_dir,
          kind: kind,
          source: "hxruby:template"
        )
      end

      def render_view
        [
          "package #{view_package};",
          "",
          "import rails.action_view.HtmlNode;",
          "",
          "typedef #{locals_type} = {",
          *locals_fields,
          "}",
          "",
          "// Generated by HXRuby::Generators::Template.",
          "// Demonstrates: typed Rails HHX as the source of truth for an",
          "// ActionView template or partial. The compiler emits ordinary Rails ERB",
          "// at app/views/#{@template_path}.html.erb; do not author raw ERB here.",
          "//",
          "// Type safety: callers can use `(Template.of(#{view_class}) :",
          "// Template<#{locals_type}>)`, so missing/renamed view classes and wrong",
          "// locals are caught by Haxe before Rails renders the template.",
          "//",
          "// `@:railsTemplate` records the Rails template path. The string is kept",
          "// literal and path-checked by the generator/compiler so it cannot drift",
          "// into an unsafe file write.",
          "@:railsTemplate(#{Common.haxe_string(@template_path)})",
          "// `@:railsTemplateAst(\"render\")` tells RailsHx to parse the inline HHX",
          "// returned by render(...) and lower it to Rails-native ERB output.",
          "@:railsTemplateAst(\"render\")",
          "class #{view_class} {",
          "\tpublic static function render(locals:#{locals_type}):HtmlNode {",
          *render_body,
          "\t}",
          "}",
          "",
        ].join("\n")
      end

      def locals_fields
        return ["\t// Add typed locals here, for example: var title:String;"] if @locals.empty?

        @locals.map { |local| "\tvar #{local.fetch(:name)}:#{local.fetch(:type)};" }
      end

      def render_body
        title_line = if @locals.any? { |local| local.fetch(:name) == "title" }
                       "\t\t\t<h1>${locals.title}</h1>"
                     else
                       "\t\t\t<h1>#{human_title}</h1>"
                     end
        root_tag = partial? ? "article" : "main"
        css_class = partial? ? "railshx-generated-partial" : "railshx-generated-view"

        [
          "\t\treturn <#{root_tag} class=\"#{css_class}\">",
          title_line,
          "\t\t\t<p>This template is authored in typed Rails HHX and emitted as Rails ERB.</p>",
          "\t\t</#{root_tag}>;",
        ]
      end

      def view_segments
        @template_path.split("/")
      end

      def view_dir
        view_segments[0...-1].join("/")
      end

      def view_package
        dirs = view_segments[0...-1].map { |segment| Common.haxe_identifier(segment, fallback: "views") }
        ([ @package_name ] + dirs).join(".")
      end

      def view_class
        "#{Common.class_name_from_path(view_basename.sub(/\A_+/, ""))}View"
      end

      def locals_type
        "#{Common.class_name_from_path(view_basename.sub(/\A_+/, ""))}Locals"
      end

      def view_basename
        view_segments.fetch(-1)
      end

      def partial?
        view_basename.start_with?("_")
      end

      def human_title
        view_basename.sub(/\A_+/, "").tr("_", " ").split.map(&:capitalize).join(" ")
      end
    end
  end
end
