# frozen_string_literal: true

require "optparse"
require_relative "common"

module HXRuby
  module Generators
    class Test
      PACKAGE_PATTERN = /\A[A-Za-z_][A-Za-z0-9_]*(?:[.][A-Za-z_][A-Za-z0-9_]*)*\z/
      TEST_PATH_PATTERN = /\A[A-Za-z0-9_\/]+\z/

      def self.run(argv)
        new(parse(argv)).run
      end

      def self.parse(argv)
        options = {
          name: nil,
          type: nil,
          output: ".",
          haxe_dir: "test_haxe",
          package: "test_haxe",
          description: nil,
          force: false,
        }
        parser = OptionParser.new do |opts|
          opts.banner = "Usage: hxruby:test NAME [options]"
          opts.on("--type TYPE", "model or request") { |value| options[:type] = value }
          opts.on("--output PATH") { |value| options[:output] = value }
          opts.on("--haxe-dir PATH") { |value| options[:haxe_dir] = value }
          opts.on("--package NAME") { |value| options[:package] = value }
          opts.on("--description TEXT") { |value| options[:description] = value }
          opts.on("--force") { options[:force] = true }
        end
        remaining = parser.parse!(argv)
        options[:name] = remaining.shift
        raise Error, "Missing required test NAME" if options[:name].to_s.empty?

        options
      end

      def initialize(options)
        @test_name = Common.safe_relative_path(options.fetch(:name), label: "test NAME")
        @test_type = normalize_type(options.fetch(:type))
        @output_dir = File.expand_path(options.fetch(:output))
        @haxe_dir = Common.safe_relative_path(options.fetch(:haxe_dir), label: "--haxe-dir")
        @package_name = options.fetch(:package)
        @description = options.fetch(:description) || default_description
        @force = options.fetch(:force)
        validate_static_options!
      end

      def run
        write(File.join(@haxe_dir, test_dir, "#{test_class}.hx"), render_test, kind: "haxe_test_source")
      end

      private

      def validate_static_options!
        raise Error, "Test name must use safe Rails path characters and no file extension" unless @test_name.match?(TEST_PATH_PATTERN)
        raise Error, "--package must be a safe Haxe package" unless @package_name.match?(PACKAGE_PATTERN)
        raise Error, "--description must not be empty" if @description.to_s.strip.empty?
      end

      def normalize_type(value)
        inferred = value || (@test_name.start_with?("controllers/") || @test_name.start_with?("requests/") ? "request" : "model")
        return inferred if %w[model request].include?(inferred)

        raise Error, "--type must be model or request"
      end

      def write(relative_path, content, kind:)
        Common.write_file(
          File.join(@output_dir, relative_path),
          content,
          force: @force,
          root: @output_dir,
          kind: kind,
          source: "hxruby:test"
        )
      end

      def render_test
        imports = [
          "import rails.test.Assert.*;",
          "import rails.test.Dsl.*;",
          "import rails.test.#{base_class};",
        ]
        imports << "import rails.test.Request.*;" if request?

        [
          "package #{test_package};",
          "",
          *imports.sort,
          "",
          "// Generated by HXRuby::Generators::Test.",
          "// Demonstrates: a Haxe-authored Rails/Minitest source file.",
          "// The compiler consumes @:railsTest and emits an ordinary Rails test",
          "// under test/generated/#{rails_test_path}.rb for `bin/rails test`.",
          "//",
          "// `@:railsTests static function define()` is a compiler-erased",
          "// declaration host: top-level `test(...)` calls become idiomatic Rails",
          "// `test \"...\" do` blocks without redundant Haxe method names.",
          "@:railsTest(#{Common.haxe_string(rails_test_path)})",
          "class #{test_class} extends #{base_class} {",
          "\t@:railsTests",
          "\tstatic function define():Void {",
          "\t\ttest(#{Common.haxe_string(@description)}, () -> {",
          *test_body,
          "\t\t});",
          "\t}",
          "}",
          "",
        ].join("\n")
      end

      def test_body
        if request?
          [
            "\t\t\t// Replace this route with a generated Routes.*Path() helper when",
            "\t\t\t// the app route externs are available.",
            "\t\t\tget(\"/\");",
            "\t\t\tassertResponse(rails.action_controller.Status.ok);",
          ]
        else
          [
            "\t\t\ttruthy(true);",
          ]
        end
      end

      def rails_test_path
        normalized = @test_name.sub(/\.rb\z/, "")
        normalized.end_with?("_test") ? normalized : "#{normalized}_haxe_test"
      end

      def test_segments
        rails_test_path.split("/")
      end

      def test_dir
        test_segments[0...-1].join("/")
      end

      def test_package
        dirs = test_segments[0...-1].map { |segment| Common.haxe_identifier(segment, fallback: "tests") }
        ([ @package_name ] + dirs).join(".")
      end

      def test_class
        basename = test_segments.fetch(-1).sub(/_test\z/, "").sub(/_haxe\z/, "")
        "#{Common.class_name_from_path(basename)}HaxeTest"
      end

      def base_class
        request? ? "RequestTestCase" : "ModelTestCase"
      end

      def request?
        @test_type == "request"
      end

      def default_description
        "#{test_segments.fetch(-1).sub(/_test\z/, "").tr("_", " ")} works"
      end
    end
  end
end
