# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "hxruby/core"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.__hx_fields()
    {instance: [], static: ["main"]}
  end
  def self.main()
    original = Dir.pwd()
    puts(HXRuby.stringify((original.length > 0)))
    puts(HXRuby.stringify((Dir.home().length > 0)))
    puts(HXRuby.stringify(Dir.exist?("std")))
    puts(HXRuby.stringify(Dir.exist?("missing-ruby-dir-facade-path")))
    puts(HXRuby.stringify(Dir.empty?("std/ruby")))
    puts(HXRuby.stringify((HXRuby.array_index_of(Dir.entries("std"), ".", nil) >= 0)))
    puts(HXRuby.stringify((HXRuby.array_index_of(Dir.children("std"), "ruby", nil) >= 0)))
    puts(HXRuby.stringify((Dir.glob("std/ruby/*.hx", 0).length > 0)))
    puts(HXRuby.stringify(Dir.chdir("std")))
    puts(HXRuby.stringify((Dir.pwd() == (original + "/std"))))
    puts(HXRuby.stringify(Dir.chdir(original)))
    puts(HXRuby.stringify((Dir.pwd() == original)))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  Main.main()
end
