# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    controller__hx17015 = nil
    puts(HXRuby.stringify((controller__hx17015 == nil)))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
