# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.main()
    controller = nil
    puts(HXRuby.stringify((controller == nil)))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
