# Generated by reflaxe.ruby
# Grouped ActiveRecord results require the typed Haxe map ABI.
require Rails.root.join("app/lib/railshx/runtime/hxruby/core.rb")
require Rails.root.join("app/lib/railshx/runtime/hxruby/maps.rb")
