# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    card__hx0 = Views::ComponentCardView
    shell__hx0 = Views::ComponentShellView
    puts(HXRuby.stringify(((card__hx0 != nil) && (shell__hx0 != nil))))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
