# Generated by reflaxe.ruby
$LOAD_PATH.unshift(__dir__)
require "active_record"
require_relative "app/haxe_gen/hxruby/core"
require_relative "app/haxe_gen/hxruby/data_define"
require_relative "app/haxe_gen/main"
require_relative "app/haxe_gen/models/todo"
Main.main
