# Generated by reflaxe.ruby
# Rails model output; Zeitwerk path should match the Ruby constant.
require "active_record"
require "active_storage/engine"
module Models
  class Profile < ::ApplicationRecord
    self.table_name = "profiles"
    def self.__hx_rails_schema()
      {
        table_name: "profiles",
        timestamps: false,
        columns: [
          {name: :id, haxe_name: "id", ruby_name: "id", haxe_type: "Int", rails_type: :bigint, nullable: false, default: nil, primary_key: true, index: false, unique: false, db_type: :bigint},
          {name: :name, haxe_name: "name", ruby_name: "name", haxe_type: "String", rails_type: :string, nullable: false, default: nil, primary_key: false, index: false, unique: false, db_type: nil}
        ]
      }
    end
    def self.typed_column_count()
      __hx_rails_schema()[:columns].length
    end
    has_one_attached :avatar
    has_many_attached :gallery
    # haxe column id: Int
    # haxe column name: String
    def initialize(*args, **kwargs)
      args = args + [kwargs] unless kwargs.empty?
      super(*args)
    end
  end
end
