# Generated by reflaxe.ruby
# Rails model output; Zeitwerk path should match the Ruby constant.
require "active_record"
require "cgi"
require "uri"
class ChatMessage < ApplicationRecord
  self.table_name = "chat_messages"
  belongs_to :user, optional: false, foreign_key: "user_id", inverse_of: :chat_messages
  # haxe column id: Int
  # haxe column body: String
  # haxe column user_id: Int
  validates :body, presence: true
  before_validation :normalize_body
  def initialize(*args, **kwargs)
    args = args + [kwargs] unless kwargs.empty?
    super(*args)
  end
  def normalize_body()
    if (self.body != nil)
      self.body = self.body.strip()
    end
  end
  def self.latest()
    return ChatMessage.includes(:user).order(id: :desc).limit(6)
  end
end
