# Generated by reflaxe.ruby
# Rails model output; Zeitwerk path should match the Ruby constant.
require "active_record"
require_relative "../lib/railshx/runtime/hxruby/core"
class User < ApplicationRecord
  self.table_name = "users"
  devise :database_authenticatable, :validatable
  has_many :todos, dependent: :destroy, inverse_of: :user
  has_many :chat_messages, dependent: :destroy, inverse_of: :user
  # haxe column id: Int
  # haxe column name: String
  # haxe column email: String
  # haxe column encrypted_password: String
  # haxe column role: String
  validates :name, presence: true, length: {minimum: 2}
  validates :name, exclusion: {within: ["admin", "root", "system"]}
  validates :email, presence: true, uniqueness: true, format: {with: /\A[^@]+@[^@]+\z/}
  validates :role, inclusion: {within: ["member", "admin", "maintainer", "guest"]}
  def initialize(*args, **kwargs)
    args = args + [kwargs] unless kwargs.empty?
    super(*args)
  end
  def role_label()
    return ((self.role == "admin") ? "Admin" : ((self.role == "maintainer") ? "Maintainer" : ((self.role == "guest") ? "Guest" : "Member")))
  end
  def can_manage_users()
    return (self.role == "admin")
  end
  def initials()
    trimmed = self.name.strip()
    return ((trimmed == "") ? "?" : HXRuby.string_substr(trimmed, 0, 1).upcase())
  end
end
