# Generated by reflaxe.ruby
# Rails model output; Zeitwerk path should match the Ruby constant.
require "active_record"
class User < ApplicationRecord
  self.table_name = "users"
  devise :database_authenticatable, :validatable
  has_many :todos, dependent: :destroy, inverse_of: :user
  has_many :chat_messages, dependent: :destroy, inverse_of: :user
  # haxe column id: Int
  # haxe column name: String
  # haxe column email: String
  # haxe column encrypted_password: String
  # haxe column role: String
  validates :name, presence: true, length: {minimum: 2}
  validates :name, exclusion: {within: ["admin", "root", "system"]}
  validates :email, presence: true, uniqueness: true, format: {with: /\A[^@]+@[^@]+\z/}
  validates :role, inclusion: {within: ["member", "admin", "maintainer", "guest"]}
  def initialize(*args, **kwargs)
    args = args + [kwargs] unless kwargs.empty?
    super(*args)
  end
  def role_label()
    return (if (self.role == "admin") then "Admin" else (if (self.role == "maintainer") then "Maintainer" else (if (self.role == "guest") then "Guest" else "Member" end) end) end)
  end
  def can_manage_users()
    return (self.role == "admin")
  end
  def initials()
    trimmed = self.name.strip()
    return (if (trimmed == "") then "?" else trimmed[0, 1].upcase() end)
  end
end
