# Generated by reflaxe.ruby
# Rails ActionCable channel output; Zeitwerk path should match the Ruby constant.
require "action_cable/engine"
class TodosChannel < ActionCable::Channel::Base
  def subscribed()
    user = current_user
    list_id = params["list_id"]
    if (list_id == "reject")
      self.reject()
      return
    end
    self.stream_from(("todos:" + list_id))
  end
  def unsubscribed()
    self.stop_all_streams()
  end
  def ping()
    self.transmit({"title" => "pong", "completed" => false})
  end
  def self.announce(list_id, title)
    ActionCable.server.broadcast(("todos:" + list_id), {"title" => title, "completed" => false})
  end
end
