package routes;

// Generated by HXRuby::Generators::Routes from Rails route output.
@:native("self")
extern class Routes {
	@:native("todos_path")
	public static function todosPath():String;

	@:native("todos_url")
	public static function todosUrl():String;

	@:native("todo_path")
	public static function todoPath(id:Dynamic):String;

	@:native("todo_url")
	public static function todoUrl(id:Dynamic):String;

	@:native("user_path")
	public static function userPath(id:Dynamic):String;

	@:native("user_url")
	public static function userUrl(id:Dynamic):String;

}
