package routes;

import rails.routing.RouteParam;

// Generated by HXRuby::Generators::Routes from Rails route output.
//
// Demonstrates: Rails-owned routes converted into typed Haxe extern methods.
// Type safety: Haxe callers use named route helpers instead of hand-written
// path strings; helper arity and required route params are checked at compile time.
// IntelliSense: editors should complete named route helpers from this extern.
// Ruby/Rails output: direct calls to Rails route helpers such as `todos_path`.
@:native("self")
extern class Routes {
	@:native("todos_path")
	public static function todosPath():String;

	@:native("todos_url")
	public static function todosUrl():String;

	@:native("todo_path")
	public static function todoPath(id:RouteParam):String;

	@:native("todo_url")
	public static function todoUrl(id:RouteParam):String;

	@:native("user_path")
	public static function userPath(id:RouteParam):String;

	@:native("user_url")
	public static function userUrl(id:RouteParam):String;

}
