# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.main()
    todo__hx16590 = nil
    puts(HXRuby.stringify((todo__hx16590 == nil)))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
