# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "hxruby/core"
class KeywordShapes
  def self.__hx_name()
    "KeywordShapes"
  end
  def self.__hx_fields()
    {instance: ["describeInstance"], static: ["assignValue", "assigned", "assignedValue", "describe", "mutate", "passthrough", "ready", "saveBang", "transform"]}
  end
  class << self
    attr_accessor :assigned_value
  end
  @assigned_value = 0
  def initialize()
    nil
  end
  def describe_instance(required_label:, retry_count:, **optional_keywords)
    # Preserve optional keyword presence separately from explicit nil and reject undeclared keys.
    unknown_keywords = (optional_keywords.keys() - [:active, :note_text])
    if (!unknown_keywords.empty?())
      raise(ArgumentError, ("unknown keyword(s) for describe_instance: " + unknown_keywords.inspect()))
    end
    return KeywordShapes.describe("instance", required_label: required_label, retry_count: retry_count, **(optional_keywords.key?(:active) ? {active: optional_keywords[:active]} : {}), **(optional_keywords.key?(:note_text) ? {note_text: optional_keywords[:note_text]} : {}))
  end
  def self.describe(prefix, required_label:, retry_count:, **optional_keywords)
    # Preserve optional keyword presence separately from explicit nil and reject undeclared keys.
    unknown_keywords = (optional_keywords.keys() - [:active, :note_text])
    if (!unknown_keywords.empty?())
      raise(ArgumentError, ("unknown keyword(s) for self.describe: " + unknown_keywords.inspect()))
    end
    note = (optional_keywords.key?(:note_text) ? HXRuby.stringify(optional_keywords[:note_text]) : "missing")
    active = (optional_keywords.key?(:active) ? HXRuby.stringify(optional_keywords[:active]) : "missing")
    return ((((((((prefix + ":") + required_label) + ":") + HXRuby.stringify(retry_count)) + ":") + note) + ":") + active)
  end
  def self.passthrough(required_label:, retry_count:, **optional_keywords)
    # Preserve optional keyword presence separately from explicit nil and reject undeclared keys.
    unknown_keywords = (optional_keywords.keys() - [:active, :note_text])
    if (!unknown_keywords.empty?())
      raise(ArgumentError, ("unknown keyword(s) for self.passthrough: " + unknown_keywords.inspect()))
    end
    # Rebuild the typed Haxe keyword carrier because this method uses it as a value.
    options = {"requiredLabel" => required_label, "retries" => retry_count}
    if optional_keywords.key?(:active)
      options["active"] = optional_keywords[:active]
    end
    if optional_keywords.key?(:note_text)
      options["note"] = optional_keywords[:note_text]
    end
    return options
  end
  def self.mutate(required_label:, retry_count:, **optional_keywords)
    # Preserve optional keyword presence separately from explicit nil and reject undeclared keys.
    unknown_keywords = (optional_keywords.keys() - [:active, :note_text])
    if (!unknown_keywords.empty?())
      raise(ArgumentError, ("unknown keyword(s) for self.mutate: " + unknown_keywords.inspect()))
    end
    # Rebuild the typed Haxe keyword carrier because this method uses it as a value.
    options = {"requiredLabel" => required_label, "retries" => retry_count}
    if optional_keywords.key?(:active)
      options["active"] = optional_keywords[:active]
    end
    if optional_keywords.key?(:note_text)
      options["note"] = optional_keywords[:note_text]
    end
    options["requiredLabel"] = (options["requiredLabel"] + "!")
    return options["requiredLabel"]
  end
  def self.transform(required_label:, retry_count:, **optional_keywords)
    # Preserve optional keyword presence separately from explicit nil and reject undeclared keys.
    unknown_keywords = (optional_keywords.keys() - [:active, :note_text])
    if (!unknown_keywords.empty?())
      raise(ArgumentError, ("unknown keyword(s) for self.transform: " + unknown_keywords.inspect()))
    end
    return yield(required_label)
  end
  def self.ready?()
    return true
  end
  def self.save!(value)
    return ("saved:" + value)
  end
  def self.value=(value)
    KeywordShapes.assigned_value = value
  end
  def self.assigned()
    return KeywordShapes.assigned_value
  end
end
