# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "hxruby/core"
class KeywordConstructed
  def self.__hx_name()
    "KeywordConstructed"
  end
  def self.__hx_fields()
    {instance: ["rendered"], static: []}
  end
  attr_accessor :rendered
  def initialize(required_label:, retry_count:, **optional_keywords)
    # Preserve optional keyword presence separately from explicit nil and reject undeclared keys.
    unknown_keywords = (optional_keywords.keys() - [:active, :note_text])
    if (!unknown_keywords.empty?())
      raise(ArgumentError, ("unknown keyword(s) for initialize: " + unknown_keywords.inspect()))
    end
    self.rendered = ((required_label + ":") + HXRuby.stringify(retry_count))
  end
end
