# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "hxruby/core"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.__hx_fields()
    {instance: [], static: ["factoryCalls", "main", "makeOptions"]}
  end
  class << self
    attr_accessor :factory_calls
  end
  @factory_calls = 0
  def self.main()
    puts(HXRuby.stringify(KeywordShapes.describe("inline", required_label: "ruby", retry_count: 1)))
    puts(HXRuby.stringify(KeywordShapes.describe("inline-null", required_label: "ruby", retry_count: 2, note_text: nil)))
    stored = {"requiredLabel" => "stored", "retries" => 3, "active" => true}
    puts(HXRuby.stringify(KeywordShapes.describe("stored", required_label: stored["requiredLabel"], retry_count: stored["retries"], **(stored.key?("active") ? {active: stored["active"]} : {}), **(stored.key?("note") ? {note_text: stored["note"]} : {}))))
    puts(HXRuby.stringify(KeywordShapes.new().describe_instance(required_label: stored["requiredLabel"], retry_count: stored["retries"], **(stored.key?("active") ? {active: stored["active"]} : {}), **(stored.key?("note") ? {note_text: stored["note"]} : {}))))
    wider = {"requiredLabel" => "narrowed", "retries" => 4, "extra" => "not-a-keyword"}
    narrowed = wider
    puts(HXRuby.stringify(KeywordShapes.describe("narrowed", required_label: narrowed["requiredLabel"], retry_count: narrowed["retries"], **(narrowed.key?("active") ? {active: narrowed["active"]} : {}), **(narrowed.key?("note") ? {note_text: narrowed["note"]} : {}))))
    puts(HXRuby.stringify(KeywordShapes.describe("factory", **begin
      # Evaluate the typed keyword carrier once and preserve optional-key presence.
      keyword_options = Main.make_options()
      projected_keywords = {required_label: keyword_options["requiredLabel"], retry_count: keyword_options["retries"]}
      if keyword_options.key?("active")
        projected_keywords[:active] = keyword_options["active"]
      end
      if keyword_options.key?("note")
        projected_keywords[:note_text] = keyword_options["note"]
      end
      projected_keywords
    end)))
    puts(HXRuby.stringify(("factory-calls:" + HXRuby.stringify(Main.factory_calls))))
    explicit_null = KeywordShapes.passthrough(required_label: "echo", retry_count: 6, note_text: nil)
    absent = KeywordShapes.passthrough(required_label: "echo", retry_count: 7)
    puts(HXRuby.stringify(((("echo-null:" + HXRuby.stringify(HXRuby.reflect_has_field(explicit_null, "note"))) + ":") + HXRuby.stringify(HXRuby.reflect_field(explicit_null, "note")))))
    puts(HXRuby.stringify(("echo-absent:" + HXRuby.stringify(HXRuby.reflect_has_field(absent, "note")))))
    puts(HXRuby.stringify(KeywordShapes.mutate(required_label: "mutated", retry_count: 8)))
    puts(HXRuby.stringify(KeywordShapes.transform(required_label: "block", retry_count: 8) { |value| value.upcase() }))
    puts(HXRuby.stringify(KeywordConstructed.new(required_label: "ctor", retry_count: 9).rendered))
    puts(HXRuby.stringify(("predicate:" + HXRuby.stringify(KeywordShapes.ready?()))))
    puts(HXRuby.stringify(KeywordShapes.save!("record")))
    KeywordShapes.value = 10
    puts(HXRuby.stringify(("assigned:" + HXRuby.stringify(KeywordShapes.assigned()))))
    puts(HXRuby.stringify(RestShapes.join("inline", 1, 2)))
    stored__hx1 = [3, 4]
    puts(HXRuby.stringify(RestShapes.join("stored", *stored__hx1)))
    puts(HXRuby.stringify(RestShapes.forward("forward", 5, 6)))
    puts(HXRuby.stringify(RestShapes.new(7, 8).values.join(",")))
    puts(HXRuby.stringify(RestShapes.new().join_instance("instance-rest", 9, 10)))
  end
  def self.make_options()
    Main.factory_calls = (Main.factory_calls + 1)
    return {"requiredLabel" => "made", "retries" => 5, "note" => "once"}
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  Main.main()
end
