# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class RestShapes
  def self.__hx_name()
    "RestShapes"
  end
  def self.__hx_fields()
    {instance: ["joinInstance", "values"], static: ["forward", "join"]}
  end
  attr_accessor :values
  def initialize(*values)
    self.values = values.dup()
  end
  def join_instance(prefix, *values)
    return ((prefix + ":") + values.dup().join(","))
  end
  def self.join(prefix, *values)
    return ((prefix + ":") + values.dup().join(","))
  end
  def self.forward(prefix, *values)
    return RestShapes.join(prefix, *values)
  end
end
