# Generated by reflaxe.ruby
# Rails controller output; Zeitwerk path should match the Ruby constant.
require "action_controller/railtie"
module Controllers
  class TodosController < ActionController::Base
    def initialize()
      super()
    end
    def create()
      attrs__hx0 = self.params().require("todo").permit([:title, :is_completed])
      request_method__hx0 = self.request().request_method()
      request_path__hx0 = self.request().path()
      current_status__hx0 = self.response().status()
      self.flash()[:notice] = "Todo queued"
      self.session()[:last_todo_title] = attrs__hx0
      remembered__hx0 = self.session()[:last_todo_title]
      self.cookies()[:todo_filter] = "open"
      self.cookies().delete(:stale_filter)
      self.render(json: attrs__hx0, status: :created)
      self.redirect_to(action: "index")
      self.head(:no_content)
    end
  end
end
