// Generated by examples/todoapp_rails/src/tools/ExportTodoHooks.hx.
// Do not edit by hand; change shared/TodoHooks.hx and rerun npm run test:todoapp-rails.
export const hooks = {
  attrs: {
    bound: "data-railshx-bound",
    scroll: "data-railshx-scroll",
    flash: "data-railshx-flash",
    session: "data-railshx-session",
    sessionZone: "data-railshx-session-zone",
    chat: "data-railshx-chat",
    chatForm: "data-railshx-chat-form",
    chatMessageKey: "data-railshx-chat-message-key"
  },
  classes: {
    shell: "todo-shell",
    form: "todo-form",
    sessionForm: "session-form",
    sessionFooter: "session-footer",
    userFrame: "user-management-frame",
    chatForm: "chat-form",
    chatList: "chat-list",
    chatMessage: "chat-message",
    list: "todo-list",
    item: "todo-item",
    dot: "todo-dot"
  },
  ids: {
    openWork: "open-work",
    userFrame: "railshx-user-frame",
    chatPanel: "railshx-chat-panel",
    chatList: "railshx-chat-list"
  },
  meta: {
    templateName: "railshx-template",
    templateContent: "todo-index"
  },
  streams: {
    chatRoom: "todoapp:chat"
  },
  selectors: {
    shell: ".todo-shell",
    form: ".todo-form",
    listItems: ".todo-list .todo-item",
    items: ".todo-item",
    dots: ".todo-item .todo-dot",
    scrollLinks: "[data-railshx-scroll]",
    sessionForms: "[data-railshx-session]",
    sessionFooter: ".session-footer",
    sessionZone: "[data-railshx-session-zone]",
    userFrame: "#railshx-user-frame",
    chatPanel: "#railshx-chat-panel",
    chatList: "#railshx-chat-list",
    chatForms: ".chat-form",
    chatMessages: ".chat-message",
    chatStreamSourceConnected: "turbo-cable-stream-source[connected]",
    openWork: "#open-work"
  }
} as const
