# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    begin
      Main.fail()
      puts(HXRuby.stringify("unreachable"))
    rescue HxException => __hx_ex
      message__hx18913 = __hx_ex.value
      puts(HXRuby.stringify(message__hx18913))
    end
  end
  def self.fail()
    raise HxException.new("boom")
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
