# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require "json"
require_relative "hxruby/core"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.__hx_fields()
    {instance: [], static: ["catchNativeError", "catchNativeWildcardException", "catchWildcardException", "classify", "evaluateThrownValueOnce", "fail", "main", "nextThrownValue", "onlyString", "rethrowNativeError", "rethrowNativeWildcardException", "throwEvaluations", "valueFromTry"]}
  end
  class << self
    attr_accessor :throw_evaluations
  end
  @throw_evaluations = 0
  def self.main()
    begin
      Main.fail()
      puts(HXRuby.stringify("unreachable"))
    rescue StandardError => haxe_exception
      haxe_thrown = (haxe_exception.is_a?(HxException) ? haxe_exception.value : haxe_exception)
      if HXRuby.is_of_type(haxe_thrown, String)
        message = haxe_thrown
        puts(HXRuby.stringify(message))
      else
        raise
      end
    end
    puts(HXRuby.stringify(Main.classify("string")))
    puts(HXRuby.stringify(Main.classify(7)))
    puts(HXRuby.stringify(Main.classify(true)))
    puts(HXRuby.stringify(Main.value_from_try(false)))
    puts(HXRuby.stringify(Main.value_from_try(true)))
    begin
      Main.only_string(7)
    rescue StandardError => haxe_exception__hx1
      haxe_thrown__hx1 = (haxe_exception__hx1.is_a?(HxException) ? haxe_exception__hx1.value : haxe_exception__hx1)
      if HXRuby.is_of_type(haxe_thrown__hx1, Int)
        number = haxe_thrown__hx1
        puts(HXRuby.stringify(("rethrown:" + HXRuby.stringify(number))))
      else
        raise
      end
    end
    puts(HXRuby.stringify(Main.catch_native_error()))
    puts(HXRuby.stringify(Main.catch_wildcard_exception()))
    puts(HXRuby.stringify(Main.catch_native_wildcard_exception()))
    puts(HXRuby.stringify(Main.evaluate_thrown_value_once()))
    puts(HXRuby.stringify(Main.rethrow_native_error()))
    puts(HXRuby.stringify(Main.rethrow_native_wildcard_exception()))
  end
  def self.fail()
    raise HxException.wrap("boom")
  end
  def self.classify(value)
    begin
      raise HxException.wrap(value)
    rescue StandardError => haxe_exception
      haxe_thrown = (haxe_exception.is_a?(HxException) ? haxe_exception.value : haxe_exception)
      if HXRuby.is_of_type(haxe_thrown, String)
        message = haxe_thrown
        return ("string:" + message)
      else
        if HXRuby.is_of_type(haxe_thrown, Int)
          number = haxe_thrown
          return ("int:" + HXRuby.stringify(number))
        else
          hx_tmp = haxe_thrown
          return "dynamic"
        end
      end
    end
  end
  def self.value_from_try(should_throw)
    return begin
      if should_throw
        raise HxException.wrap("value")
      end
      "try-value"
    rescue StandardError => haxe_exception
      haxe_thrown = (haxe_exception.is_a?(HxException) ? haxe_exception.value : haxe_exception)
      if HXRuby.is_of_type(haxe_thrown, String)
        message = haxe_thrown
        ("catch:" + message)
      else
        raise
      end
    end
  end
  def self.only_string(value)
    begin
      raise HxException.wrap(value)
    rescue StandardError => haxe_exception
      haxe_thrown = (haxe_exception.is_a?(HxException) ? haxe_exception.value : haxe_exception)
      if HXRuby.is_of_type(haxe_thrown, String)
        message = haxe_thrown
        return message
      else
        raise
      end
    end
    return "unreachable"
  end
  def self.catch_native_error()
    begin
      Haxe::Json.parse("{")
    rescue StandardError => haxe_exception
      haxe_thrown = (haxe_exception.is_a?(HxException) ? haxe_exception.value : haxe_exception)
      if HXRuby.is_of_type(haxe_thrown, String)
        hx_tmp = haxe_thrown
        return "wrong-string-catch"
      else
        if HXRuby.is_of_type(haxe_thrown, StandardError)
          hx_tmp__hx1 = haxe_thrown
          return "native"
        else
          raise
        end
      end
    end
    return "missing-native-error"
  end
  def self.catch_wildcard_exception()
    begin
      raise HxException.wrap("wildcard")
    rescue StandardError => haxe_exception
      haxe_thrown = (haxe_exception.is_a?(HxException) ? haxe_exception.value : haxe_exception)
      error = HxException.caught(haxe_exception)
      return error.get_message()
    end
  end
  def self.catch_native_wildcard_exception()
    begin
      Haxe::Json.parse("{")
    rescue StandardError => haxe_exception
      haxe_thrown = (haxe_exception.is_a?(HxException) ? haxe_exception.value : haxe_exception)
      error = HxException.caught(haxe_exception)
      return ("native-wildcard:" + HXRuby.stringify((error.get_message().length > 0)))
    end
    return "missing-native-wildcard"
  end
  def self.evaluate_thrown_value_once()
    Main.throw_evaluations = 0
    begin
      raise HxException.wrap(Main.next_thrown_value())
    rescue StandardError => haxe_exception
      haxe_thrown = (haxe_exception.is_a?(HxException) ? haxe_exception.value : haxe_exception)
      if HXRuby.is_of_type(haxe_thrown, String)
        message = haxe_thrown
        return ((("once:" + message) + ":") + HXRuby.stringify(Main.throw_evaluations))
      else
        raise
      end
    end
  end
  def self.next_thrown_value()
    Main.throw_evaluations = (Main.throw_evaluations + 1)
    return "once"
  end
  def self.rethrow_native_error()
    begin
      begin
        Haxe::Json.parse("{")
      rescue StandardError => haxe_exception__hx1
        haxe_thrown__hx1 = (haxe_exception__hx1.is_a?(HxException) ? haxe_exception__hx1.value : haxe_exception__hx1)
        error = haxe_thrown__hx1
        raise HxException.wrap(error)
      end
    rescue StandardError => haxe_exception
      haxe_thrown = (haxe_exception.is_a?(HxException) ? haxe_exception.value : haxe_exception)
      if HXRuby.is_of_type(haxe_thrown, StandardError)
        hx_tmp = haxe_thrown
        return "native-rethrow"
      else
        raise
      end
    end
    return "missing-native-rethrow"
  end
  def self.rethrow_native_wildcard_exception()
    begin
      begin
        Haxe::Json.parse("{")
      rescue StandardError => haxe_exception__hx1
        haxe_thrown__hx1 = (haxe_exception__hx1.is_a?(HxException) ? haxe_exception__hx1.value : haxe_exception__hx1)
        error = HxException.caught(haxe_exception__hx1)
        raise HxException.wrap(error)
      end
    rescue StandardError => haxe_exception
      haxe_thrown = (haxe_exception.is_a?(HxException) ? haxe_exception.value : haxe_exception)
      if HXRuby.is_of_type(haxe_thrown, StandardError)
        hx_tmp = haxe_thrown
        return "native-wildcard-rethrow"
      else
        raise
      end
    end
    return "missing-native-wildcard-rethrow"
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  Main.main()
end
