# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "hxruby/core"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.__hx_fields()
    {instance: [], static: ["fail", "main"]}
  end
  def self.main()
    begin
      Main.fail()
      puts(HXRuby.stringify("unreachable"))
    rescue HxException => __hx_ex
      message = __hx_ex.value
      puts(HXRuby.stringify(message))
    end
  end
  def self.fail()
    raise HxException.new("boom")
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  Main.main()
end
