# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    todo__hx18407 = nil
    controller__hx18408 = nil
    dashboard_view__hx18409 = Views::TodoDashboardView
    form_view__hx18410 = Views::TodoFormView
    view__hx18411 = Views::TodoIndexView
    summary_view__hx18412 = Views::TodoSummaryView
    puts(HXRuby.stringify((todo__hx18407 == nil)))
    puts(HXRuby.stringify((controller__hx18408 == nil)))
    puts(HXRuby.stringify((dashboard_view__hx18409 != nil)))
    puts(HXRuby.stringify((form_view__hx18410 != nil)))
    puts(HXRuby.stringify((view__hx18411 != nil)))
    puts(HXRuby.stringify((summary_view__hx18412 != nil)))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
