package reflaxe.ruby.compiler;

import reflaxe.ruby.naming.RubyNaming;

/**
	Centralizes Ruby output identities that cannot follow the default naming rules.

	The compiler must use the same override when it declares an owned type,
	references that type, and chooses its output filename. Keeping those decisions
	here prevents a collision fix from changing only one call site and emitting a
	constant whose references or feature path no longer agree.

	Most types still delegate directly to `RubyNaming`. The one current exception
	is Haxe's portable root `Date`: emitting it as Ruby `Date` in `date.rb` would
	conflict with the native `ruby.Date` facade. Because generated output is on
	`$LOAD_PATH`, `require "date"` could load that generated file instead of Ruby's
	date library, and both APIs would also compete for the same `Date` constant.
	Using `HxDate` in `hx_date.rb` keeps the portable and native contracts distinct
	while preserving the established load-path-first behavior that permits
	intentional generated or app-local feature implementations.
**/
class RubyOutputLayout {
	static inline final HAXE_DATE_CONSTANT = "HxDate";
	static inline final HAXE_DATE_FILE = "hx_date";

	public static function runnerPrelude(requires:Array<String>, quote:String->String):Array<String> {
		var lines = ["# Generated by reflaxe.ruby", "$LOAD_PATH.unshift(__dir__)"];
		for (value in requires) {
			lines.push("require " + quote(value));
		}
		return lines;
	}

	public static function ownedClassConstant(pack:Array<String>, typeName:String):String {
		return isHaxeDate(pack, typeName) ? HAXE_DATE_CONSTANT : RubyNaming.toConstantName(typeName);
	}

	public static function classConstantOverride(pack:Array<String>, typeName:String):Null<String> {
		return isHaxeDate(pack, typeName) ? HAXE_DATE_CONSTANT : null;
	}

	public static function outputFileName(pack:Array<String>, typeName:String):String {
		return isHaxeDate(pack, typeName) ? HAXE_DATE_FILE : RubyNaming.fileName(typeName);
	}

	static function isHaxeDate(pack:Array<String>, typeName:String):Bool {
		// Only the package-less Haxe std type is renamed. `ruby.Date` has package
		// `ruby`, remains an extern over native `Date`, and owns `require "date"`.
		return (pack == null || pack.length == 0) && typeName == "Date";
	}
}
