package reflaxe.ruby.compiler;

import reflaxe.ruby.naming.RubyNaming;

/**
	Owns collision-safe Ruby identities and runner prelude ordering.

	Portable Haxe `Date` cannot occupy Ruby's `Date` constant or `date.rb`
	feature path once the native date library is used. External features also
	must load before generated files enter `$LOAD_PATH`, or an unrelated output
	file could shadow a Ruby standard/default-gem feature.
**/
class RubyOutputLayout {
	static inline final HAXE_DATE_CONSTANT = "HxDate";
	static inline final HAXE_DATE_FILE = "hx_date";

	public static function runnerPrelude(requires:Array<String>, quote:String->String):Array<String> {
		var lines = ["# Generated by reflaxe.ruby"];
		for (value in requires) {
			lines.push("require " + quote(value));
		}
		lines.push("$LOAD_PATH.unshift(__dir__)");
		return lines;
	}

	public static function ownedClassConstant(pack:Array<String>, typeName:String):String {
		return isHaxeDate(pack, typeName) ? HAXE_DATE_CONSTANT : RubyNaming.toConstantName(typeName);
	}

	public static function classConstantOverride(pack:Array<String>, typeName:String):Null<String> {
		return isHaxeDate(pack, typeName) ? HAXE_DATE_CONSTANT : null;
	}

	public static function outputFileName(pack:Array<String>, typeName:String):String {
		return isHaxeDate(pack, typeName) ? HAXE_DATE_FILE : RubyNaming.fileName(typeName);
	}

	static function isHaxeDate(pack:Array<String>, typeName:String):Bool {
		return (pack == null || pack.length == 0) && typeName == "Date";
	}
}
