# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require "fileutils"
require_relative "hxruby/core"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.__hx_fields()
    {instance: [], static: ["main"]}
  end
  def self.main()
    root = "test/.generated/fileutils_facade/runtime"
    workspace = (root + "/workspace")
    nested = (workspace + "/nested")
    source = "test/fileutils_facade/fixtures/source.txt"
    source_tree = "test/fileutils_facade/fixtures/tree"
    FileUtils.remove_entry_secure(root, true)
    made = FileUtils.mkdir_p(nested)
    puts(HXRuby.stringify((made.length == 1)))
    puts(HXRuby.stringify((made[0] == nested)))
    empty = (workspace + "/empty")
    puts(HXRuby.stringify((FileUtils.mkdir(empty)[0] == empty)))
    copied = (workspace + "/copied.txt")
    FileUtils.cp(source, copied)
    puts(HXRuby.stringify(FileUtils.compare_file(source, copied)))
    puts(HXRuby.stringify((File.read(copied) == "typed fileutils facade\n")))
    moved = (workspace + "/moved.txt")
    FileUtils.mv(copied, moved)
    puts(HXRuby.stringify(FileUtils.compare_file(source, moved)))
    copied_tree = (workspace + "/tree-copy")
    FileUtils.cp_r(source_tree, copied_tree)
    puts(HXRuby.stringify((File.read((copied_tree + "/nested.txt")) == "typed recursive copy\n")))
    touched = (workspace + "/touched.txt")
    puts(HXRuby.stringify((FileUtils.touch(touched)[0] == touched)))
    puts(HXRuby.stringify(FileUtils.uptodate?(moved, [])))
    puts(HXRuby.stringify((FileUtils.rm(touched)[0] == touched)))
    puts(HXRuby.stringify((FileUtils.rm_f((workspace + "/missing.txt"))[0] == (workspace + "/missing.txt"))))
    puts(HXRuby.stringify((FileUtils.rmdir(empty)[0] == empty)))
    FileUtils.remove_entry_secure(copied_tree)
    puts(HXRuby.stringify((!Dir.exist?(copied_tree))))
    FileUtils.remove_entry_secure(root)
    puts(HXRuby.stringify((!Dir.exist?(root))))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  Main.main()
end
