# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require "json"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    puts(JSON.generate({"name" => "ruby", "count" => 2}).to_s())
    puts(File.basename("/tmp/reflaxe.rb").to_s())
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
