# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
module BlockModule
  def self.__hx_name()
    "BlockModule"
  end
  def self.__hx_fields()
    {instance: ["decorateFromModule"], static: []}
  end
  def decorate_from_module(value)
    return yield(value)
  end
end
