# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require "active_support/concern"
module BlockConcern
  def self.__hx_name()
    "BlockConcern"
  end
  def self.__hx_fields()
    {instance: ["decorateFromConcern"], static: []}
  end
  extend ActiveSupport::Concern
  def decorate_from_concern(value)
    return yield(value)
  end
end
