# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class BlockConstructed
  def self.__hx_name()
    "BlockConstructed"
  end
  def self.__hx_fields()
    {instance: ["rendered"], static: []}
  end
  attr_accessor :rendered
  def initialize(value)
    self.rendered = yield(value)
  end
end
