# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class ConcernReceiver
  def self.__hx_name()
    "ConcernReceiver"
  end
  def self.__hx_fields()
    {instance: ["decorateFromConcern"], static: []}
  end
  include BlockConcern
  def initialize()
    nil
  end
end
