# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "./support/string_block_patch"
require_relative "hxruby/core"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.__hx_fields()
    {instance: [], static: ["main"]}
  end
  def self.main()
    puts(HXRuby.stringify(("direct:" + HXRuby.stringify(OwnedBlocks.direct(5) { |value| (value + 1) }))))
    puts(HXRuby.stringify(("instance:" + HXRuby.stringify(OwnedBlocks.new().instance_direct(5) { |value__hx1| (value__hx1 + 2) }))))
    puts(HXRuby.stringify(("optional:" + OwnedBlocks.optional(3))))
    puts(HXRuby.stringify(("optional:" + OwnedBlocks.optional(4) { |value__hx2| ("value:" + HXRuby.stringify(value__hx2)) })))
    absent = nil
    puts(HXRuby.stringify(("optional-null:" + OwnedBlocks.optional(4, &absent))))
    optional_callback = ->(value__hx3) { ("stored:" + HXRuby.stringify(value__hx3)) }
    puts(HXRuby.stringify(("optional-stored:" + OwnedBlocks.optional(4, &optional_callback))))
    captured = OwnedBlocks.capture { |value__hx4| ("captured:" + HXRuby.stringify(value__hx4)) }
    puts(HXRuby.stringify(captured.call(5)))
    puts(HXRuby.stringify(OwnedBlocks.forward(6) { |value__hx5| ("forward:" + HXRuby.stringify(value__hx5)) }))
    puts(HXRuby.stringify(OwnedBlocks.nested(7) { |value__hx6| ("nested:" + HXRuby.stringify(value__hx6)) }))
    puts(HXRuby.stringify(("sum:" + HXRuby.stringify(OwnedBlocks.sum([1, 2, 3]) { |value__hx7| (value__hx7 * 2) }))))
    puts(HXRuby.stringify(("zero:" + OwnedBlocks.zero { "zero" })))
    puts(HXRuby.stringify(("pair:" + HXRuby.stringify(OwnedBlocks.pair(3, 4) { |left, right| (left + right) }))))
    constructed = BlockConstructed.new(8) { |value__hx8| ("ctor:" + HXRuby.stringify(value__hx8)) }
    puts(HXRuby.stringify(constructed.rendered))
    puts(HXRuby.stringify(ModuleReceiver.new().decorate_from_module(9) { |value__hx9| ("module:" + HXRuby.stringify(value__hx9)) }))
    puts(HXRuby.stringify(ConcernReceiver.new().decorate_from_concern(10) { |value__hx10| ("concern:" + HXRuby.stringify(value__hx10)) }))
    puts(HXRuby.stringify("patch".decorate { |value__hx11| value__hx11.upcase() }))
    early = OwnedBlocks.direct(11, &->(value__hx12) do
      if (value__hx12 > 0)
        return ("early:" + HXRuby.stringify(value__hx12))
      end
      "fallback"
    end)
    puts(HXRuby.stringify(early))
    puts(HXRuby.stringify("after-early"))
    nested_return = OwnedBlocks.direct(12) do |value__hx13|
      add = ->() { (value__hx13 + 3) }
      add.call()
    end
    puts(HXRuby.stringify(("nested-return:" + HXRuby.stringify(nested_return))))
    begin
      OwnedBlocks.direct(1) do |hx_tmp|
        raise HxException.wrap("block-boom")
      end
    rescue StandardError => haxe_exception
      haxe_thrown = (haxe_exception.is_a?(HxException) ? haxe_exception.value : haxe_exception)
      if HXRuby.is_of_type(haxe_thrown, String)
        error = haxe_thrown
        puts(HXRuby.stringify(("throw:" + error)))
      else
        raise
      end
    end
    puts(HXRuby.stringify("after-throw"))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  Main.main()
end
