# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class ModuleReceiver
  def self.__hx_name()
    "ModuleReceiver"
  end
  def self.__hx_fields()
    {instance: ["decorateFromModule"], static: []}
  end
  include BlockModule
  def initialize()
    nil
  end
end
