# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class OwnedBlocks
  def self.__hx_name()
    "OwnedBlocks"
  end
  def self.__hx_fields()
    {instance: ["instanceDirect"], static: ["capture", "direct", "forward", "nested", "optional", "pair", "sum", "zero"]}
  end
  def initialize()
    nil
  end
  def instance_direct(value)
    return yield(value)
  end
  def self.direct(value)
    return yield(value)
  end
  def self.optional(value, &block)
    if (block == nil)
      return "none"
    end
    return block.call(value)
  end
  def self.capture(&block)
    if (block == nil)
      raise(ArgumentError, "required block missing for self.capture")
    end
    return block
  end
  def self.forward(value, &block)
    if (block == nil)
      raise(ArgumentError, "required block missing for self.forward")
    end
    return OwnedBlocks.direct(value, &block)
  end
  def self.nested(value, &block)
    if (block == nil)
      raise(ArgumentError, "required block missing for self.nested")
    end
    invoke = ->() { block.call(value) }
    return invoke.call()
  end
  def self.sum(values)
    total = 0
    g = 0
    while (g < values.length)
      value = values[g]
      g = (g + 1)
      total = (total + yield(value))
    end
    return total
  end
  def self.zero()
    return yield
  end
  def self.pair(left, right)
    return yield(left, right)
  end
end
