# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    mailer__hx0 = Mailers::UserMailer.new()
    mailer__hx0.welcome("reader@example.test", "Ada", "Typed RailsHx mailers are ready.")
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
