# Generated by reflaxe.ruby
# Rails controller output; Zeitwerk path should match the Ruby constant.
require "action_controller/railtie"
require "turbo-rails"
module Controllers
  class ChatMessagesController < ActionController::Base
    def initialize()
      super()
    end
    def create()
      gthis__hx0 = self
      attrs__hx0 = self.params().require("chat_message").permit([:body, :user_id])
      Models::ChatMessage.create(attrs__hx0)
      self.respond_to() do |format__hx0|
        format__hx0.turbo_stream() { gthis__hx0.render(turbo_stream: turbo_stream.replace("railshx-chat-panel", partial: "controllers/todos/chat_panel", locals: {messages: Models::ChatMessage.latest().to_a(), current_user: Controllers::UserSession.current_user(gthis__hx0), users: Models::User.order(name: :asc).to_a()})) }
        format__hx0.html() { gthis__hx0.redirect_to(self.todos_path(), status: :see_other) }
      end
    end
  end
end
