# Generated by reflaxe.ruby
# Rails controller output; Zeitwerk path should match the Ruby constant.
require "action_controller/railtie"
require "turbo-rails"
module Controllers
  class ChatMessagesController < ActionController::Base
    before_action :authenticate_user!
    def initialize()
      super()
    end
    def index()
      gthis__hx0 = self
      self.respond_to() do |format__hx0|
        format__hx0.turbo_stream() { gthis__hx0.render(turbo_stream: turbo_stream.replace("railshx-chat-panel", partial: "controllers/todos/chat_panel", locals: {messages: Models::ChatMessage.latest().to_a(), current_user: current_user(), users: Models::User.order(name: :asc).to_a()})) }
        format__hx0.html() { gthis__hx0.redirect_to(self.todos_path(), status: :see_other) }
      end
    end
    def create()
      gthis__hx0 = self
      current_user__hx0 = current_user()
      attrs__hx0 = self.params().require("chat_message").permit([:body])
      attrs__hx0 = attrs__hx0.merge(user_id: current_user__hx0.id)
      message__hx0 = Models::ChatMessage.create(attrs__hx0)
      Turbo::StreamsChannel.broadcast_prepend_to("todoapp:chat", target: "railshx-chat-list", partial: "controllers/todos/chat_message", locals: {message: message__hx0})
      self.respond_to() do |format__hx0|
        format__hx0.turbo_stream() { gthis__hx0.head(:no_content) }
        format__hx0.html() { gthis__hx0.redirect_to(self.todos_path(), status: :see_other) }
      end
    end
  end
end
