# Generated by reflaxe.ruby
# Rails controller output; Zeitwerk path should match the Ruby constant.
require "action_controller/railtie"
module Controllers
  class TodosController < ActionController::Base
    def initialize()
      super()
    end
    def index()
      todos__hx18455 = Models::Todo.incomplete()
      self.render(template: "controllers/todos/index", locals: {"todos" => todos__hx18455})
    end
    def create()
      attrs__hx18457 = self.params().require("todo").permit([:title, :is_completed, :user_id])
      todo__hx18458 = Models::Todo.create(attrs__hx18457)
      self.redirect_to(self.todos_path())
    end
  end
end
