# Generated by reflaxe.ruby
# Rails controller output; Zeitwerk path should match the Ruby constant.
require "action_controller/railtie"
module Controllers
  class TodosController < ActionController::Base
    def initialize()
      super()
    end
    def index()
      todos__hx16748 = Models::Todo.incomplete()
      self.render(json: todos__hx16748)
    end
    def create()
      attrs__hx16750 = self.params().require("todo").permit([:title, :is_completed, :user_id])
      todo__hx16751 = Models::Todo.create(attrs__hx16750)
      self.redirect_to(self.todos_path())
    end
  end
end
