# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class HxDate
  def self.__hx_name()
    "Date"
  end
  def self.__hx_fields()
    {instance: ["getDate", "getDay", "getFullYear", "getHours", "getMinutes", "getMonth", "getSeconds", "getTime", "getTimezoneOffset", "getUTCDate", "getUTCDay", "getUTCFullYear", "getUTCHours", "getUTCMinutes", "getUTCMonth", "getUTCSeconds", "toString"], static: ["fromRubyTime", "fromString", "fromTime", "now"]}
  end
  def initialize(year, month, day, hours, minutes, seconds)
    @native_time = Time.local(year, month + 1, day, hours, minutes, seconds)
  end
  def get_time()
    return @native_time.to_f * 1000.0
  end
  def get_full_year()
    return @native_time.year
  end
  def get_month()
    return @native_time.month - 1
  end
  def get_date()
    return @native_time.day
  end
  def get_day()
    return @native_time.wday
  end
  def get_hours()
    return @native_time.hour
  end
  def get_minutes()
    return @native_time.min
  end
  def get_seconds()
    return @native_time.sec
  end
  def get_utc_full_year()
    return @native_time.getutc.year
  end
  def get_utc_month()
    return @native_time.getutc.month - 1
  end
  def get_utc_date()
    return @native_time.getutc.day
  end
  def get_utc_day()
    return @native_time.getutc.wday
  end
  def get_utc_hours()
    return @native_time.getutc.hour
  end
  def get_utc_minutes()
    return @native_time.getutc.min
  end
  def get_utc_seconds()
    return @native_time.getutc.sec
  end
  def get_timezone_offset()
    return (-@native_time.utc_offset / 60).to_i
  end
  def to_string()
    return @native_time.strftime('%Y-%m-%d %H:%M:%S')
  end
  def self.now()
    return HxDate.from_ruby_time(Time.now)
  end
  def self.from_time(time)
    return HxDate.from_ruby_time(Time.at(time / 1000.0).getlocal)
  end
  def self.from_string(value)
    return HxDate.from_ruby_time((begin string = value.to_s; if (match = /\A(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2}):(\d{2})\z/.match(string)); Time.local(match[1].to_i, match[2].to_i, match[3].to_i, match[4].to_i, match[5].to_i, match[6].to_i); elsif (match = /\A(\d{4})-(\d{2})-(\d{2})\z/.match(string)); Time.local(match[1].to_i, match[2].to_i, match[3].to_i, 0, 0, 0); elsif (match = /\A(\d{2}):(\d{2}):(\d{2})\z/.match(string)); Time.at((match[1].to_i * 3600) + (match[2].to_i * 60) + match[3].to_i).getlocal; else raise ArgumentError, 'Invalid date format'; end end))
  end
  def self.from_ruby_time(value)
    date = HxDate.new(1970, 0, 1, 0, 0, 0)
    date.instance_variable_set(:@native_time, value)
    return date
  end
end
