# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "hxruby/core"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.__hx_fields()
    {instance: [], static: ["assertBytes", "main", "removeTree", "root"]}
  end
  class << self
    attr_accessor :root
  end
  @root = "test/.generated/filesystem_parity_probe"
  def self.main()
    Main.remove_tree(Main.root)
    nested = (Main.root + "/one/two")
    (::FileUtils.mkdir_p(nested); nil)
    (::FileUtils.mkdir_p(nested); nil)
    Main::FilesystemParityAssert.is_true((::File.exist?(nested) || ::File.symlink?(nested)), "nested directory exists")
    Main::FilesystemParityAssert.is_true((raise Errno::ENOENT, nested unless (::File.exist?(nested) || ::File.symlink?(nested)); ::File.directory?(nested)), "nested path is directory")
    Main::FilesystemParityAssert.is_true((::File.exist?("/") || ::File.symlink?("/")), "root exists")
    Main::FilesystemParityAssert.is_true((begin
      stat = ::File.stat("/")
      {"gid" => stat.gid, "uid" => stat.uid, "atime" => begin
        value = stat.atime
        HxDate.new(value.year, value.month - 1, value.day, value.hour, value.min, value.sec)
      end, "mtime" => begin
        value__hx1 = stat.mtime
        HxDate.new(value__hx1.year, value__hx1.month - 1, value__hx1.day, value__hx1.hour, value__hx1.min, value__hx1.sec)
      end, "ctime" => begin
        value__hx2 = stat.ctime
        HxDate.new(value__hx2.year, value__hx2.month - 1, value__hx2.day, value__hx2.hour, value__hx2.min, value__hx2.sec)
      end, "size" => stat.size, "dev" => stat.dev, "ino" => stat.ino, "nlink" => stat.nlink, "rdev" => stat.rdev, "mode" => stat.mode}
    end != nil), "root stat")
    names = (raise Errno::ENOENT, Main.root unless ::File.directory?(Main.root); ::Dir.children(Main.root))
    Main::FilesystemParityAssert.equal(1, names.length, "root entry count")
    Main::FilesystemParityAssert.is_true((HXRuby.array_index_of(names, "one", nil) >= 0), "root entry name")
    text_path = (nested + "/note.txt")
    (::File.write(text_path, "first\nsecond\n"); nil)
    Main::FilesystemParityAssert.equal("first\nsecond\n", ::File.read(text_path), "text newline round trip")
    text_stat_uid = nil
    text_stat_size = nil
    text_stat_rdev = nil
    text_stat_nlink = nil
    text_stat_mtime = nil
    text_stat_mode = nil
    text_stat_ino = nil
    text_stat_gid = nil
    text_stat_dev = nil
    text_stat_ctime = nil
    text_stat_atime = nil
    stat__hx1 = ::File.stat(text_path)
    text_stat_gid = stat__hx1.gid
    text_stat_uid = stat__hx1.uid
    text_stat_atime = begin
      value__hx3 = stat__hx1.atime
      HxDate.new(value__hx3.year, value__hx3.month - 1, value__hx3.day, value__hx3.hour, value__hx3.min, value__hx3.sec)
    end
    text_stat_mtime = begin
      value__hx4 = stat__hx1.mtime
      HxDate.new(value__hx4.year, value__hx4.month - 1, value__hx4.day, value__hx4.hour, value__hx4.min, value__hx4.sec)
    end
    text_stat_ctime = begin
      value__hx5 = stat__hx1.ctime
      HxDate.new(value__hx5.year, value__hx5.month - 1, value__hx5.day, value__hx5.hour, value__hx5.min, value__hx5.sec)
    end
    text_stat_size = stat__hx1.size
    text_stat_dev = stat__hx1.dev
    text_stat_ino = stat__hx1.ino
    text_stat_nlink = stat__hx1.nlink
    text_stat_rdev = stat__hx1.rdev
    text_stat_mode = stat__hx1.mode
    Main::FilesystemParityAssert.equal(13, text_stat_size, "file stat size")
    Main::FilesystemParityAssert.is_true((text_stat_mtime.get_time() > 0), "file stat mtime")
    source_absolute = (Haxe::Io::Path.is_absolute("./filesystem-source.txt") ? "./filesystem-source.txt" : ::File.join(::Dir.pwd, "./filesystem-source.txt"))
    Main::FilesystemParityAssert.is_true((HXRuby.string_index_of(source_absolute, "/./filesystem-source.txt") >= 0), "absolutePath preserves dot segment")
    Main::FilesystemParityAssert.equal("/filesystem-source.txt", (Haxe::Io::Path.is_absolute("/filesystem-source.txt") ? "/filesystem-source.txt" : ::File.join(::Dir.pwd, "/filesystem-source.txt")), "absolute path unchanged")
    Main::FilesystemParityAssert.is_true((HXRuby.string_index_of(::File.realpath(text_path), "filesystem_parity_probe/one/two/note.txt") >= 0), "fullPath resolves existing path")
    copy_path = (nested + "/copy.txt")
    (::File.write(copy_path, "old"); nil)
    (::FileUtils.copy_file(text_path, copy_path); nil)
    Main::FilesystemParityAssert.equal("first\nsecond\n", ::File.read(copy_path), "copy overwrites destination")
    renamed_path = (nested + "/renamed.txt")
    (::File.rename(copy_path, renamed_path); nil)
    Main::FilesystemParityAssert.is_true((::File.exist?(renamed_path) || ::File.symlink?(renamed_path)), "rename destination exists")
    Main::FilesystemParityAssert.is_false((::File.exist?(copy_path) || ::File.symlink?(copy_path)), "rename source removed")
    binary = Haxe::Io::Bytes.alloc(4)
    g_current = nil
    g_array = nil
    g_current = 0
    g_array = [0, 127, 128, 255]
    while (g_current < g_array.length)
      g_value = nil
      g_key = nil
      g_value = g_array[g_current]
      g_key = (g_current).tap { g_current = g_current + 1 }
      index = g_key
      value__hx6 = g_value
      binary.set(index, value__hx6)
    end
    binary_path = (nested + "/bytes.bin")
    (::File.binwrite(binary_path, binary.get_data().pack('C*')); nil)
    Main.assert_bytes(binary, begin
      data = ::File.binread(binary_path).bytes.to_a
      Haxe::Io::Bytes.new(data.length, data)
    end, "binary save/get")
    input = begin
      binary__hx1 = true
      Sys::Io::FileInput.new(::File.open(binary_path, (binary__hx1 ? "rb" : "r")))
    end
    Main::FilesystemParityAssert.equal(0, input.tell(), "input initial position")
    Main::FilesystemParityAssert.equal(0, input.read_byte(), "input first byte")
    Main::FilesystemParityAssert.equal(1, input.tell(), "input position after byte")
    input.seek(2, Sys::Io::FileSeek.seek_begin())
    Main::FilesystemParityAssert.equal(128, input.read_byte(), "input seek begin")
    input.seek(-1, Sys::Io::FileSeek.seek_end())
    Main::FilesystemParityAssert.equal(255, input.read_byte(), "input seek end")
    Main::FilesystemParityAssert.is_false(input.eof(), "EOF is false before failed read")
    Main::FilesystemParityAssert.raises(->() { input.read_byte() }, "read past EOF raises")
    Main::FilesystemParityAssert.is_true(input.eof(), "EOF latches after failed read")
    input.seek(0, Sys::Io::FileSeek.seek_begin())
    Main::FilesystemParityAssert.is_false(input.eof(), "seek resets EOF")
    read_buffer = Haxe::Io::Bytes.alloc(4)
    Main::FilesystemParityAssert.equal(4, input.read_bytes(read_buffer, 0, 4), "input readBytes length")
    Main.assert_bytes(binary, read_buffer, "input readBytes contents")
    input.close()
    output_path = (nested + "/stream.bin")
    output = begin
      binary__hx2 = true
      Sys::Io::FileOutput.new(::File.open(output_path, (binary__hx2 ? "wb" : "w")))
    end
    output.write(binary)
    Main::FilesystemParityAssert.equal(4, output.tell(), "output position")
    output.close()
    Main.assert_bytes(binary, begin
      data__hx1 = ::File.binread(output_path).bytes.to_a
      Haxe::Io::Bytes.new(data__hx1.length, data__hx1)
    end, "stream output bytes")
    Main::FilesystemParityAssert.raises(->() { (::FileUtils.copy_file((Main.root + "/missing"), (Main.root + "/missing-copy")); nil) }, "copy missing source raises")
    Main::FilesystemParityAssert.raises(->() { ::File.read((Main.root + "/missing")) }, "getContent missing file raises")
    Main::FilesystemParityAssert.raises(->() do
      stat__hx2 = ::File.stat((Main.root + "/missing"))
      inlobj_uid = nil
      inlobj_size = nil
      inlobj_rdev = nil
      inlobj_nlink = nil
      inlobj_mtime = nil
      inlobj_mode = nil
      inlobj_ino = nil
      inlobj_gid = nil
      inlobj_dev = nil
      inlobj_ctime = nil
      inlobj_atime = nil
      inlobj_gid = stat__hx2.gid
      inlobj_uid = stat__hx2.uid
      inlobj_atime = begin
        value__hx7 = stat__hx2.atime
        HxDate.new(value__hx7.year, value__hx7.month - 1, value__hx7.day, value__hx7.hour, value__hx7.min, value__hx7.sec)
      end
      inlobj_mtime = begin
        value__hx8 = stat__hx2.mtime
        HxDate.new(value__hx8.year, value__hx8.month - 1, value__hx8.day, value__hx8.hour, value__hx8.min, value__hx8.sec)
      end
      inlobj_ctime = begin
        value__hx9 = stat__hx2.ctime
        HxDate.new(value__hx9.year, value__hx9.month - 1, value__hx9.day, value__hx9.hour, value__hx9.min, value__hx9.sec)
      end
      inlobj_size = stat__hx2.size
      inlobj_dev = stat__hx2.dev
      inlobj_ino = stat__hx2.ino
      inlobj_nlink = stat__hx2.nlink
      inlobj_rdev = stat__hx2.rdev
      inlobj_mode = stat__hx2.mode
    end, "stat missing path raises")
    Main::FilesystemParityAssert.raises(->() { (raise Errno::ENOENT, (Main.root + "/missing") unless (::File.exist?((Main.root + "/missing")) || ::File.symlink?((Main.root + "/missing"))); ::File.directory?((Main.root + "/missing"))) }, "isDirectory missing path raises")
    Main::FilesystemParityAssert.raises(->() { (raise Errno::ENOENT, text_path unless ::File.directory?(text_path); ::Dir.children(text_path)) }, "readDirectory file path raises")
    Main::FilesystemParityAssert.raises(->() { (::File.delete((Main.root + "/missing")); nil) }, "delete missing file raises")
    Main::FilesystemParityAssert.raises(->() { (::Dir.rmdir((Main.root + "/missing")); nil) }, "delete missing directory raises")
    Main.remove_tree(Main.root)
    puts(HXRuby.stringify("filesystem-parity ok"))
  end
  def self.assert_bytes(expected, actual, label)
    Main::FilesystemParityAssert.equal(expected.length, actual.length, (label + " length"))
    g = 0
    g1 = expected.length
    while (g < g1)
      index = (g).tap { g = g + 1 }
      Main::FilesystemParityAssert.equal(expected.get(index), actual.get(index), ((label + " byte ") + HXRuby.stringify(index)))
    end
  end
  def self.remove_tree(path)
    if (!(::File.exist?(path) || ::File.symlink?(path)))
      return
    end
    if (!(raise Errno::ENOENT, path unless (::File.exist?(path) || ::File.symlink?(path)); ::File.directory?(path)))
      (::File.delete(path); nil)
      return
    end
    g = 0
    g1 = (raise Errno::ENOENT, path unless ::File.directory?(path); ::Dir.children(path))
    while (g < g1.length)
      entry = g1[g]
      g = (g + 1)
      Main.remove_tree(Haxe::Io::Path.join([path, entry]))
    end
    (::Dir.rmdir(path); nil)
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  Main.main()
end
