# Generated by RailsHx from @:railsMailerPreview.
# Rails preview output; Rails discovers this under test/mailers/previews.
require "action_mailer/railtie"

class UserMailerPreview < ActionMailer::Preview
  def welcome()
    return Mailers::UserMailer.with(email: "preview@example.test", name: "Preview Ada", message: "Previewed through typed RailsHx params.").welcome_from_params()
  end
end
