# Generated by reflaxe.ruby
# Rails model output; Zeitwerk path should match the Ruby constant.
require "active_record"
module Models
  class AuditLog < ::ApplicationRecord
    self.table_name = "audit_logs"
    def self.__hx_rails_schema()
      {
        table_name: "audit_logs",
        timestamps: false,
        columns: [
          {name: :event_count, haxe_name: "eventCount", ruby_name: "event_count", haxe_type: "Int", rails_type: :integer, nullable: false, default: 0, primary_key: false, index: false, unique: false, db_type: nil}
        ]
      }
    end
    # haxe column event_count: Int
    def initialize()
      super()
    end
  end
end
