# Generated by reflaxe.ruby
# Rails model output; Zeitwerk path should match the Ruby constant.
require "active_record"
module Models
  class Todo < ::ApplicationRecord
    self.table_name = "todos"
    def self.__hx_rails_schema()
      {
        table_name: "todos",
        timestamps: true,
        columns: [
          {name: :id, haxe_name: "id", ruby_name: "id", haxe_type: "Int", rails_type: :bigint, nullable: false, default: nil, primary_key: true, index: false, unique: false, db_type: :bigint},
          {name: :title, haxe_name: "title", ruby_name: "title", haxe_type: "String", rails_type: :string, nullable: false, default: nil, primary_key: false, index: true, unique: false, db_type: nil},
          {name: :completed, haxe_name: "completed", ruby_name: "completed", haxe_type: "Bool", rails_type: :boolean, nullable: false, default: false, primary_key: false, index: false, unique: false, db_type: nil},
          {name: :status, haxe_name: "status", ruby_name: "status", haxe_type: "String", rails_type: :string, nullable: false, default: "open", primary_key: false, index: false, unique: false, db_type: nil},
          {name: :notes, haxe_name: "notes", ruby_name: "notes", haxe_type: "String", rails_type: :text, nullable: true, default: nil, primary_key: false, index: false, unique: false, db_type: :text},
          {name: :external_id, haxe_name: "externalId", ruby_name: "external_id", haxe_type: "String", rails_type: :string, nullable: false, default: nil, primary_key: false, index: false, unique: true, db_type: nil},
          {name: :user_id, haxe_name: "userId", ruby_name: "user_id", haxe_type: "Int", rails_type: :integer, nullable: false, default: nil, primary_key: false, index: true, unique: false, db_type: nil}
        ]
      }
    end
    def self.typed_column_count()
      __hx_rails_schema()[:columns].length
    end
    belongs_to :user, optional: false, foreign_key: "user_id", inverse_of: :todos
    enum :status, {open: "open", done: "done"}
    scope :incomplete, -> { where(completed: false) }
    scope :with_status, ->(status__hx0) { where(status: status__hx0) }
    default_scope -> { order(title: :asc) }
    # haxe column id: Int
    # haxe column title: String
    # haxe column completed: Bool
    # haxe column status: String
    # haxe column notes: Null
    # haxe column external_id: String
    # haxe column user_id: Int
    validates :title, presence: true, length: {minimum: 3}
    validates :external_id, presence: true, uniqueness: true, format: {with: /^[a-z0-9-]+$/}
    validates :status, inclusion: {within: ["open", "done"]}
    validates :user_id, numericality: {only_integer: true, greater_than: 0}
    before_validation :normalize_title
    after_commit :publish_lifecycle_event
    def initialize(*args, **kwargs)
      args = args + [kwargs] unless kwargs.empty?
      super(*args)
    end
    def normalize_title()
      nil
    end
    def publish_lifecycle_event()
      nil
    end
  end
end
