package reflaxe.ruby;

#if (macro || reflaxe_runtime)
import haxe.io.Path;
import haxe.macro.Context;
import haxe.macro.Type.AbstractType;
import haxe.macro.Type.ClassType;
import haxe.macro.Type.DefType;
import haxe.macro.Type.EnumType;
import haxe.macro.Type.ModuleType;
import haxe.macro.Type.TypedExpr;
import haxe.macro.Type.TVar;
import reflaxe.GenericCompiler;
import reflaxe.data.ClassFuncData;
import reflaxe.data.ClassVarData;
import reflaxe.data.EnumOptionData;
import reflaxe.output.DataAndFileInfo;
import reflaxe.output.OutputPath;
import reflaxe.output.StringOrBytes;
import reflaxe.ruby.ast.RubyAST.RubyExpr;
import reflaxe.ruby.ast.RubyAST.RubyFile;
import reflaxe.ruby.ast.RubyAST.RubyStatement;
import reflaxe.ruby.compiler.RubyBuildContext;
import reflaxe.ruby.compiler.RubyBuildContextResolver;
import reflaxe.ruby.naming.RubyNaming;
import reflaxe.ruby.RequireRegistry;
import sys.FileSystem;
import sys.io.File;

class RubyCompiler extends GenericCompiler<RubyFile, RubyFile, RubyExpr, RubyFile, RubyFile> {
	public var currentCompilationContext:Null<CompilationContext>;
	var emittedRubyPaths:Array<String> = [];
	var emittedAppRubyPaths:Array<String> = [];
	var requireRegistry:RequireRegistry = new RequireRegistry();
	var buildContext:RubyBuildContext;
	var didEmitMain:Bool = false;
	static var needsDataDefine:Bool = false;
	static var needsHxException:Bool = false;

	public function new() {
		super();
		buildContext = RubyBuildContextResolver.resolve();
	}

	public function createCompilationContext():CompilationContext {
		return CompilationContext.fromBuildContext(RubyBuildContextResolver.resolve());
	}

	public function generateOutputIterator():Iterator<DataAndFileInfo<StringOrBytes>> {
		return new RubyOutputIterator(this);
	}

	override public function onCompileStart():Void {
		buildContext = RubyBuildContextResolver.resolve();
		emittedRubyPaths = [];
		emittedAppRubyPaths = [];
		requireRegistry = new RequireRegistry();
		didEmitMain = false;
		needsDataDefine = false;
		needsHxException = false;
	}

	override public function onCompileEnd():Void {
		if (buildContext.railsMode) {
			setRailsAutoloadInitializer();
		}
		if (!didEmitMain) {
			return;
		}
		setRuntimeExtraFile("core.rb");
		if (needsDataDefine) {
			setRuntimeExtraFile("data_define.rb");
		}
		if (needsHxException) {
			setRuntimeExtraFile("hx_exception.rb");
		}
		var paths = [outputRelativePath("hxruby/core.rb", true)];
		if (needsDataDefine) {
			paths.push(outputRelativePath("hxruby/data_define.rb", true));
		}
		if (needsHxException) {
			paths.push(outputRelativePath("hxruby/hx_exception.rb", true));
		}
		var appPaths = emittedAppRubyPaths.copy();
		appPaths.sort((a, b) -> {
			if (a == "main.rb") return 1;
			if (b == "main.rb") return -1;
			return Reflect.compare(a, b);
		});
		paths = paths.concat(appPaths);
		var lines = ["# Generated by reflaxe.ruby", "$LOAD_PATH.unshift(__dir__)"];
		for (value in requireRegistry.requireValues()) {
			lines.push("require " + quoteRubyStringForCode(value));
		}
		for (value in requireRegistry.requireRelativeValues()) {
			lines.push("require_relative " + quoteRubyStringForCode(value));
		}
		for (path in paths) {
			lines.push("require_relative " + quoteRubyStringForCode(path.substr(0, path.length - 3)));
		}
		lines.push("Main.main");
		lines.push("");
		setExtraFile(OutputPath.fromStr("run.rb"), lines.join("\n"));
	}

	public function compileClassImpl(classType:ClassType, varFields:Array<ClassVarData>, funcFields:Array<ClassFuncData>):Null<RubyFile> {
		setRubyOutputPath(classType.pack, classType.name);
		var moduleRequires = collectModuleRequires(classType.meta);
		if (hasMeta(classType.meta, ":railsModel")) {
			requireRegistry.addRequire("active_record");
			moduleRequires.addRequire("active_record");
			return compileRailsModelImpl(classType, varFields, funcFields, moduleRequires);
		}
		if (hasMeta(classType.meta, ":railsController")) {
			requireRegistry.addRequire("action_controller/railtie");
			moduleRequires.addRequire("action_controller/railtie");
			return compileRailsControllerImpl(classType, varFields, funcFields, moduleRequires);
		}
		var classBody:Array<RubyStatement> = [];
		for (field in varFields) {
			classBody.push(compileVarField(field));
		}
		for (field in funcFields) {
			if (field.expr == null) {
				continue;
			}
			if (hasMeta(field.field.meta, ":rubyExternStub")) {
				continue;
			}
			classBody.push(compileMethod(field));
		}
		if (classBody.length == 0) {
			classBody.push(RubyComment("No Ruby members emitted for " + fullTypeName(classType.pack, classType.name)));
		}

		var statements = [
			RubyComment("Generated by reflaxe.ruby"),
			RubyComment("Generated type shell for Ruby output.")
		];
		statements = statements.concat(requirePreludeStatements(moduleRequires));
		statements.push(wrapInModules(classType.pack, RubyClassDecl(RubyNaming.toConstantName(classType.name), classBody)));

		if (classType.pack.length == 0 && classType.name == "Main" && hasStaticMain(funcFields)) {
			didEmitMain = true;
			statements.push(RubyRawStatement("if __FILE__ == $PROGRAM_NAME\n  $LOAD_PATH.unshift(__dir__)\n  require_relative \"hxruby/core\"\n  Main.main()\nend"));
		}

		return {
			modulePath: classType.pack == null ? [] : classType.pack.copy(),
			statements: statements
		};
	}

	public function compileEnumImpl(enumType:EnumType, options:Array<EnumOptionData>):Null<RubyFile> {
		setRubyOutputPath(enumType.pack, enumType.name);
		var moduleRequires = collectModuleRequires(enumType.meta);
		needsDataDefine = true;
		var statements = [
			RubyComment("Generated by reflaxe.ruby"),
			RubyComment("Enum constructors use hxruby/data_define.rb for Data.define compatibility.")
		];
		statements = statements.concat(requirePreludeStatements(moduleRequires));
		statements.push(wrapInModules(enumType.pack, RubyModuleDecl(RubyNaming.toConstantName(enumType.name), compileEnumBody(options))));
		return {
			modulePath: enumType.pack == null ? [] : enumType.pack.copy(),
			statements: statements
		};
	}

	public function compileExpressionImpl(expr:TypedExpr, topLevel:Bool):Null<RubyExpr> {
		return compileExpr(expr);
	}

	override public function compileTypedefImpl(typedefType:DefType):Null<RubyFile> {
		setRubyOutputPath(typedefType.pack, typedefType.name);
		return typeShell(typedefType.pack, typedefType.name, RubyModuleDecl(RubyNaming.toConstantName(typedefType.name), [
			RubyComment("Haxe typedef " + fullTypeName(typedefType.pack, typedefType.name) + " has no Ruby runtime body.")
		]), collectModuleRequires(typedefType.meta));
	}

	override public function compileAbstractImpl(abstractType:AbstractType):Null<RubyFile> {
		setRubyOutputPath(abstractType.pack, abstractType.name);
		return typeShell(abstractType.pack, abstractType.name, RubyModuleDecl(RubyNaming.toConstantName(abstractType.name), [
			RubyComment("Haxe abstract " + fullTypeName(abstractType.pack, abstractType.name) + " has no Ruby runtime body.")
		]), collectModuleRequires(abstractType.meta));
	}

	static function typeShell(pack:Array<String>, name:String, declaration:RubyStatement, ?moduleRequires:RequireRegistry):RubyFile {
		var statements:Array<RubyStatement> = [
			RubyComment("Generated by reflaxe.ruby"),
			RubyComment("Generated type shell for Ruby output.")
		];
		statements = statements.concat(requirePreludeStatements(moduleRequires));
		statements.push(wrapInModules(pack, declaration));
		return {
			modulePath: pack == null ? [] : pack.copy(),
			statements: statements
		};
	}

	function collectModuleRequires(meta:Null<haxe.macro.Type.MetaAccess>):RequireRegistry {
		var moduleRequires = new RequireRegistry();
		moduleRequires.collectMeta(meta);
		moduleRequires.collectTypeUsage(getTypeUsage());
		requireRegistry.addAll(moduleRequires);
		return moduleRequires;
	}

	static function requirePreludeStatements(registry:Null<RequireRegistry>):Array<RubyStatement> {
		if (registry == null) {
			return [];
		}
		var out:Array<RubyStatement> = [];
		for (value in registry.requireValues()) {
			out.push(RubyRawStatement("require " + quoteRubyStringForCode(value)));
		}
		for (value in registry.requireRelativeValues()) {
			out.push(RubyRawStatement("require_relative " + quoteRubyStringForCode(value)));
		}
		return out;
	}

	static function wrapInModules(pack:Array<String>, statement:RubyStatement):RubyStatement {
		if (pack == null || pack.length == 0) {
			return statement;
		}
		var wrapped = statement;
		var i = pack.length - 1;
		while (i >= 0) {
			wrapped = RubyModuleDecl(rubyConstantName(pack[i]), [wrapped]);
			i -= 1;
		}
		return wrapped;
	}

	static function fullTypeName(pack:Array<String>, name:String):String {
		if (pack == null || pack.length == 0) {
			return name;
		}
		return pack.concat([name]).join(".");
	}

	static function rubyConstantName(raw:String):String {
		return RubyNaming.toConstantName(raw);
	}

	static function compileMethod(field:ClassFuncData):RubyStatement {
		var name = RubyNaming.toMethodName(field.field.name);
		if (field.isStatic) {
			name = "self." + name;
		}
		var args = [for (arg in field.args) RubyNaming.toLocalName(arg.getName())];
		return RubyMethodDecl(name, args, compileFunctionBody(field.expr));
	}

	static function compileVarField(field:ClassVarData):RubyStatement {
		var name = RubyNaming.toLocalName(field.field.name);
		if (!field.isStatic) {
			return RubyRawStatement("attr_accessor :" + name);
		}
		var init = field.findDefaultExpr();
		var initExpr = init == null ? compileUntypedConst(field.getDefaultUntypedExpr()) : compileExpr(init);
		return RubyRawStatement("class << self\n  attr_accessor :" + name + "\nend\n@" + name + " = "
			+ reflaxe.ruby.ast.RubyASTPrinter.printExpr(initExpr));
	}

	static function compileEnumBody(options:Array<EnumOptionData>):Array<RubyStatement> {
		var out:Array<RubyStatement> = [];
		var index = 0;
		for (option in options) {
			var ctorName = RubyNaming.toConstantName(option.name);
			var methodName = RubyNaming.toMethodName(option.name);
			var argNames = [for (arg in option.args) RubyNaming.toLocalName(arg.name)];
			var dataFields = argNames.concat(["__hx_tag", "__hx_index"]);
			out.push(RubyRawStatement(ctorName + " = Data.define(" + [for (name in dataFields) ":" + name].join(", ") + ")"));
			var ctorArgs = argNames.concat([quoteRubyStringForCode(option.name), Std.string(index)]);
			out.push(RubyRawStatement("def self." + methodName + "(" + argNames.join(", ") + ")\n  " + ctorName + ".new(" + ctorArgs.join(", ") + ")\nend"));
			index++;
		}
		if (out.length == 0) {
			out.push(RubyComment("empty enum"));
		}
		return out;
	}

	function setRubyOutputPath(pack:Array<String>, typeName:String):Void {
		setOutputFileName(RubyNaming.fileName(typeName));
		setOutputFileDir(outputRelativeDir(RubyNaming.fileDir(pack), !isStdRubyType(pack, typeName)));
		rememberRubyPath(pack, typeName);
	}

	function rememberRubyPath(pack:Array<String>, typeName:String):Void {
		var path = RubyNaming.fileName(typeName) + ".rb";
		var dir = outputRelativeDir(RubyNaming.fileDir(pack), !isStdRubyType(pack, typeName));
		if (dir != null && dir != "") {
			path = dir + "/" + path;
		}
		if (emittedRubyPaths.indexOf(path) == -1) {
			emittedRubyPaths.push(path);
		}
		if (!isStdRubyType(pack, typeName) && emittedAppRubyPaths.indexOf(path) == -1) {
			emittedAppRubyPaths.push(path);
		}
	}

	function compileRailsControllerImpl(classType:ClassType, varFields:Array<ClassVarData>, funcFields:Array<ClassFuncData>, moduleRequires:RequireRegistry):RubyFile {
		var body:Array<String> = [];
		for (field in varFields) {
			body = body.concat(renderStatements([compileVarField(field)]));
		}
		for (field in funcFields) {
			if (field.expr == null || hasMeta(field.field.meta, ":rubyExternStub")) {
				continue;
			}
			body = body.concat(renderStatements([compileMethod(field)]));
		}
		if (body.length == 0) {
			body.push("# Rails controller generated by reflaxe.ruby");
		}

		var lines = ["class " + RubyNaming.toConstantName(classType.name) + " < ActionController::Base"];
		for (line in body) {
			lines.push("  " + line);
		}
		lines.push("end");

		var statements:Array<RubyStatement> = [
			RubyComment("Generated by reflaxe.ruby"),
			RubyComment("Rails controller output; Zeitwerk path should match the Ruby constant.")
		];
		statements = statements.concat(requirePreludeStatements(moduleRequires));
		statements.push(wrapInModules(classType.pack, RubyRawStatement(lines.join("\n"))));
		return {
			modulePath: classType.pack == null ? [] : classType.pack.copy(),
			statements: statements
		};
	}

	function compileRailsModelImpl(classType:ClassType, varFields:Array<ClassVarData>, funcFields:Array<ClassFuncData>, moduleRequires:RequireRegistry):RubyFile {
		var body:Array<String> = [];
		var tableName = railsModelTableName(classType);
		if (tableName != null) {
			body.push("self.table_name = " + quoteRubyStringForCode(tableName));
		}
		for (field in varFields) {
			if (hasMeta(field.field.meta, ":belongsTo")) {
				body.push("belongs_to :" + RubyNaming.toMethodName(field.field.name));
			}
			if (hasMeta(field.field.meta, ":hasMany")) {
				body.push("has_many :" + RubyNaming.toMethodName(field.field.name));
			}
			if (hasMeta(field.field.meta, ":hasOne")) {
				body.push("has_one :" + RubyNaming.toMethodName(field.field.name));
			}
		}
		for (field in varFields) {
			if (hasMeta(field.field.meta, ":railsColumn")) {
				body.push("# haxe column " + RubyNaming.toMethodName(field.field.name) + ": " + typeLabel(field.field.type));
			}
		}
		for (field in varFields) {
			if (hasMeta(field.field.meta, ":validates")) {
				var options = validationOptions(field.field.meta);
				var suffix = options.length == 0 ? "" : ", " + options.join(", ");
				body.push("validates :" + validationTargetName(field) + suffix);
			}
		}
		for (field in funcFields) {
			if (field.expr == null || hasMeta(field.field.meta, ":rubyExternStub")) {
				continue;
			}
			body = body.concat(renderStatements([compileMethod(field)]));
		}
		if (body.length == 0) {
			body.push("# Rails model generated by reflaxe.ruby");
		}

		var lines = ["class " + RubyNaming.toConstantName(classType.name) + " < ActiveRecord::Base"];
		for (line in body) {
			lines.push("  " + line);
		}
		lines.push("end");

		var statements:Array<RubyStatement> = [
			RubyComment("Generated by reflaxe.ruby"),
			RubyComment("Rails model output; Zeitwerk path should match the Ruby constant.")
		];
		statements = statements.concat(requirePreludeStatements(moduleRequires));
		statements.push(wrapInModules(classType.pack, RubyRawStatement(lines.join("\n"))));
		return {
			modulePath: classType.pack == null ? [] : classType.pack.copy(),
			statements: statements
		};
	}

	static function isStdRubyType(pack:Array<String>, typeName:String):Bool {
		if (pack != null && pack.length > 0) {
			if (["_Any", "_EnumValue"].indexOf(pack[0]) != -1) {
				return true;
			}
			return pack[0] == "haxe" || pack[0] == "sys" || pack[0] == "ruby" || pack[0] == "rails";
		}
		return [
			"Any", "Bool", "Class", "Dynamic", "EReg", "Enum", "EnumValue", "Float", "IMap", "Int", "IntIterator", "Iterable", "Iterator",
			"KeyValueIterable", "KeyValueIterator", "Map", "Null", "StringBuf", "StringTools", "Std", "Sys", "Date", "Lambda", "ValueType", "Void"
		].indexOf(typeName) != -1;
	}

	static function hasStaticMain(funcFields:Array<ClassFuncData>):Bool {
		for (field in funcFields) {
			if (field.isStatic && field.field.name == "main") {
				return true;
			}
		}
		return false;
	}

	static function compileFunctionBody(expr:TypedExpr):Array<RubyStatement> {
		return switch (expr.expr) {
			case TBlock(exprs):
				compileStatementList(exprs);
			case _:
				[compileStatement(expr)];
		}
	}

	static function compileStatementList(exprs:Array<TypedExpr>):Array<RubyStatement> {
		var out = new Array<RubyStatement>();
		for (expr in exprs) {
			out.push(compileStatement(expr));
		}
		if (out.length == 0) {
			out.push(RubyNilStatement());
		}
		return out;
	}

	static function compileStatement(expr:TypedExpr):RubyStatement {
		if (expr == null) {
			return RubyExprStatement(RubyNil);
		}
		var special = compileSpecialStatement(expr);
		if (special != null) {
			return special;
		}
		switch (expr.expr) {
			case TBlock(exprs):
				return RubyRawStatement([for (stmt in compileStatementList(exprs)) statementToInlineRuby(stmt)].join("\n"));
			case TVar(v, init):
				return RubyAssign(RubyLocal(localName(v)), init == null ? RubyNil : compileExpr(init));
			case TBinop(OpAssign, lhs, rhs):
				return RubyAssign(compileAssignable(lhs), compileExpr(rhs));
			case TBinop(OpAssignOp(op), lhs, rhs):
				return RubyAssign(compileAssignable(lhs), RubyBinary(binopToRuby(op), compileExpr(lhs), compileExpr(rhs)));
			case TIf(cond, eThen, eElse):
				return RubyIfStmt(compileExpr(cond), compileFunctionBody(eThen), eElse == null ? null : compileFunctionBody(eElse));
			case TWhile(cond, body, _):
				return RubyWhileStmt(compileExpr(cond), compileFunctionBody(body));
			case TSwitch(switchExpr, cases, edef):
				return RubyRawStatement(renderSwitch(switchExpr, cases, edef));
			case TTry(tryExpr, catches):
				needsHxException = true;
				return RubyRawStatement(renderTry(tryExpr, catches));
			case TThrow(thrown):
				needsHxException = true;
				return RubyRawStatement("raise HxException.new(" + printInlineExpr(thrown) + ")");
			case TReturn(value):
				return RubyReturn(value == null ? null : compileExpr(value));
			case _:
				return RubyExprStatement(compileExpr(expr));
		}
	}

	static function compileExpr(expr:TypedExpr):RubyExpr {
		if (expr == null) {
			return RubyNil;
		}
		var special = compileSpecialExpr(expr);
		if (special != null) {
			return special;
		}
		return switch (expr.expr) {
			case TConst(TNull): RubyNil;
			case TConst(TBool(value)): RubyBool(value);
			case TConst(TInt(value)): RubyInt(Std.string(value));
			case TConst(TFloat(value)): RubyFloat(value);
			case TConst(TString(value)): RubyString(value);
			case TConst(TThis): RubyLocal("self");
			case TConst(TSuper): RubyLocal("super");
			case TLocal(v): RubyLocal(localName(v));
			case TArrayDecl(values): RubyArray([for (value in values) compileExpr(value)]);
			case TObjectDecl(fields): RubyHash([for (field in fields) {key: field.name, value: compileExpr(field.expr)}]);
			case TBinop(op, lhs, rhs): RubyBinary(binopToRuby(op), compileExpr(lhs), compileExpr(rhs));
			case TUnop(op, _, inner): RubyUnary(unopToRuby(op), compileExpr(inner));
			case TParenthesis(inner) | TMeta(_, inner) | TCast(inner, _): compileExpr(inner);
			case TFunction(fn):
				RubyLambda([for (arg in fn.args) RubyNaming.toLocalName(arg.v.name)], lambdaBody(fn.expr));
			case TBlock(exprs):
				RubyRawExpr("begin\n" + [for (stmt in compileStatementList(exprs)) "  " + statementToInlineRuby(stmt)].join("\n") + "\nend");
			case TIf(cond, eThen, eElse):
				RubyRawExpr("(if " + printInlineExpr(cond) + " then " + printInlineExpr(eThen) + " else " + (eElse == null ? "nil" : printInlineExpr(eElse)) + " end)");
			case TSwitch(switchExpr, cases, edef):
				RubyRawExpr(renderSwitch(switchExpr, cases, edef));
			case TTry(tryExpr, catches):
				needsHxException = true;
				RubyRawExpr(renderTry(tryExpr, catches));
			case TThrow(thrown):
				needsHxException = true;
				RubyRawExpr("(raise HxException.new(" + printInlineExpr(thrown) + "))");
			case TEnumIndex(enumExpr):
				RubyRawExpr(printInlineExpr(enumExpr) + ".__hx_index");
			case TCall({expr: TField(_, FEnum(enumRef, field))}, params):
				RubyCall(RubyLocal(RubyNaming.toConstantName(enumRef.get().name)), RubyNaming.toMethodName(field.name), [for (param in params) compileExpr(param)]);
			case TCall({expr: TField(target, access)}, params) if (isRubyInteropCall(access)):
				compileRubyInteropCall(target, access, params);
			case TCall({expr: TField(target, access)}, params):
				RubyCall(compileExpr(target), fieldAccessName(access), [for (param in params) compileExpr(param)]);
			case TCall({expr: TConst(TSuper)}, params):
				RubyCall(null, "super", [for (param in params) compileExpr(param)]);
			case TCall(callee, params):
				RubyCall(compileExpr(callee), "call", [for (param in params) compileExpr(param)]);
			case TField(_, FEnum(enumRef, field)):
				RubyCall(RubyLocal(RubyNaming.toConstantName(enumRef.get().name)), RubyNaming.toMethodName(field.name), []);
			case TField(target, access):
				RubyRawExpr(printInlineExpr(target) + "." + fieldAccessName(access));
			case TTypeExpr(moduleType):
				RubyLocal(moduleTypeName(moduleType));
			case _:
				RubyRawExpr("nil # TODO: unsupported expression " + Std.string(expr.expr));
		}
	}

	static function compileAssignable(expr:TypedExpr):RubyExpr {
		return switch (expr.expr) {
			case TLocal(v): RubyLocal(localName(v));
			case TField(target, access): RubyRawExpr(printInlineExpr(target) + "." + fieldAccessName(access));
			case _: RubyRawExpr(printInlineExpr(expr));
		}
	}

	static function compileUntypedConst(expr:Null<haxe.macro.Expr>):RubyExpr {
		if (expr == null) {
			return RubyNil;
		}
		return switch (expr.expr) {
			case EConst(CInt(value, _)): RubyInt(value);
			case EConst(CFloat(value, _)): RubyFloat(value);
			case EConst(CString(value, _)): RubyString(value);
			case EConst(CIdent("true")): RubyBool(true);
			case EConst(CIdent("false")): RubyBool(false);
			case EConst(CIdent("null")): RubyNil;
			case _: RubyNil;
		}
	}

	static function compileSpecialStatement(expr:TypedExpr):Null<RubyStatement> {
		return switch (expr.expr) {
			case TCall(callee, params):
				var special = compileSpecialCall(callee, params);
				special == null ? null : RubyExprStatement(special);
			case _:
				null;
		}
	}

	static function compileSpecialExpr(expr:TypedExpr):Null<RubyExpr> {
		return switch (expr.expr) {
			case TCall(callee, params):
				compileSpecialCall(callee, params);
			case _:
				null;
		}
	}

	static function compileSpecialCall(callee:TypedExpr, params:Array<TypedExpr>):Null<RubyExpr> {
		var info = staticCallInfo(callee);
		if (info == null) {
			return null;
		}
		if ((info.owner == "ruby.Symbol" || StringTools.endsWith(info.owner, ".Symbol_Impl_")) && info.name == "of") {
			return compileRubySymbol(params);
		}
		return switch [info.owner, info.name] {
			case ["Std", "string"]:
				RubyCall(RubyLocal("HXRuby"), "stringify", [compileParam(params, 0)]);
			case ["Std", "parseInt"]:
				RubyCall(RubyLocal("HXRuby"), "parse_int", [compileParam(params, 0)]);
			case ["Std", "parseFloat"]:
				RubyCall(RubyLocal("HXRuby"), "parse_float", [compileParam(params, 0)]);
			case ["Sys", "println"]:
				RubyCall(null, "puts", [RubyCall(RubyLocal("HXRuby"), "stringify", [compileParam(params, 0)])]);
			case ["Sys", "print"]:
				RubyCall(null, "print", [RubyCall(RubyLocal("HXRuby"), "stringify", [compileParam(params, 0)])]);
			case ["Sys", "args"]:
				RubyRawExpr("ARGV");
			case ["Sys", "getEnv"]:
				RubyRawExpr("ENV[" + printParam(params, 0) + "]");
			case ["Sys", "putEnv"]:
				RubyRawExpr("ENV[" + printParam(params, 0) + "] = " + printParam(params, 1));
			case ["Sys", "getCwd"]:
				RubyRawExpr("Dir.pwd");
			case ["Sys", "setCwd"]:
				RubyRawExpr("Dir.chdir(" + printParam(params, 0) + ")");
			case ["Sys", "time"]:
				RubyRawExpr("Time.now.to_f");
			case ["Sys", "systemName"]:
				RubyRawExpr("RUBY_PLATFORM");
			case ["Sys", "exit"]:
				RubyRawExpr("exit(" + printParam(params, 0) + ")");
			case ["StringTools", "trim"]:
				RubyCall(compileParam(params, 0), "strip", []);
			case ["StringTools", "ltrim"]:
				RubyCall(compileParam(params, 0), "lstrip", []);
			case ["StringTools", "rtrim"]:
				RubyCall(compileParam(params, 0), "rstrip", []);
			case ["StringTools", "replace"]:
				RubyCall(compileParam(params, 0), "gsub", [compileParam(params, 1), compileParam(params, 2)]);
			case ["StringTools", "startsWith"]:
				RubyCall(compileParam(params, 0), "start_with?", [compileParam(params, 1)]);
			case ["StringTools", "endsWith"]:
				RubyCall(compileParam(params, 0), "end_with?", [compileParam(params, 1)]);
			case ["StringTools", "contains"]:
				RubyCall(compileParam(params, 0), "include?", [compileParam(params, 1)]);
			case ["StringTools", "hex"]:
				RubyCall(RubyLocal("HXRuby"), "hex", [compileParam(params, 0), params.length > 1 ? compileExpr(params[1]) : RubyNil]);
			case ["StringTools", "urlEncode"]:
				RubyCall(RubyLocal("HXRuby"), "url_encode", [compileParam(params, 0)]);
			case ["StringTools", "urlDecode"]:
				RubyCall(RubyLocal("HXRuby"), "url_decode", [compileParam(params, 0)]);
			case _:
				null;
		}
	}

	static function compileRubyInteropCall(target:TypedExpr, access:haxe.macro.Type.FieldAccess, params:Array<TypedExpr>):RubyExpr {
		var receiver = reflaxe.ruby.ast.RubyASTPrinter.printExpr(compileExpr(target));
		var method = fieldAccessName(access);
		var remaining = params.copy();
		var block:Null<TypedExpr> = null;
		if (hasFieldAccessMeta(access, ":rubyBlockArg") && remaining.length > 0 && isFunctionExpr(remaining[remaining.length - 1])) {
			block = remaining.pop();
		}
		var keywordSource:Null<TypedExpr> = null;
		if (hasFieldAccessMeta(access, ":rubyKwargs") && remaining.length > 0 && isObjectDeclExpr(remaining[remaining.length - 1])) {
			keywordSource = remaining.pop();
		}
		var args = [for (param in remaining) printInlineExpr(param)];
		if (keywordSource != null) {
			args = args.concat(renderKeywordArgs(keywordSource));
		}
		var code = receiver + "." + method + "(" + args.join(", ") + ")";
		if (block != null) {
			code += " " + renderRubyBlock(block);
		}
		return RubyRawExpr(code);
	}

	static function compileRubySymbol(params:Array<TypedExpr>):RubyExpr {
		if (params.length == 0) {
			return RubyRawExpr(":\"\"");
		}
		return switch (params[0].expr) {
			case TConst(TString(value)):
				RubyRawExpr(rubySymbolLiteral(value));
			case _:
				RubyRawExpr("(" + printParam(params, 0) + ").to_sym");
		}
	}

	static function renderKeywordArgs(expr:TypedExpr):Array<String> {
		return switch (expr.expr) {
			case TObjectDecl(fields):
				[for (field in fields) RubyNaming.toMethodName(field.name) + ": " + printInlineExpr(field.expr)];
			case _:
				[printInlineExpr(expr)];
		}
	}

	static function renderRubyBlock(expr:TypedExpr):String {
		return switch (expr.expr) {
			case TFunction(fn):
				var args = [for (arg in fn.args) RubyNaming.toLocalName(arg.v.name)].join(", ");
				var body = renderStatements(compileFunctionBody(fn.expr));
				if (canRenderInlineBlock(body)) {
					var prefix = args == "" ? "" : "|" + args + "| ";
					"{ " + prefix + body[0] + " }";
				} else {
					var lines = [args == "" ? "do" : "do |" + args + "|"];
					appendIndentedLines(lines, body, 1);
					lines.push("end");
					lines.join("\n");
				}
			case _:
			"{ |value| " + printInlineExpr(expr) + ".call(value) }";
		}
	}

	static function canRenderInlineBlock(body:Array<String>):Bool {
		if (body.length != 1) {
			return false;
		}
		var line = body[0];
		return line.indexOf("\n") == -1 && !StringTools.startsWith(StringTools.trim(line), "return");
	}

	static function isRubyInteropCall(access:haxe.macro.Type.FieldAccess):Bool {
		return hasFieldAccessMeta(access, ":rubyKwargs") || hasFieldAccessMeta(access, ":rubyBlockArg");
	}

	static function isFunctionExpr(expr:TypedExpr):Bool {
		return switch (expr.expr) {
			case TFunction(_): true;
			case _: false;
		}
	}

	static function isObjectDeclExpr(expr:TypedExpr):Bool {
		return switch (expr.expr) {
			case TObjectDecl(_): true;
			case _: false;
		}
	}

	static function staticCallInfo(callee:TypedExpr):Null<{owner:String, name:String}> {
		return switch (callee.expr) {
			case TField(_, FStatic(classRef, fieldRef)):
				var classType = classRef.get();
				{owner: fullTypeName(classType.pack, classType.name), name: fieldRef.get().name};
			case _:
				null;
		}
	}

	static function compileParam(params:Array<TypedExpr>, index:Int):RubyExpr {
		return index < params.length ? compileExpr(params[index]) : RubyNil;
	}

	static function printParam(params:Array<TypedExpr>, index:Int):String {
		return reflaxe.ruby.ast.RubyASTPrinter.printExpr(compileParam(params, index));
	}

	static function renderSwitch(switchExpr:TypedExpr, cases:Array<{values:Array<TypedExpr>, expr:TypedExpr}>, edef:Null<TypedExpr>):String {
		var usesEnumIndex = switch (switchExpr.expr) {
			case TEnumIndex(_): true;
			case _: false;
		}
		var lines = ["case " + switchScrutineeCode(switchExpr)];
		for (branch in cases) {
			var values = [for (value in branch.values) switchValueCode(value, usesEnumIndex)];
			lines.push("when " + values.join(", "));
			appendIndentedLines(lines, renderStatements(compileFunctionBody(branch.expr)), 1);
		}
		if (edef != null) {
			lines.push("else");
			appendIndentedLines(lines, renderStatements(compileFunctionBody(edef)), 1);
		}
		lines.push("end");
		return lines.join("\n");
	}

	static function renderTry(tryExpr:TypedExpr, catches:Array<{v:TVar, expr:TypedExpr}>):String {
		var lines = ["begin"];
		appendIndentedLines(lines, renderStatements(compileFunctionBody(tryExpr)), 1);
		if (catches.length > 0) {
			var first = catches[0];
			lines.push("rescue HxException => __hx_ex");
			lines.push("  " + RubyNaming.toLocalName(first.v.name) + " = __hx_ex.value");
			appendIndentedLines(lines, renderStatements(compileFunctionBody(first.expr)), 1);
		}
		lines.push("end");
		return lines.join("\n");
	}

	static function switchScrutineeCode(expr:TypedExpr):String {
		return switch (expr.expr) {
			case TEnumIndex(enumExpr):
				printInlineExpr(enumExpr) + ".__hx_index";
			case _:
				printInlineExpr(expr);
		}
	}

	static function switchValueCode(expr:TypedExpr, usesEnumIndex:Bool):String {
		if (usesEnumIndex) {
			return printInlineExpr(expr);
		}
		return switch (expr.expr) {
			case TField(_, FEnum(_, field)):
				quoteRubyStringForCode(field.name);
			case _:
				printInlineExpr(expr);
		}
	}

	static function renderStatements(statements:Array<RubyStatement>):Array<String> {
		var file = {
			modulePath: [],
			statements: statements
		};
		var printed = reflaxe.ruby.ast.RubyASTPrinter.printFile(file).split("\n");
		if (printed.length > 0 && printed[printed.length - 1] == "") {
			printed.pop();
		}
		return printed;
	}

	static function appendIndentedLines(target:Array<String>, lines:Array<String>, indentLevel:Int):Void {
		var indent = "";
		for (_ in 0...indentLevel) {
			indent += "  ";
		}
		for (line in lines) {
			target.push(indent + line);
		}
	}

	function setRuntimeExtraFile(name:String):Void {
		setExtraFile(OutputPath.fromStr(outputRelativePath("hxruby/" + name, true)), runtimeFileContent(name));
	}

	function setRailsAutoloadInitializer():Void {
		var root = buildContext.railsOutputRoot;
		var lines = [
			"# Generated by reflaxe.ruby",
			"hxruby_root = Rails.root.join(" + quoteRubyStringForCode(root) + ")",
			"Rails.application.config.autoload_paths << hxruby_root",
			"Rails.application.config.eager_load_paths << hxruby_root",
			""
		];
		setExtraFile(OutputPath.fromStr("config/initializers/hxruby_autoload.rb"), lines.join("\n"));
	}

	function outputRelativeDir(dir:Null<String>, appOwned:Bool):Null<String> {
		var normalized = dir == null ? "" : dir;
		if (buildContext.railsMode && appOwned) {
			return normalized == "" ? buildContext.railsOutputRoot : buildContext.railsOutputRoot + "/" + normalized;
		}
		return normalized == "" ? null : normalized;
	}

	function outputRelativePath(path:String, runtimeOwned:Bool):String {
		if (buildContext.railsMode && runtimeOwned) {
			return buildContext.railsOutputRoot + "/" + path;
		}
		return path;
	}

	static function runtimeFileContent(name:String):String {
		var path = Path.join([findLibraryRoot(), "runtime", "hxruby", name]);
		if (!FileSystem.exists(path)) {
			Context.fatalError("Missing hxruby runtime file: " + path, Context.currentPos());
		}
		return File.getContent(path);
	}

	static function findLibraryRoot():String {
		var compilerPath = Context.resolvePath("reflaxe/ruby/RubyCompiler.hx");
		return Path.normalize(Path.join([Path.directory(compilerPath), "..", "..", ".."]));
	}

	static function isSysPrintCall(callee:TypedExpr):Bool {
		return switch (callee.expr) {
			case TField(_, FStatic(_, field)) | TField(_, FInstance(_, _, field)):
				var name = field.get().name;
				name == "print" || name == "println";
			case TField(_, FAnon(fieldRef)) | TField(_, FClosure(_, fieldRef)):
				var field = fieldRef.get();
				field.name == "print" || field.name == "println";
			case _:
				false;
		}
	}

	static function fieldAccessName(access:haxe.macro.Type.FieldAccess):String {
		return switch (access) {
			case FInstance(_, _, field) | FStatic(_, field): rubyFieldName(field.get().name, field.get().meta);
			case FAnon(fieldRef) | FClosure(_, fieldRef): rubyFieldName(fieldRef.get().name, fieldRef.get().meta);
			case FDynamic(name): RubyNaming.toMethodName(name);
			case FEnum(_, field): rubyFieldName(field.name, field.meta);
		}
	}

	static function hasFieldAccessMeta(access:haxe.macro.Type.FieldAccess, name:String):Bool {
		var meta = switch (access) {
			case FInstance(_, _, field) | FStatic(_, field): field.get().meta;
			case FAnon(fieldRef) | FClosure(_, fieldRef): fieldRef.get().meta;
			case FEnum(_, field): field.meta;
			case FDynamic(_): null;
		}
		return hasMeta(meta, name);
	}

	static function moduleTypeName(moduleType:ModuleType):String {
		return switch (moduleType) {
			case TClassDecl(classRef):
				var classType = classRef.get();
				rubyNativeName(classType.meta) ?? rubyConstantPath(classType.pack, classType.name);
			case TEnumDecl(enumRef):
				var enumType = enumRef.get();
				rubyNativeName(enumType.meta) ?? rubyConstantPath(enumType.pack, enumType.name);
			case TTypeDecl(typeRef):
				var defType = typeRef.get();
				rubyNativeName(defType.meta) ?? rubyConstantPath(defType.pack, defType.name);
			case TAbstract(abstractRef):
				var abstractType = abstractRef.get();
				rubyNativeName(abstractType.meta) ?? rubyConstantPath(abstractType.pack, abstractType.name);
		}
	}

	static function rubyConstantPath(pack:Array<String>, name:String):String {
		var parts = RubyNaming.modulePath(pack);
		parts.push(RubyNaming.toConstantName(name));
		return parts.join("::");
	}

	static function rubyFieldName(name:String, meta:Null<haxe.macro.Type.MetaAccess>):String {
		return rubyNativeName(meta) ?? RubyNaming.toMethodName(name);
	}

	static function rubyNativeName(meta:Null<haxe.macro.Type.MetaAccess>):Null<String> {
		if (meta == null || meta.extract == null) {
			return null;
		}
		var entries = meta.extract(":native");
		if (entries.length == 0) {
			return null;
		}
		var entry = entries[0];
		if (entry.params == null || entry.params.length == 0) {
			return null;
		}
		return switch (entry.params[0].expr) {
			case EConst(CString(value, _)) if (value.length > 0): value;
			case EConst(CIdent(value)) if (value.length > 0): value;
			case _: null;
		}
	}

	static function hasMeta(meta:Null<haxe.macro.Type.MetaAccess>, name:String):Bool {
		return meta != null && meta.has != null && meta.has(name);
	}

	static function railsModelTableName(classType:ClassType):Null<String> {
		var explicit = metaStringValue(classType.meta, ":railsModel");
		if (explicit != null) {
			return explicit;
		}
		return RubyNaming.fileName(classType.name) + "s";
	}

	static function metaStringValue(meta:Null<haxe.macro.Type.MetaAccess>, name:String):Null<String> {
		if (meta == null || meta.extract == null) {
			return null;
		}
		var entries = meta.extract(name);
		if (entries.length == 0 || entries[0].params == null || entries[0].params.length == 0) {
			return null;
		}
		return switch (entries[0].params[0].expr) {
			case EConst(CString(value, _)) if (value.length > 0): value;
			case _: null;
		}
	}

	static function validationTargetName(field:ClassVarData):String {
		var explicit = metaStringValue(field.field.meta, ":validates");
		if (explicit != null) {
			return RubyNaming.toMethodName(explicit);
		}
		var name = field.field.name;
		var suffix = "Validation";
		if (StringTools.endsWith(name, suffix) && name.length > suffix.length) {
			name = name.substr(0, name.length - suffix.length);
		}
		return RubyNaming.toMethodName(name);
	}

	static function validationOptions(meta:Null<haxe.macro.Type.MetaAccess>):Array<String> {
		if (meta == null || meta.extract == null) {
			return [];
		}
		var entries = meta.extract(":validates");
		if (entries.length == 0 || entries[0].params == null || entries[0].params.length == 0) {
			return [];
		}
		var params = entries[0].params;
		var options = switch (params[0].expr) {
			case EObjectDecl(_): params[0];
			case _ if (params.length > 1): params[1];
			case _: null;
		}
		return options == null ? [] : metadataObjectOptions(options);
	}

	static function metadataObjectOptions(expr:haxe.macro.Expr):Array<String> {
		return switch (expr.expr) {
			case EObjectDecl(fields):
				[for (field in fields) RubyNaming.toMethodName(field.field) + ": " + metadataValueCode(field.expr)];
			case _:
				[];
		}
	}

	static function metadataValueCode(expr:haxe.macro.Expr):String {
		return switch (expr.expr) {
			case EConst(CIdent("true")): "true";
			case EConst(CIdent("false")): "false";
			case EConst(CIdent("null")): "nil";
			case EConst(CString(value, _)): quoteRubyStringForCode(value);
			case EConst(CInt(value, _)): value;
			case EConst(CFloat(value, _)): value;
			case EArrayDecl(values): "[" + [for (value in values) metadataValueCode(value)].join(", ") + "]";
			case EObjectDecl(fields): "{" + [for (field in fields) RubyNaming.toMethodName(field.field) + ": " + metadataValueCode(field.expr)].join(", ") + "}";
			case _: "nil";
		}
	}

	static function typeLabel(type:haxe.macro.Type):String {
		return switch (type) {
			case TAbstract(ref, _): ref.get().name;
			case TInst(ref, _): ref.get().name;
			case TEnum(ref, _): ref.get().name;
			case TType(ref, _): ref.get().name;
			case TDynamic(_): "Dynamic";
			case TFun(_, _): "Function";
			case TAnonymous(_): "Anonymous";
			case TLazy(lazy): typeLabel(lazy());
			case TMono(_): "Unknown";
		}
	}

	static function rubySymbolLiteral(value:String):String {
		if (isSimpleRubySymbol(value)) {
			return ":" + value;
		}
		var escaped = value == null ? "" : value;
		escaped = StringTools.replace(escaped, "\\", "\\\\");
		escaped = StringTools.replace(escaped, "\"", "\\\"");
		return ":\"" + escaped + "\"";
	}

	static function isSimpleRubySymbol(value:String):Bool {
		if (value == null || value.length == 0) {
			return false;
		}
		var first = value.charCodeAt(0);
		if (!isRubyIdentStart(first)) {
			return false;
		}
		var limit = value.length;
		var last = value.charAt(value.length - 1);
		if (last == "!" || last == "?" || last == "=") {
			limit--;
		}
		for (i in 1...limit) {
			if (!isRubyIdentPart(value.charCodeAt(i))) {
				return false;
			}
		}
		return true;
	}

	static function isRubyIdentStart(code:Int):Bool {
		return code == 95 || (code >= 65 && code <= 90) || (code >= 97 && code <= 122);
	}

	static function isRubyIdentPart(code:Int):Bool {
		return isRubyIdentStart(code) || (code >= 48 && code <= 57);
	}

	static function localName(v:TVar):String {
		return RubyNaming.toLocalName(v.name);
	}

	static function binopToRuby(op:haxe.macro.Expr.Binop):String {
		return switch (op) {
			case OpAdd: "+";
			case OpSub: "-";
			case OpMult: "*";
			case OpDiv: "/";
			case OpMod: "%";
			case OpEq: "==";
			case OpNotEq: "!=";
			case OpGt: ">";
			case OpGte: ">=";
			case OpLt: "<";
			case OpLte: "<=";
			case OpBoolAnd: "&&";
			case OpBoolOr: "||";
			case OpAnd: "&";
			case OpOr: "|";
			case OpXor: "^";
			case OpShl: "<<";
			case OpShr | OpUShr: ">>";
			case OpAssign: "=";
			case OpAssignOp(inner): binopToRuby(inner);
			case _: "+";
		}
	}

	static function unopToRuby(op:haxe.macro.Expr.Unop):String {
		return switch (op) {
			case OpNot: "!";
			case OpNeg | OpNegBits: "-";
			case OpIncrement | OpDecrement: "";
			case _: "";
		}
	}

	static function printInlineExpr(expr:TypedExpr):String {
		return reflaxe.ruby.ast.RubyASTPrinter.printExpr(compileExpr(expr));
	}

	static function lambdaBody(expr:TypedExpr):String {
		return switch (expr.expr) {
			case TReturn(value):
				value == null ? "nil" : printInlineExpr(value);
			case TBlock(exprs) if (exprs.length > 0):
				lambdaBody(exprs[exprs.length - 1]);
			case _:
				printInlineExpr(expr);
		}
	}

	static function quoteRubyStringForCode(value:String):String {
		var escaped = value == null ? "" : value;
		escaped = StringTools.replace(escaped, "\\", "\\\\");
		escaped = StringTools.replace(escaped, "\"", "\\\"");
		return "\"" + escaped + "\"";
	}

	static function statementToInlineRuby(statement:RubyStatement):String {
		return switch (statement) {
			case RubyExprStatement(expr): reflaxe.ruby.ast.RubyASTPrinter.printExpr(expr);
			case RubyAssign(target, value): reflaxe.ruby.ast.RubyASTPrinter.printExpr(target) + " = " + reflaxe.ruby.ast.RubyASTPrinter.printExpr(value);
			case RubyReturn(value): value == null ? "return" : "return " + reflaxe.ruby.ast.RubyASTPrinter.printExpr(value);
			case RubyRawStatement(code): code;
			case RubyComment(text): "# " + text;
			case _: "# TODO: inline statement";
		}
	}

	static function RubyNilStatement():RubyStatement {
		return RubyExprStatement(RubyNil);
	}
}
#else
class RubyCompiler {
	public function new() {}
}
#end
