package reflaxe.ruby;

#if (macro || reflaxe_runtime)
import haxe.io.Path;
import haxe.macro.Context;
import haxe.macro.Type.AbstractType;
import haxe.macro.Type.ClassType;
import haxe.macro.Type.DefType;
import haxe.macro.Type.EnumType;
import haxe.macro.Type.FieldAccess;
import haxe.macro.Type.ModuleType;
import haxe.macro.Type.TypedExpr;
import haxe.macro.Type.TVar;
import reflaxe.GenericCompiler;
import reflaxe.data.ClassFuncData;
import reflaxe.data.ClassVarData;
import reflaxe.data.EnumOptionData;
import reflaxe.output.DataAndFileInfo;
import reflaxe.output.OutputPath;
import reflaxe.output.StringOrBytes;
import reflaxe.ruby.ast.RubyAST.RubyExpr;
import reflaxe.ruby.ast.RubyAST.RubyFile;
import reflaxe.ruby.ast.RubyAST.RubyStatement;
import reflaxe.ruby.compiler.RubyBuildContext;
import reflaxe.ruby.compiler.RubyBuildContextResolver;
import reflaxe.ruby.naming.RubyNaming;
import reflaxe.ruby.RequireRegistry;
import sys.FileSystem;
import sys.io.File;

typedef RailsColumnInfo = {
	haxeName:String,
	rubyName:String,
	haxeType:String,
	railsType:String,
	nullable:Bool,
	defaultValue:Null<String>,
	primaryKey:Bool,
	index:Bool,
	unique:Bool,
	dbType:Null<String>
}

typedef RubyMetadataField = {
	field:String,
	expr:haxe.macro.Expr
}

typedef RailsTemplateScope = {
	localNames:Map<Int, String>,
	localObjectNames:Map<Int, String>,
	?formBuilderName:String
}

class RubyCompiler extends GenericCompiler<RubyFile, RubyFile, RubyExpr, RubyFile, RubyFile> {
	public var currentCompilationContext:Null<CompilationContext>;
	var emittedRubyPaths:Array<String> = [];
	var emittedAppRubyPaths:Array<String> = [];
	var requireRegistry:RequireRegistry = new RequireRegistry();
	var buildContext:RubyBuildContext;
	var didEmitMain:Bool = false;
	static var needsDataDefine:Bool = false;
	static var needsHxException:Bool = false;

	public function new() {
		super();
		buildContext = RubyBuildContextResolver.resolve();
	}

	public function createCompilationContext():CompilationContext {
		return CompilationContext.fromBuildContext(RubyBuildContextResolver.resolve());
	}

	public function generateOutputIterator():Iterator<DataAndFileInfo<StringOrBytes>> {
		return new RubyOutputIterator(this);
	}

	override public function onCompileStart():Void {
		buildContext = RubyBuildContextResolver.resolve();
		emittedRubyPaths = [];
		emittedAppRubyPaths = [];
		requireRegistry = new RequireRegistry();
		didEmitMain = false;
		needsDataDefine = false;
		needsHxException = false;
	}

	override public function onCompileEnd():Void {
		if (buildContext.railsMode) {
			setRailsAutoloadInitializer();
		}
		if (!didEmitMain) {
			return;
		}
		setRuntimeExtraFile("core.rb");
		if (needsDataDefine) {
			setRuntimeExtraFile("data_define.rb");
		}
		if (needsHxException) {
			setRuntimeExtraFile("hx_exception.rb");
		}
		var paths = [outputRelativePath("hxruby/core.rb", true)];
		if (needsDataDefine) {
			paths.push(outputRelativePath("hxruby/data_define.rb", true));
		}
		if (needsHxException) {
			paths.push(outputRelativePath("hxruby/hx_exception.rb", true));
		}
		var generatedPaths = emittedRubyPaths.copy();
		generatedPaths.sort((a, b) -> {
			if (a == "main.rb") return 1;
			if (b == "main.rb") return -1;
			return Reflect.compare(a, b);
		});
		paths = paths.concat(generatedPaths);
		var lines = ["# Generated by reflaxe.ruby", "$LOAD_PATH.unshift(__dir__)"];
		for (value in requireRegistry.requireValues()) {
			lines.push("require " + quoteRubyStringForCode(value));
		}
		for (value in requireRegistry.requireRelativeValues()) {
			lines.push("require_relative " + quoteRubyStringForCode(value));
		}
		for (path in paths) {
			lines.push("require_relative " + quoteRubyStringForCode(path.substr(0, path.length - 3)));
		}
		lines.push("Main.main");
		lines.push("");
		setExtraFile(OutputPath.fromStr("run.rb"), lines.join("\n"));
	}

	public function compileClassImpl(classType:ClassType, varFields:Array<ClassVarData>, funcFields:Array<ClassFuncData>):Null<RubyFile> {
		setRubyOutputPath(classType.pack, classType.name);
		var moduleRequires = collectModuleRequires(classType.meta);
		if (hasMeta(classType.meta, ":railsTemplate")) {
			return compileRailsTemplateImpl(classType, varFields, funcFields, moduleRequires);
		}
		if (hasMeta(classType.meta, ":railsModel")) {
			requireRegistry.addRequire("active_record");
			moduleRequires.addRequire("active_record");
			return compileRailsModelImpl(classType, varFields, funcFields, moduleRequires);
		}
		if (hasMeta(classType.meta, ":railsController")) {
			requireRegistry.addRequire("action_controller/railtie");
			moduleRequires.addRequire("action_controller/railtie");
			return compileRailsControllerImpl(classType, varFields, funcFields, moduleRequires);
		}
		var classBody:Array<RubyStatement> = [];
		classBody.push(typeNameMetadata(fullTypeName(classType.pack, classType.name)));
		for (field in varFields) {
			var mathConstant = mathConstantValue(classType.pack, classType.name, field.field.name);
			classBody.push(mathConstant == null ? compileVarField(field) : compileMathConstantField(field.field.name, mathConstant));
		}
		for (field in funcFields) {
			if (field.expr == null) {
				continue;
			}
			if (hasMeta(field.field.meta, ":rubyExternStub")) {
				continue;
			}
			classBody.push(compileMethod(field));
		}
		if (classBody.length == 0) {
			classBody.push(RubyComment("No Ruby members emitted for " + fullTypeName(classType.pack, classType.name)));
		}

		var statements = [
			RubyComment("Generated by reflaxe.ruby"),
			RubyComment("Generated type shell for Ruby output.")
		];
		statements = statements.concat(requirePreludeStatements(moduleRequires));
		statements.push(wrapInModules(classType.pack, rubyClassDeclaration(classType, classBody)));

		if (classType.pack.length == 0 && classType.name == "Main" && hasStaticMain(funcFields)) {
			didEmitMain = true;
			statements.push(RubyRawStatement("if __FILE__ == $PROGRAM_NAME\n  $LOAD_PATH.unshift(__dir__)\n  require_relative \"hxruby/core\"\n  Main.main()\nend"));
		}

		return {
			modulePath: classType.pack == null ? [] : classType.pack.copy(),
			statements: statements
		};
	}

	public function compileEnumImpl(enumType:EnumType, options:Array<EnumOptionData>):Null<RubyFile> {
		setRubyOutputPath(enumType.pack, enumType.name);
		var moduleRequires = collectModuleRequires(enumType.meta);
		needsDataDefine = true;
		var statements = [
			RubyComment("Generated by reflaxe.ruby"),
			RubyComment("Enum constructors use hxruby/data_define.rb for Data.define compatibility.")
		];
		statements = statements.concat(requirePreludeStatements(moduleRequires));
		statements.push(wrapInModules(enumType.pack, RubyModuleDecl(RubyNaming.toConstantName(enumType.name), compileEnumBody(enumType, options))));
		return {
			modulePath: enumType.pack == null ? [] : enumType.pack.copy(),
			statements: statements
		};
	}

	public function compileExpressionImpl(expr:TypedExpr, topLevel:Bool):Null<RubyExpr> {
		return compileExpr(expr);
	}

	override public function compileTypedefImpl(typedefType:DefType):Null<RubyFile> {
		setRubyOutputPath(typedefType.pack, typedefType.name);
		return typeShell(typedefType.pack, typedefType.name, RubyModuleDecl(RubyNaming.toConstantName(typedefType.name), [
			RubyComment("Haxe typedef " + fullTypeName(typedefType.pack, typedefType.name) + " has no Ruby runtime body.")
		]), collectModuleRequires(typedefType.meta));
	}

	override public function compileAbstractImpl(abstractType:AbstractType):Null<RubyFile> {
		setRubyOutputPath(abstractType.pack, abstractType.name);
		return typeShell(abstractType.pack, abstractType.name, RubyModuleDecl(RubyNaming.toConstantName(abstractType.name), [
			RubyComment("Haxe abstract " + fullTypeName(abstractType.pack, abstractType.name) + " has no Ruby runtime body.")
		]), collectModuleRequires(abstractType.meta));
	}

	function compileRailsTemplateImpl(classType:ClassType, varFields:Array<ClassVarData>, funcFields:Array<ClassFuncData>,
			moduleRequires:RequireRegistry):RubyFile {
		emitRailsTemplateArtifact(classType, varFields, funcFields);
		return typeShell(classType.pack, classType.name, RubyClassDecl(RubyNaming.toConstantName(classType.name), [
			RubyComment("Rails ActionView template marker. The ERB artifact is generated under app/views.")
		]), moduleRequires);
	}

	static function typeShell(pack:Array<String>, name:String, declaration:RubyStatement, ?moduleRequires:RequireRegistry):RubyFile {
		var statements:Array<RubyStatement> = [
			RubyComment("Generated by reflaxe.ruby"),
			RubyComment("Generated type shell for Ruby output.")
		];
		statements = statements.concat(requirePreludeStatements(moduleRequires));
		statements.push(wrapInModules(pack, declaration));
		return {
			modulePath: pack == null ? [] : pack.copy(),
			statements: statements
		};
	}

	static function rubyClassDeclaration(classType:ClassType, body:Array<RubyStatement>):RubyStatement {
		var constant = RubyNaming.toConstantName(classType.name);
		if (fullTypeName(classType.pack, classType.name) == "Math") {
			return RubyModuleDecl(constant, body);
		}
		return RubyClassDecl(constant, body);
	}

	function collectModuleRequires(meta:Null<haxe.macro.Type.MetaAccess>):RequireRegistry {
		var moduleRequires = new RequireRegistry();
		moduleRequires.collectMeta(meta);
		moduleRequires.collectTypeUsage(getTypeUsage());
		requireRegistry.addAll(moduleRequires);
		return moduleRequires;
	}

	static function requirePreludeStatements(registry:Null<RequireRegistry>):Array<RubyStatement> {
		if (registry == null) {
			return [];
		}
		var out:Array<RubyStatement> = [];
		for (value in registry.requireValues()) {
			out.push(RubyRawStatement("require " + quoteRubyStringForCode(value)));
		}
		for (value in registry.requireRelativeValues()) {
			out.push(RubyRawStatement("require_relative " + quoteRubyStringForCode(value)));
		}
		return out;
	}

	static function wrapInModules(pack:Array<String>, statement:RubyStatement):RubyStatement {
		if (pack == null || pack.length == 0) {
			return statement;
		}
		var wrapped = statement;
		var i = pack.length - 1;
		while (i >= 0) {
			wrapped = RubyModuleDecl(rubyConstantName(pack[i]), [wrapped]);
			i -= 1;
		}
		return wrapped;
	}

	static function fullTypeName(pack:Array<String>, name:String):String {
		if (pack == null || pack.length == 0) {
			return name;
		}
		return pack.concat([name]).join(".");
	}

	static function rubyConstantName(raw:String):String {
		return RubyNaming.toConstantName(raw);
	}

	static function compileMethod(field:ClassFuncData):RubyStatement {
		var name = RubyNaming.toMethodName(field.field.name);
		if (!field.isStatic && field.field.name == "new") {
			name = "initialize";
		}
		if (field.isStatic) {
			name = "self." + name;
		}
		var args = [for (arg in field.args) arg.tvar == null ? RubyNaming.toLocalName(arg.getName()) : localName(arg.tvar)];
		return RubyMethodDecl(name, args, compileFunctionBody(field.expr));
	}

	static function compileVarField(field:ClassVarData):RubyStatement {
		var name = RubyNaming.toLocalName(field.field.name);
		if (!field.isStatic) {
			return RubyRawStatement("attr_accessor :" + name);
		}
		var init = field.findDefaultExpr();
		var initExpr = init == null ? compileUntypedConst(field.getDefaultUntypedExpr()) : compileExpr(init);
		return RubyRawStatement("class << self\n  attr_accessor :" + name + "\nend\n@" + name + " = "
			+ reflaxe.ruby.ast.RubyASTPrinter.printExpr(initExpr));
	}

	static function compileMathConstantField(name:String, value:String):RubyStatement {
		return RubyRawStatement("def self." + RubyNaming.toMethodName(name) + "()\n  " + value + "\nend");
	}

	static function mathConstantValue(pack:Array<String>, typeName:String, fieldName:String):Null<String> {
		if (fullTypeName(pack, typeName) != "Math") {
			return null;
		}
		return switch (fieldName) {
			case "PI": "::Math::PI";
			case "NEGATIVE_INFINITY": "-Float::INFINITY";
			case "POSITIVE_INFINITY": "Float::INFINITY";
			case "NaN": "Float::NAN";
			case _: null;
		}
	}

	static function typeNameMetadata(name:String):RubyStatement {
		return RubyRawStatement("def self.__hx_name()\n  " + quoteRubyStringForCode(name) + "\nend");
	}

	static function compileEnumBody(enumType:EnumType, options:Array<EnumOptionData>):Array<RubyStatement> {
		var out:Array<RubyStatement> = [typeNameMetadata(fullTypeName(enumType.pack, enumType.name))];
		var index = 0;
		var metadata:Array<String> = [];
		for (option in options) {
			var ctorName = RubyNaming.toConstantName(option.name);
			var methodName = RubyNaming.toMethodName(option.name);
			var argNames = [for (arg in option.args) RubyNaming.toLocalName(arg.name)];
			metadata.push("{name: " + quoteRubyStringForCode(option.name) + ", index: " + Std.string(index) + ", method: " + rubySymbolLiteral(methodName)
				+ ", arity: " + Std.string(argNames.length) + "}");
			var dataFields = argNames.concat(["__hx_tag", "__hx_index"]);
			out.push(RubyRawStatement(ctorName + " = Data.define(" + [for (name in dataFields) ":" + name].join(", ") + ")"));
			var ctorArgs = argNames.concat([quoteRubyStringForCode(option.name), Std.string(index)]);
			out.push(RubyRawStatement("def self." + methodName + "(" + argNames.join(", ") + ")\n  " + ctorName + ".new(" + ctorArgs.join(", ") + ")\nend"));
			index++;
		}
		out.insert(1, RubyRawStatement("def self.__hx_constructs()\n  [" + metadata.join(", ") + "]\nend"));
		if (out.length == 0) {
			out.push(RubyComment("empty enum"));
		}
		return out;
	}

	function setRubyOutputPath(pack:Array<String>, typeName:String):Void {
		setOutputFileName(RubyNaming.fileName(typeName));
		setOutputFileDir(outputRelativeDir(RubyNaming.fileDir(pack), !isStdRubyType(pack, typeName)));
		rememberRubyPath(pack, typeName);
	}

	function rememberRubyPath(pack:Array<String>, typeName:String):Void {
		var path = RubyNaming.fileName(typeName) + ".rb";
		var dir = outputRelativeDir(RubyNaming.fileDir(pack), !isStdRubyType(pack, typeName));
		if (dir != null && dir != "") {
			path = dir + "/" + path;
		}
		if (emittedRubyPaths.indexOf(path) == -1) {
			emittedRubyPaths.push(path);
		}
		if (!isStdRubyType(pack, typeName) && emittedAppRubyPaths.indexOf(path) == -1) {
			emittedAppRubyPaths.push(path);
		}
	}

	function compileRailsControllerImpl(classType:ClassType, varFields:Array<ClassVarData>, funcFields:Array<ClassFuncData>, moduleRequires:RequireRegistry):RubyFile {
		var body:Array<String> = [];
		for (field in varFields) {
			body = body.concat(renderStatements([compileVarField(field)]));
		}
		for (field in funcFields) {
			if (field.expr == null || hasMeta(field.field.meta, ":rubyExternStub")) {
				continue;
			}
			body = body.concat(renderStatements([compileMethod(field)]));
		}
		if (body.length == 0) {
			body.push("# Rails controller generated by reflaxe.ruby");
		}

		var lines = ["class " + RubyNaming.toConstantName(classType.name) + " < ActionController::Base"];
		for (line in body) {
			lines.push("  " + line);
		}
		lines.push("end");

		var statements:Array<RubyStatement> = [
			RubyComment("Generated by reflaxe.ruby"),
			RubyComment("Rails controller output; Zeitwerk path should match the Ruby constant.")
		];
		statements = statements.concat(requirePreludeStatements(moduleRequires));
		statements.push(wrapInModules(classType.pack, RubyRawStatement(lines.join("\n"))));
		return {
			modulePath: classType.pack == null ? [] : classType.pack.copy(),
			statements: statements
		};
	}

	function compileRailsModelImpl(classType:ClassType, varFields:Array<ClassVarData>, funcFields:Array<ClassFuncData>, moduleRequires:RequireRegistry):RubyFile {
		var body:Array<String> = [];
		var tableName = railsModelTableName(classType);
		if (tableName != null) {
			body.push("self.table_name = " + quoteRubyStringForCode(tableName));
		}
		body = body.concat(railsSchemaRegistryLines(tableName, varFields, classType));
		for (field in varFields) {
			if (hasMeta(field.field.meta, ":belongsTo")) {
				body.push("belongs_to :" + RubyNaming.toMethodName(field.field.name));
			}
			if (hasMeta(field.field.meta, ":hasMany")) {
				body.push("has_many :" + RubyNaming.toMethodName(field.field.name));
			}
			if (hasMeta(field.field.meta, ":hasOne")) {
				body.push("has_one :" + RubyNaming.toMethodName(field.field.name));
			}
		}
		for (field in varFields) {
			if (hasMeta(field.field.meta, ":railsColumn")) {
				body.push("# haxe column " + RubyNaming.toMethodName(field.field.name) + ": " + typeLabel(field.field.type));
			}
		}
		for (field in varFields) {
			if (hasMeta(field.field.meta, ":validates")) {
				var options = validationOptions(field.field.meta);
				var suffix = options.length == 0 ? "" : ", " + options.join(", ");
				body.push("validates :" + validationTargetName(field) + suffix);
			}
		}
		for (field in funcFields) {
			if (field.expr == null || hasMeta(field.field.meta, ":rubyExternStub")) {
				continue;
			}
			body = body.concat(renderStatements([compileMethod(field)]));
		}
		if (body.length == 0) {
			body.push("# Rails model generated by reflaxe.ruby");
		}

		var lines = ["class " + RubyNaming.toConstantName(classType.name) + " < ::ApplicationRecord"];
		for (line in body) {
			lines.push("  " + line);
		}
		lines.push("end");

		var statements:Array<RubyStatement> = [
			RubyComment("Generated by reflaxe.ruby"),
			RubyComment("Rails model output; Zeitwerk path should match the Ruby constant.")
		];
		statements = statements.concat(requirePreludeStatements(moduleRequires));
		statements.push(wrapInModules(classType.pack, RubyRawStatement(lines.join("\n"))));
		return {
			modulePath: classType.pack == null ? [] : classType.pack.copy(),
			statements: statements
		};
	}

	static function railsSchemaRegistryLines(tableName:Null<String>, varFields:Array<ClassVarData>, classType:ClassType):Array<String> {
		var columns = [for (field in varFields) if (hasMeta(field.field.meta, ":railsColumn")) railsColumnInfo(field)];
		var lines = [
			"def self.__hx_rails_schema()",
			"  {",
			"    table_name: " + quoteRubyStringForCode(tableName == null ? railsModelTableName(classType) : tableName) + ",",
			"    timestamps: " + (hasMeta(classType.meta, ":railsTimestamps") ? "true" : "false") + ",",
			"    columns: ["
		];
		for (index in 0...columns.length) {
			var suffix = index == columns.length - 1 ? "" : ",";
			lines.push("      " + railsColumnInfoCode(columns[index]) + suffix);
		}
		lines.push("    ]");
		lines.push("  }");
		lines.push("end");
		lines.push("def self.typed_column_count()");
		lines.push("  __hx_rails_schema()[:columns].length");
		lines.push("end");
		return lines;
	}

	static function railsColumnInfo(field:ClassVarData):RailsColumnInfo {
		var haxeType = railsColumnTypeLabel(field.field.type);
		var explicitDbType = railsColumnStringOption(field.field.meta, "dbType");
		return {
			haxeName: field.field.name,
			rubyName: RubyNaming.toMethodName(field.field.name),
			haxeType: haxeType,
			railsType: explicitDbType != null ? explicitDbType : railsTypeName(haxeType),
			nullable: railsColumnBoolOption(field.field.meta, "nullable", isNullableType(field.field.type)),
			defaultValue: railsColumnValueOption(field.field.meta, "defaultValue"),
			primaryKey: railsColumnBoolOption(field.field.meta, "primaryKey", false),
			index: railsColumnBoolOption(field.field.meta, "index", false),
			unique: railsColumnBoolOption(field.field.meta, "unique", false),
			dbType: explicitDbType
		};
	}

	static function railsColumnInfoCode(info:RailsColumnInfo):String {
		var parts = [
			"name: " + rubySymbolLiteral(info.rubyName),
			"haxe_name: " + quoteRubyStringForCode(info.haxeName),
			"ruby_name: " + quoteRubyStringForCode(info.rubyName),
			"haxe_type: " + quoteRubyStringForCode(info.haxeType),
			"rails_type: " + rubySymbolLiteral(info.railsType),
			"nullable: " + (info.nullable ? "true" : "false"),
			"default: " + (info.defaultValue == null ? "nil" : info.defaultValue),
			"primary_key: " + (info.primaryKey ? "true" : "false"),
			"index: " + (info.index ? "true" : "false"),
			"unique: " + (info.unique ? "true" : "false"),
			"db_type: " + (info.dbType == null ? "nil" : rubySymbolLiteral(info.dbType))
		];
		return "{" + parts.join(", ") + "}";
	}

	static function isStdRubyType(pack:Array<String>, typeName:String):Bool {
		if (pack != null && pack.length > 0) {
			if (["_Any", "_EnumValue"].indexOf(pack[0]) != -1) {
				return true;
			}
			return pack[0] == "haxe" || pack[0] == "sys" || pack[0] == "ruby" || pack[0] == "rails";
		}
		return [
			"Any", "Bool", "Class", "Dynamic", "EReg", "Enum", "EnumValue", "Float", "IMap", "Int", "IntIterator", "Iterable", "Iterator",
			"KeyValueIterable", "KeyValueIterator", "Map", "Null", "StringBuf", "StringTools", "Std", "Sys", "Date", "Lambda", "ValueType", "Void"
		].indexOf(typeName) != -1;
	}

	static function hasStaticMain(funcFields:Array<ClassFuncData>):Bool {
		for (field in funcFields) {
			if (field.isStatic && field.field.name == "main") {
				return true;
			}
		}
		return false;
	}

	static function compileFunctionBody(expr:TypedExpr):Array<RubyStatement> {
		return switch (expr.expr) {
			case TBlock(exprs):
				compileStatementList(exprs);
			case _:
				[compileStatement(expr)];
		}
	}

	static function compileStatementList(exprs:Array<TypedExpr>):Array<RubyStatement> {
		var out = new Array<RubyStatement>();
		for (expr in exprs) {
			out.push(compileStatement(expr));
		}
		if (out.length == 0) {
			out.push(RubyNilStatement());
		}
		return out;
	}

	static function compileStatement(expr:TypedExpr):RubyStatement {
		if (expr == null) {
			return RubyExprStatement(RubyNil);
		}
		var special = compileSpecialStatement(expr);
		if (special != null) {
			return special;
		}
		switch (expr.expr) {
			case TBlock(exprs):
				return RubyRawStatement([for (stmt in compileStatementList(exprs)) statementToInlineRuby(stmt)].join("\n"));
			case TVar(v, init):
				return RubyAssign(RubyLocal(localName(v)), init == null ? RubyNil : compileExpr(init));
			case TBinop(OpAssign, lhs, rhs):
				return RubyAssign(compileAssignable(lhs), compileExpr(rhs));
			case TBinop(OpAssignOp(op), lhs, rhs):
				return RubyAssign(compileAssignable(lhs), RubyBinary(binopToRuby(op), compileExpr(lhs), compileExpr(rhs)));
			case TUnop(OpIncrement, _, inner):
				return RubyAssign(compileAssignable(inner), RubyBinary("+", compileExpr(inner), RubyInt("1")));
			case TUnop(OpDecrement, _, inner):
				return RubyAssign(compileAssignable(inner), RubyBinary("-", compileExpr(inner), RubyInt("1")));
			case TIf(cond, eThen, eElse):
				return RubyIfStmt(compileExpr(cond), compileFunctionBody(eThen), eElse == null ? null : compileFunctionBody(eElse));
			case TWhile(cond, body, _):
				return RubyWhileStmt(compileExpr(cond), compileFunctionBody(body));
			case TFor(v, iterable, body):
				return RubyRawStatement(renderFor(v, iterable, body));
			case TSwitch(switchExpr, cases, edef):
				return RubyRawStatement(renderSwitch(switchExpr, cases, edef));
			case TTry(tryExpr, catches):
				needsHxException = true;
				return RubyRawStatement(renderTry(tryExpr, catches));
			case TThrow(thrown):
				needsHxException = true;
				return RubyRawStatement("raise HxException.new(" + printInlineExpr(thrown) + ")");
			case TReturn(value):
				return RubyReturn(value == null ? null : compileExpr(value));
			case _:
				return RubyExprStatement(compileExpr(expr));
		}
	}

	static function compileExpr(expr:TypedExpr):RubyExpr {
		if (expr == null) {
			return RubyNil;
		}
		var special = compileSpecialExpr(expr);
		if (special != null) {
			return special;
		}
		return switch (expr.expr) {
			case TConst(TNull): RubyNil;
			case TConst(TBool(value)): RubyBool(value);
			case TConst(TInt(value)): RubyInt(Std.string(value));
			case TConst(TFloat(value)): RubyFloat(value);
			case TConst(TString(value)): RubyString(value);
			case TConst(TThis): RubyLocal("self");
			case TConst(TSuper): RubyLocal("super");
			case TLocal(v): RubyLocal(localName(v));
			case TArray(target, index): RubyRawExpr(printInlineExpr(target) + "[" + printInlineExpr(index) + "]");
			case TArrayDecl(values): RubyArray([for (value in values) compileExpr(value)]);
			case TObjectDecl(fields): RubyHash([for (field in fields) {key: field.name, value: compileExpr(field.expr)}]);
			case TBinop(op, lhs, rhs): RubyBinary(binopToRuby(op), compileExpr(lhs), compileExpr(rhs));
			case TUnop(op, _, inner): RubyUnary(unopToRuby(op), compileExpr(inner));
			case TParenthesis(inner) | TMeta(_, inner) | TCast(inner, _): compileExpr(inner);
			case TFunction(fn):
				RubyLambda([for (arg in fn.args) localName(arg.v)], lambdaBody(fn.expr));
			case TNew(classRef, _, params):
				var classType = classRef.get();
				RubyCall(RubyLocal(rubyNativeName(classType.meta) ?? rubyConstantPath(classType.pack, classType.name)), "new", [for (param in params) compileExpr(param)]);
			case TBlock(exprs):
				RubyRawExpr("begin\n" + [for (stmt in compileStatementList(exprs)) "  " + statementToInlineRuby(stmt)].join("\n") + "\nend");
			case TIf(cond, eThen, eElse):
				RubyRawExpr("(if " + printInlineExpr(cond) + " then " + printInlineExpr(eThen) + " else " + (eElse == null ? "nil" : printInlineExpr(eElse)) + " end)");
			case TSwitch(switchExpr, cases, edef):
				RubyRawExpr(renderSwitch(switchExpr, cases, edef));
			case TTry(tryExpr, catches):
				needsHxException = true;
				RubyRawExpr(renderTry(tryExpr, catches));
			case TThrow(thrown):
				needsHxException = true;
				RubyRawExpr("(raise HxException.new(" + printInlineExpr(thrown) + "))");
			case TEnumIndex(enumExpr):
				RubyRawExpr(printInlineExpr(enumExpr) + ".__hx_index");
			case TCall({expr: TField(_, FEnum(enumRef, field))}, params):
				RubyCall(RubyLocal(RubyNaming.toConstantName(enumRef.get().name)), RubyNaming.toMethodName(field.name), [for (param in params) compileExpr(param)]);
			case TCall({expr: TField(target, access)}, params) if (isRubyInteropCall(access)):
				compileRubyInteropCall(target, access, params);
			case TCall({expr: TField(target, access)}, params):
				RubyCall(compileExpr(target), fieldAccessName(access), [for (param in params) compileExpr(param)]);
			case TCall({expr: TConst(TSuper)}, params):
				RubyCall(null, "super", [for (param in params) compileExpr(param)]);
			case TCall(callee, params):
				RubyCall(compileExpr(callee), "call", [for (param in params) compileExpr(param)]);
			case TField(_, FEnum(enumRef, field)):
				RubyCall(RubyLocal(RubyNaming.toConstantName(enumRef.get().name)), RubyNaming.toMethodName(field.name), []);
			case TField(_, FStatic(classRef, fieldRef)):
				var classType = classRef.get();
				var constant = mathConstantValue(classType.pack, classType.name, fieldRef.get().name);
				constant == null
					? RubyRawExpr((rubyNativeName(classType.meta) ?? rubyConstantPath(classType.pack, classType.name)) + "." + rubyFieldName(fieldRef.get().name, fieldRef.get().meta))
					: RubyRawExpr(constant);
			case TField(target, access):
				RubyRawExpr(printInlineExpr(target) + "." + fieldAccessName(access));
			case TTypeExpr(moduleType):
				RubyLocal(moduleTypeName(moduleType));
			case _:
				RubyRawExpr("nil # TODO: unsupported expression " + Std.string(expr.expr));
		}
	}

	static function compileAssignable(expr:TypedExpr):RubyExpr {
		return switch (expr.expr) {
			case TLocal(v): RubyLocal(localName(v));
			case TArray(target, index): RubyRawExpr(printInlineExpr(target) + "[" + printInlineExpr(index) + "]");
			case TField(target, access): RubyRawExpr(printInlineExpr(target) + "." + fieldAccessName(access));
			case _: RubyRawExpr(printInlineExpr(expr));
		}
	}

	static function compileUntypedConst(expr:Null<haxe.macro.Expr>):RubyExpr {
		if (expr == null) {
			return RubyNil;
		}
		return switch (expr.expr) {
			case EConst(CInt(value, _)): RubyInt(value);
			case EConst(CFloat(value, _)): RubyFloat(value);
			case EConst(CString(value, _)): RubyString(value);
			case EConst(CIdent("true")): RubyBool(true);
			case EConst(CIdent("false")): RubyBool(false);
			case EConst(CIdent("null")): RubyNil;
			case _: RubyNil;
		}
	}

	static function compileSpecialStatement(expr:TypedExpr):Null<RubyStatement> {
		return switch (expr.expr) {
			case TCall(callee, params):
				var special = compileSpecialCall(callee, params);
				special == null ? null : RubyExprStatement(special);
			case _:
				null;
		}
	}

	static function compileSpecialExpr(expr:TypedExpr):Null<RubyExpr> {
		return switch (expr.expr) {
			case TCall(callee, params):
				compileSpecialCall(callee, params);
			case _:
				null;
		}
	}

	static function compileSpecialCall(callee:TypedExpr, params:Array<TypedExpr>):Null<RubyExpr> {
		var injected = compileRubyInjection(callee, params);
		if (injected != null) {
			return injected;
		}
		if (isIdentifierCallee(callee, "__is__")) {
			return RubyCall(RubyLocal("HXRuby"), "is_of_type", [compileParam(params, 0), compileParam(params, 1)]);
		}
		var arrayCall = compileArrayCall(callee, params);
		if (arrayCall != null) {
			return arrayCall;
		}
		var info = staticCallInfo(callee);
		if (info == null) {
			return null;
		}
		if ((info.owner == "ruby.Symbol" || StringTools.endsWith(info.owner, ".Symbol_Impl_")) && info.name == "of") {
			return compileRubySymbol(params);
		}
		return switch [info.owner, info.name] {
			case ["Std", "string"]:
				RubyCall(RubyLocal("HXRuby"), "stringify", [compileParam(params, 0)]);
			case ["Std", "is"] | ["Std", "isOfType"]:
				compileStdIsOfType(params);
			case ["Std", "parseInt"]:
				RubyCall(RubyLocal("HXRuby"), "parse_int", [compileParam(params, 0)]);
			case ["Std", "parseFloat"]:
				RubyCall(RubyLocal("HXRuby"), "parse_float", [compileParam(params, 0)]);
			case ["Sys", "println"]:
				RubyCall(null, "puts", [RubyCall(RubyLocal("HXRuby"), "stringify", [compileParam(params, 0)])]);
			case ["Sys", "print"]:
				RubyCall(null, "print", [RubyCall(RubyLocal("HXRuby"), "stringify", [compileParam(params, 0)])]);
			case ["Sys", "args"]:
				RubyRawExpr("ARGV");
			case ["Sys", "getEnv"]:
				RubyRawExpr("ENV[" + printParam(params, 0) + "]");
			case ["Sys", "putEnv"]:
				RubyRawExpr("ENV[" + printParam(params, 0) + "] = " + printParam(params, 1));
			case ["Sys", "getCwd"]:
				RubyRawExpr("Dir.pwd");
			case ["Sys", "setCwd"]:
				RubyRawExpr("Dir.chdir(" + printParam(params, 0) + ")");
			case ["Sys", "time"]:
				RubyRawExpr("Time.now.to_f");
			case ["Sys", "systemName"]:
				RubyRawExpr("RUBY_PLATFORM");
			case ["Sys", "exit"]:
				RubyRawExpr("exit(" + printParam(params, 0) + ")");
			case ["StringTools", "trim"]:
				RubyCall(compileParam(params, 0), "strip", []);
			case ["StringTools", "ltrim"]:
				RubyCall(compileParam(params, 0), "lstrip", []);
			case ["StringTools", "rtrim"]:
				RubyCall(compileParam(params, 0), "rstrip", []);
			case ["StringTools", "replace"]:
				RubyCall(compileParam(params, 0), "gsub", [compileParam(params, 1), compileParam(params, 2)]);
			case ["StringTools", "startsWith"]:
				RubyCall(compileParam(params, 0), "start_with?", [compileParam(params, 1)]);
			case ["StringTools", "endsWith"]:
				RubyCall(compileParam(params, 0), "end_with?", [compileParam(params, 1)]);
			case ["StringTools", "contains"]:
				RubyCall(compileParam(params, 0), "include?", [compileParam(params, 1)]);
			case ["StringTools", "hex"]:
				RubyCall(RubyLocal("HXRuby"), "hex", [compileParam(params, 0), params.length > 1 ? compileExpr(params[1]) : RubyNil]);
			case ["StringTools", "urlEncode"]:
				RubyCall(RubyLocal("HXRuby"), "url_encode", [compileParam(params, 0)]);
			case ["StringTools", "urlDecode"]:
				RubyCall(RubyLocal("HXRuby"), "url_decode", [compileParam(params, 0)]);
			case _:
				null;
		}
	}

	static function compileArrayCall(callee:TypedExpr, params:Array<TypedExpr>):Null<RubyExpr> {
		return switch (callee.expr) {
			case TField(target, access) if (isArrayFieldAccess(access)):
				var receiver = compileExpr(target);
				switch (fieldAccessRawName(access)) {
					case "concat":
						RubyCall(RubyLocal("HXRuby"), "array_concat", [receiver, compileParam(params, 0)]);
					case "join":
						RubyCall(RubyLocal("HXRuby"), "array_join", [receiver, compileParam(params, 0)]);
					case "push":
						RubyCall(RubyLocal("HXRuby"), "array_push", [receiver, compileParam(params, 0)]);
					case "reverse":
						RubyCall(RubyLocal("HXRuby"), "array_reverse", [receiver]);
					case "slice":
						RubyCall(RubyLocal("HXRuby"), "array_slice", [receiver, compileParam(params, 0), params.length > 1 ? compileExpr(params[1]) : RubyNil]);
					case "sort":
						RubyCall(RubyLocal("HXRuby"), "array_sort", [receiver, compileParam(params, 0)]);
					case "splice":
						RubyCall(RubyLocal("HXRuby"), "array_splice", [receiver, compileParam(params, 0), compileParam(params, 1)]);
					case "toString":
						RubyCall(RubyLocal("HXRuby"), "stringify", [receiver]);
					case "insert":
						RubyCall(RubyLocal("HXRuby"), "array_insert", [receiver, compileParam(params, 0), compileParam(params, 1)]);
					case "remove":
						RubyCall(RubyLocal("HXRuby"), "array_remove", [receiver, compileParam(params, 0)]);
					case "contains":
						RubyCall(RubyLocal("HXRuby"), "array_contains", [receiver, compileParam(params, 0)]);
					case "indexOf":
						RubyCall(RubyLocal("HXRuby"), "array_index_of", [receiver, compileParam(params, 0), params.length > 1 ? compileExpr(params[1]) : RubyNil]);
					case "lastIndexOf":
						RubyCall(RubyLocal("HXRuby"), "array_last_index_of", [receiver, compileParam(params, 0), params.length > 1 ? compileExpr(params[1]) : RubyNil]);
					case "copy":
						RubyCall(RubyLocal("HXRuby"), "array_copy", [receiver]);
					case "map":
						RubyCall(RubyLocal("HXRuby"), "array_map", [receiver, compileParam(params, 0)]);
					case "filter":
						RubyCall(RubyLocal("HXRuby"), "array_filter", [receiver, compileParam(params, 0)]);
					case "resize":
						RubyCall(RubyLocal("HXRuby"), "array_resize", [receiver, compileParam(params, 0)]);
					case _:
						null;
				}
			case _:
				null;
		}
	}

	static function compileStdIsOfType(params:Array<TypedExpr>):RubyExpr {
		return RubyCall(RubyLocal("HXRuby"), "is_of_type", [compileParam(params, 0), compileTypeCheckParam(params, 1)]);
	}

	static function compileTypeCheckParam(params:Array<TypedExpr>, index:Int):RubyExpr {
		if (index >= params.length) {
			return RubyNil;
		}
		return switch (params[index].expr) {
			case TTypeExpr(moduleType):
				RubyLocal(moduleTypeName(moduleType));
			case _:
				compileExpr(params[index]);
		}
	}

	static function compileRubyInteropCall(target:TypedExpr, access:haxe.macro.Type.FieldAccess, params:Array<TypedExpr>):RubyExpr {
		var receiver = reflaxe.ruby.ast.RubyASTPrinter.printExpr(compileExpr(target));
		var method = fieldAccessName(access);
		var remaining = params.copy();
		var block:Null<TypedExpr> = null;
		if (hasFieldAccessMeta(access, ":rubyBlockArg") && remaining.length > 0 && isFunctionExpr(remaining[remaining.length - 1])) {
			block = remaining.pop();
		}
		var keywordSource:Null<TypedExpr> = null;
		if (hasFieldAccessMeta(access, ":rubyKwargs") && remaining.length > 0 && isObjectDeclExpr(remaining[remaining.length - 1])) {
			keywordSource = remaining.pop();
		}
		var args = [for (param in remaining) printInlineExpr(param)];
		if (keywordSource != null) {
			args = args.concat(renderKeywordArgs(keywordSource));
		}
		var code = receiver + "." + method + "(" + args.join(", ") + ")";
		if (block != null) {
			code += " " + renderRubyBlock(block);
		}
		return RubyRawExpr(code);
	}

	static function compileRubySymbol(params:Array<TypedExpr>):RubyExpr {
		if (params.length == 0) {
			return RubyRawExpr(":\"\"");
		}
		return switch (params[0].expr) {
			case TConst(TString(value)):
				RubyRawExpr(rubySymbolLiteral(value));
			case _:
				RubyRawExpr("(" + printParam(params, 0) + ").to_sym");
		}
	}

	static function compileRubyInjection(callee:TypedExpr, params:Array<TypedExpr>):Null<RubyExpr> {
		if (!isRubyInjectionCallee(callee)) {
			return null;
		}
		if (params.length == 0) {
			Context.error("__ruby__ requires at least one String argument.", callee.pos);
			return RubyNil;
		}
		var template = switch (params[0].expr) {
			case TConst(TString(value)): value;
			case _:
				Context.error("__ruby__ first parameter must be a constant String.", params[0].pos);
				"";
		}
		var code = ~/{(\d+)}/g.map(template, ereg -> {
			var index = Std.parseInt(ereg.matched(1));
			if (index == null || index + 1 >= params.length) {
				return ereg.matched(0);
			}
			return printInlineExpr(params[index + 1]);
		});
		return RubyRawExpr(code);
	}

	static function isRubyInjectionCallee(callee:TypedExpr):Bool {
		return isIdentifierCallee(callee, "__ruby__");
	}

	static function isIdentifierCallee(callee:TypedExpr, name:String):Bool {
		return switch (callee.expr) {
			case TIdent(value) if (value == name): true;
			case TLocal(variable) if (variable.name == name): true;
			case TField(_, access):
				fieldAccessName(access) == name;
			case _:
				false;
		}
	}

	static function renderKeywordArgs(expr:TypedExpr):Array<String> {
		return switch (expr.expr) {
			case TObjectDecl(fields):
				[for (field in fields) RubyNaming.toMethodName(field.name) + ": " + printInlineExpr(field.expr)];
			case _:
				[printInlineExpr(expr)];
		}
	}

	static function renderRubyBlock(expr:TypedExpr):String {
		return switch (expr.expr) {
			case TFunction(fn):
				var args = [for (arg in fn.args) localName(arg.v)].join(", ");
				var body = renderStatements(compileFunctionBody(fn.expr));
				if (canRenderInlineBlock(body)) {
					var prefix = args == "" ? "" : "|" + args + "| ";
					"{ " + prefix + body[0] + " }";
				} else {
					var lines = [args == "" ? "do" : "do |" + args + "|"];
					appendIndentedLines(lines, body, 1);
					lines.push("end");
					lines.join("\n");
				}
			case _:
			"{ |value| " + printInlineExpr(expr) + ".call(value) }";
		}
	}

	static function canRenderInlineBlock(body:Array<String>):Bool {
		if (body.length != 1) {
			return false;
		}
		var line = body[0];
		return line.indexOf("\n") == -1 && !StringTools.startsWith(StringTools.trim(line), "return");
	}

	static function isRubyInteropCall(access:haxe.macro.Type.FieldAccess):Bool {
		return hasFieldAccessMeta(access, ":rubyKwargs") || hasFieldAccessMeta(access, ":rubyBlockArg");
	}

	static function isFunctionExpr(expr:TypedExpr):Bool {
		return switch (expr.expr) {
			case TFunction(_): true;
			case _: false;
		}
	}

	static function isObjectDeclExpr(expr:TypedExpr):Bool {
		return switch (expr.expr) {
			case TObjectDecl(_): true;
			case _: false;
		}
	}

	static function staticCallInfo(callee:TypedExpr):Null<{owner:String, name:String}> {
		return switch (callee.expr) {
			case TField(_, FStatic(classRef, fieldRef)):
				var classType = classRef.get();
				{owner: fullTypeName(classType.pack, classType.name), name: fieldRef.get().name};
			case _:
				null;
		}
	}

	static function compileParam(params:Array<TypedExpr>, index:Int):RubyExpr {
		return index < params.length ? compileExpr(params[index]) : RubyNil;
	}

	static function printParam(params:Array<TypedExpr>, index:Int):String {
		return reflaxe.ruby.ast.RubyASTPrinter.printExpr(compileParam(params, index));
	}

	static function renderSwitch(switchExpr:TypedExpr, cases:Array<{values:Array<TypedExpr>, expr:TypedExpr}>, edef:Null<TypedExpr>):String {
		var usesEnumIndex = switch (switchExpr.expr) {
			case TEnumIndex(_): true;
			case _: false;
		}
		var lines = ["case " + switchScrutineeCode(switchExpr)];
		for (branch in cases) {
			var values = [for (value in branch.values) switchValueCode(value, usesEnumIndex)];
			lines.push("when " + values.join(", "));
			appendIndentedLines(lines, renderStatements(compileFunctionBody(branch.expr)), 1);
		}
		if (edef != null) {
			lines.push("else");
			appendIndentedLines(lines, renderStatements(compileFunctionBody(edef)), 1);
		}
		lines.push("end");
		return lines.join("\n");
	}

	static function renderTry(tryExpr:TypedExpr, catches:Array<{v:TVar, expr:TypedExpr}>):String {
		var lines = ["begin"];
		appendIndentedLines(lines, renderStatements(compileFunctionBody(tryExpr)), 1);
		if (catches.length > 0) {
			var first = catches[0];
			lines.push("rescue HxException => __hx_ex");
			lines.push("  " + localName(first.v) + " = __hx_ex.value");
			appendIndentedLines(lines, renderStatements(compileFunctionBody(first.expr)), 1);
		}
		lines.push("end");
		return lines.join("\n");
	}

	static function renderFor(v:TVar, iterable:TypedExpr, body:TypedExpr):String {
		var iteratorName = loopIteratorName(v, iterable);
		var lines = [
			iteratorName + " = " + printInlineExpr(iterable),
			"while " + iteratorName + ".has_next()",
			"  " + localName(v) + " = " + iteratorName + ".next_()"
		];
		appendIndentedLines(lines, renderStatements(compileFunctionBody(body)), 1);
		lines.push("end");
		return lines.join("\n");
	}

	static function switchScrutineeCode(expr:TypedExpr):String {
		return switch (expr.expr) {
			case TEnumIndex(enumExpr):
				printInlineExpr(enumExpr) + ".__hx_index";
			case _:
				printInlineExpr(expr);
		}
	}

	static function switchValueCode(expr:TypedExpr, usesEnumIndex:Bool):String {
		if (usesEnumIndex) {
			return printInlineExpr(expr);
		}
		return switch (expr.expr) {
			case TField(_, FEnum(_, field)):
				quoteRubyStringForCode(field.name);
			case _:
				printInlineExpr(expr);
		}
	}

	static function renderStatements(statements:Array<RubyStatement>):Array<String> {
		var file = {
			modulePath: [],
			statements: statements
		};
		var printed = reflaxe.ruby.ast.RubyASTPrinter.printFile(file).split("\n");
		if (printed.length > 0 && printed[printed.length - 1] == "") {
			printed.pop();
		}
		return printed;
	}

	static function appendIndentedLines(target:Array<String>, lines:Array<String>, indentLevel:Int):Void {
		var indent = "";
		for (_ in 0...indentLevel) {
			indent += "  ";
		}
		for (line in lines) {
			target.push(indent + line);
		}
	}

	function setRuntimeExtraFile(name:String):Void {
		setExtraFile(OutputPath.fromStr(outputRelativePath("hxruby/" + name, true)), runtimeFileContent(name));
	}

	function setRailsAutoloadInitializer():Void {
		var root = buildContext.railsOutputRoot;
		var lines = [
			"# Generated by reflaxe.ruby",
			"hxruby_root = Rails.root.join(" + quoteRubyStringForCode(root) + ")",
			"Rails.application.config.autoload_paths << hxruby_root",
			"Rails.application.config.eager_load_paths << hxruby_root",
			""
		];
		setExtraFile(OutputPath.fromStr("config/initializers/hxruby_autoload.rb"), lines.join("\n"));
	}

	function emitRailsTemplateArtifact(classType:ClassType, varFields:Array<ClassVarData>, funcFields:Array<ClassFuncData>):Void {
		if (!buildContext.railsMode) {
			Context.error("@:railsTemplate requires -D reflaxe_ruby_rails.", classType.pos);
			return;
		}
		var templatePath = metaStringParam(classType.meta, ":railsTemplate", 0);
		if (templatePath == null) {
			Context.error("@:railsTemplate expects a Rails template path string.", classType.pos);
			return;
		}
		var usesTypedTemplateAst = metaStringParam(classType.meta, ":railsTemplateAst", 0) != null;
		var body = railsTemplateSourceBody(classType, varFields, funcFields);
		if (body == null) {
			Context.error("@:railsTemplate expects a source path argument, @:railsTemplateAst method, or static string field named body/erb/template.",
				classType.pos);
			return;
		}
		if (!usesTypedTemplateAst && containsRawErb(body) && !hasMeta(classType.meta, ":railsAllowRawErb")) {
			Context.error("@:railsTemplate raw ERB blocks require @:railsAllowRawErb. Prefer typed RailsHx template helpers when available.", classType.pos);
			return;
		}
		setExtraFile(OutputPath.fromStr(railsTemplateOutputPath(templatePath)), normalizeGeneratedText(body));
	}

	function railsTemplateSourceBody(classType:ClassType, varFields:Array<ClassVarData>, funcFields:Array<ClassFuncData>):Null<String> {
		var source = metaStringParam(classType.meta, ":railsTemplate", 1);
		if (source != null) {
			var path = Path.normalize(Path.join([Path.directory(Context.getPosInfos(classType.pos).file), source]));
			if (!FileSystem.exists(path)) {
				Context.error("@:railsTemplate source file not found: " + path, classType.pos);
				return null;
			}
			return File.getContent(path);
		}
		var astMethod = metaStringParam(classType.meta, ":railsTemplateAst", 0);
		if (astMethod != null) {
			return railsTemplateAstBody(classType, funcFields, astMethod);
		}
		for (field in varFields) {
			if (!field.isStatic || ["body", "erb", "template"].indexOf(field.field.name) == -1) {
				continue;
			}
			var expr = field.getDefaultUntypedExpr();
			if (expr == null) {
				continue;
			}
			return switch (expr.expr) {
				case EConst(CString(value, _)): value;
				case _:
					Context.error("@:railsTemplate static body/erb/template field must be a string literal.", expr.pos);
					null;
			}
		}
		return null;
	}

	function railsTemplateAstBody(classType:ClassType, funcFields:Array<ClassFuncData>, methodName:String):Null<String> {
		for (field in funcFields) {
			if (!field.isStatic || field.field.name != methodName) {
				continue;
			}
			if (field.expr == null) {
				Context.error("@:railsTemplateAst method must have a body.", field.field.pos);
				return null;
			}
			var scope = templateScopeFor(field);
			var node = extractTemplateAstReturn(field.expr);
			if (node == null) {
				Context.error("@:railsTemplateAst method must return a rails.action_view.HtmlNode expression.", field.field.pos);
				return null;
			}
			return lowerTemplateNode(node, scope);
		}
		Context.error('@:railsTemplateAst could not find static method "$methodName".', classType.pos);
		return null;
	}

	static function templateScopeFor(field:ClassFuncData):RailsTemplateScope {
		var localNames:Map<Int, String> = [];
		var localObjectNames:Map<Int, String> = [];
		for (arg in field.args) {
			if (arg.tvar != null) {
				var argName = arg.getName();
				localNames.set(arg.tvar.id, RubyNaming.toLocalName(argName));
				if (argName == "locals") {
					localObjectNames.set(arg.tvar.id, argName);
				}
			}
		}
		return {localNames: localNames, localObjectNames: localObjectNames};
	}

	static function extractTemplateAstReturn(expr:TypedExpr):Null<TypedExpr> {
		var unwrapped = unwrapTemplateExpr(expr);
		return switch (unwrapped.expr) {
			case TReturn(value): value == null ? null : unwrapTemplateExpr(value);
			case TBlock(exprs):
				if (exprs == null || exprs.length == 0) {
					null;
				} else {
					extractTemplateAstReturn(exprs[exprs.length - 1]);
				}
			case _: unwrapped;
		}
	}

	static function unwrapTemplateExpr(expr:TypedExpr):TypedExpr {
		return switch (expr.expr) {
			case TMeta(_, inner) | TParenthesis(inner) | TCast(inner, _): unwrapTemplateExpr(inner);
			case _: expr;
		}
	}

	static function lowerTemplateNode(expr:TypedExpr, scope:RailsTemplateScope):String {
		var node = unwrapTemplateExpr(expr);
		return switch (node.expr) {
			case TCall(fn, params):
				switch (templateCtorName(fn, "HtmlNode")) {
					case "Text":
						if (params.length != 1) {
							Context.error("HtmlNode.Text expects one argument.", node.pos);
							"";
						} else {
							expectTemplateString(params[0], "HtmlNode.Text expects a string literal.");
						}
					case "ExprText":
						if (params.length != 1) {
							Context.error("HtmlNode.ExprText expects one argument.", node.pos);
							"";
						} else {
							"<%= " + printTemplateExpr(params[0], scope) + " %>";
						}
					case "Fragment":
						if (params.length != 1) {
							Context.error("HtmlNode.Fragment expects one children array.", node.pos);
							"";
						} else {
							var out = "";
							for (child in expectTemplateArray(params[0], "HtmlNode.Fragment expects an array literal.")) {
								out += lowerTemplateNode(child, scope);
							}
							out;
						}
					case "Element":
						if (params.length != 3) {
							Context.error("HtmlNode.Element expects name, attrs, and children arguments.", node.pos);
							"";
						} else {
							var name = expectTemplateString(params[0], "HtmlNode.Element name must be a string literal.");
							var attrs = expectTemplateArray(params[1], "HtmlNode.Element attrs must be an array literal.");
							var children = expectTemplateArray(params[2], "HtmlNode.Element children must be an array literal.");
							lowerTemplateElement(name, attrs, children, scope);
						}
					case "If":
						if (params.length != 3) {
							Context.error("HtmlNode.If expects cond, thenBranch, and elseBranch arguments.", node.pos);
							"";
						} else {
							lowerTemplateIf(params[0], params[1], params[2], scope);
						}
					case "For":
						if (params.length != 2) {
							Context.error("HtmlNode.For expects items and render arguments.", node.pos);
							"";
						} else {
							lowerTemplateFor(params[0], params[1], scope);
						}
					case "Partial":
						if (params.length != 2) {
							Context.error("HtmlNode.Partial expects template and locals arguments.", node.pos);
							"";
						} else {
							lowerTemplatePartial(params[0], params[1], scope);
						}
					case "LinkTo":
						if (params.length != 3) {
							Context.error("HtmlNode.LinkTo expects label, url, and attrs arguments.", node.pos);
							"";
						} else {
							lowerTemplateLinkTo(params[0], params[1], params[2], scope);
						}
					case "LinkToBlock":
						if (params.length != 3) {
							Context.error("HtmlNode.LinkToBlock expects url, attrs, and children arguments.", node.pos);
							"";
						} else {
							lowerTemplateLinkToBlock(params[0], params[1], params[2], scope);
						}
					case "FormWith":
						if (params.length != 4) {
							Context.error("HtmlNode.FormWith expects url, scope, attrs, and children arguments.", node.pos);
							"";
						} else {
							lowerTemplateFormWith(params[0], params[1], params[2], params[3], scope);
						}
					case "FormHiddenField":
						if (params.length != 2) {
							Context.error("HtmlNode.FormHiddenField expects name and value arguments.", node.pos);
							"";
						} else {
							lowerTemplateFormHiddenField(params[0], params[1], scope);
						}
					case "FormLabel":
						if (params.length != 2) {
							Context.error("HtmlNode.FormLabel expects name and text arguments.", node.pos);
							"";
						} else {
							lowerTemplateFormLabel(params[0], params[1], scope);
						}
					case "FormTextField":
						if (params.length != 2) {
							Context.error("HtmlNode.FormTextField expects name and attrs arguments.", node.pos);
							"";
						} else {
							lowerTemplateFormTextField(params[0], params[1], scope);
						}
					case "FormSubmit":
						if (params.length != 2) {
							Context.error("HtmlNode.FormSubmit expects text and attrs arguments.", node.pos);
							"";
						} else {
							lowerTemplateFormSubmit(params[0], params[1], scope);
						}
					case other:
						Context.error('Unsupported HtmlNode constructor "$other" in @:railsTemplateAst.', node.pos);
						"";
				}
			case TBlock(exprs):
				if (exprs == null || exprs.length == 0) {
					Context.error("@:railsTemplateAst node block is empty.", node.pos);
					"";
				} else {
					lowerTemplateNode(exprs[exprs.length - 1], scope);
				}
			case _:
				Context.error("@:railsTemplateAst expected a rails.action_view.HtmlNode constructor expression.", node.pos);
				"";
		}
	}

	static function lowerTemplateElement(name:String, attrs:Array<TypedExpr>, children:Array<TypedExpr>, scope:RailsTemplateScope):String {
		var out = "<" + name;
		for (attr in attrs) {
			out += lowerTemplateAttr(attr, scope);
		}
		if (children.length == 0 && isVoidHtmlElement(name)) {
			return out + ">";
		}
		out += ">";
		for (child in children) {
			out += lowerTemplateNode(child, scope);
		}
		return out + "</" + name + ">";
	}

	static function lowerTemplateAttr(expr:TypedExpr, scope:RailsTemplateScope):String {
		var attr = unwrapTemplateExpr(expr);
		return switch (attr.expr) {
			case TCall(fn, params):
				switch (templateCtorName(fn, "HtmlAttr")) {
					case "Static":
						if (params.length != 2) {
							Context.error("HtmlAttr.Static expects name and value arguments.", attr.pos);
							"";
						} else {
							" " + expectTemplateString(params[0], "HtmlAttr.Static name must be a string literal.") + "="
								+ quoteHtmlAttr(expectTemplateString(params[1], "HtmlAttr.Static value must be a string literal."));
						}
					case "Bool":
						if (params.length != 1) {
							Context.error("HtmlAttr.Bool expects one name argument.", attr.pos);
							"";
						} else {
							" " + expectTemplateString(params[0], "HtmlAttr.Bool name must be a string literal.");
						}
					case "Expr":
						if (params.length != 2) {
							Context.error("HtmlAttr.Expr expects name and value arguments.", attr.pos);
							"";
						} else {
							" " + expectTemplateString(params[0], "HtmlAttr.Expr name must be a string literal.") + "=\"<%= "
								+ printTemplateExpr(params[1], scope) + " %>\"";
						}
					case other:
						Context.error('Unsupported HtmlAttr constructor "$other" in @:railsTemplateAst.', attr.pos);
						"";
				}
			case _:
				Context.error("@:railsTemplateAst expected a rails.action_view.HtmlAttr constructor expression.", attr.pos);
				"";
		}
	}

	static function lowerTemplateIf(cond:TypedExpr, thenBranch:TypedExpr, elseBranch:TypedExpr, scope:RailsTemplateScope):String {
		var out = "<% if " + printTemplateExpr(cond, scope) + " %>" + lowerTemplateNode(thenBranch, scope);
		var unwrappedElse = unwrapTemplateExpr(elseBranch);
		switch (unwrappedElse.expr) {
			case TConst(TNull):
			case _:
				out += "<% else %>" + lowerTemplateNode(unwrappedElse, scope);
		}
		return out + "<% end %>";
	}

	static function lowerTemplateFor(items:TypedExpr, render:TypedExpr, scope:RailsTemplateScope):String {
		var fn = unwrapTemplateExpr(render);
		return switch (fn.expr) {
			case TFunction(func):
				if (func.args.length != 1) {
					Context.error("HtmlNode.For render function must take exactly one argument.", fn.pos);
					"";
				} else {
					var binder = func.args[0].v;
					var nextScope = cloneTemplateScope(scope);
					nextScope.localNames.set(binder.id, RubyNaming.toLocalName(binder.name));
					var body = extractTemplateAstReturn(func.expr);
					if (body == null) {
						Context.error("HtmlNode.For render function must return a HtmlNode.", fn.pos);
						"";
					} else {
						"<% " + printTemplateExpr(items, scope) + ".each do |" + RubyNaming.toLocalName(binder.name) + "| %>"
							+ lowerTemplateNode(body, nextScope) + "<% end %>";
					}
				}
			case _:
				Context.error("HtmlNode.For render argument must be an inline function.", fn.pos);
				"";
		}
	}

	static function lowerTemplateFormWith(url:TypedExpr, scopeExpr:TypedExpr, attrs:TypedExpr, childrenExpr:TypedExpr, scope:RailsTemplateScope):String {
		var formVar = "form";
		var helperArgs = ["url: " + printTemplateExpr(url, scope), "scope: " + rubySymbolLiteral(expectTemplateString(scopeExpr, "HtmlNode.FormWith scope must be a string literal."))];
		helperArgs = helperArgs.concat(lowerTemplateHelperAttrs(attrs, scope));
		var formScope = cloneTemplateScope(scope);
		formScope.formBuilderName = formVar;
		var out = "<%= form_with " + helperArgs.join(", ") + " do |" + formVar + "| %>";
		for (child in expectTemplateArray(childrenExpr, "HtmlNode.FormWith children must be an array literal.")) {
			out += lowerTemplateNode(child, formScope);
		}
		return out + "<% end %>";
	}

	static function lowerTemplateFormHiddenField(name:TypedExpr, value:TypedExpr, scope:RailsTemplateScope):String {
		var form = requireFormBuilder(scope, name);
		return "<%= " + form + ".hidden_field " + rubySymbolLiteral(expectTemplateString(name, "H.hiddenField name must be a string literal."))
			+ ", value: " + printTemplateExpr(value, scope) + " %>";
	}

	static function lowerTemplateFormLabel(name:TypedExpr, text:TypedExpr, scope:RailsTemplateScope):String {
		var form = requireFormBuilder(scope, name);
		return "<%= " + form + ".label " + rubySymbolLiteral(expectTemplateString(name, "H.label name must be a string literal."))
			+ ", " + printTemplateExpr(text, scope) + " %>";
	}

	static function lowerTemplateFormTextField(name:TypedExpr, attrs:TypedExpr, scope:RailsTemplateScope):String {
		var form = requireFormBuilder(scope, name);
		var args = [rubySymbolLiteral(expectTemplateString(name, "H.textField name must be a string literal."))].concat(lowerTemplateHelperAttrs(attrs, scope));
		return "<%= " + form + ".text_field " + args.join(", ") + " %>";
	}

	static function lowerTemplateFormSubmit(text:TypedExpr, attrs:TypedExpr, scope:RailsTemplateScope):String {
		var form = requireFormBuilder(scope, text);
		var args = [printTemplateExpr(text, scope)].concat(lowerTemplateHelperAttrs(attrs, scope));
		return "<%= " + form + ".submit " + args.join(", ") + " %>";
	}

	static function requireFormBuilder(scope:RailsTemplateScope, expr:TypedExpr):String {
		if (scope.formBuilderName == null) {
			Context.error("Rails form field helpers must be used inside <form_with> or H.formWith(...).", expr.pos);
			return "form";
		}
		return scope.formBuilderName;
	}

	static function lowerTemplateLinkTo(label:TypedExpr, url:TypedExpr, attrs:TypedExpr, scope:RailsTemplateScope):String {
		var args = [printTemplateExpr(label, scope), printTemplateExpr(url, scope)];
		var kwargs = lowerTemplateHelperAttrs(attrs, scope);
		if (kwargs.length > 0) {
			args = args.concat(kwargs);
		}
		return "<%= link_to " + args.join(", ") + " %>";
	}

	static function lowerTemplateLinkToBlock(url:TypedExpr, attrs:TypedExpr, childrenExpr:TypedExpr, scope:RailsTemplateScope):String {
		var args = [printTemplateExpr(url, scope)].concat(lowerTemplateHelperAttrs(attrs, scope));
		var out = "<%= link_to " + args.join(", ") + " do %>";
		for (child in expectTemplateArray(childrenExpr, "HtmlNode.LinkToBlock children must be an array literal.")) {
			out += lowerTemplateNode(child, scope);
		}
		return out + "<% end %>";
	}

	static function lowerTemplateHelperAttrs(attrs:TypedExpr, scope:RailsTemplateScope):Array<String> {
		var out:Array<String> = [];
		for (attr in expectTemplateArray(attrs, "HtmlNode.LinkTo attrs must be an array literal.")) {
			var unwrapped = unwrapTemplateExpr(attr);
			switch (unwrapped.expr) {
				case TCall(fn, params):
					switch (templateCtorName(fn, "HtmlAttr")) {
						case "Static":
							if (params.length != 2) {
								Context.error("HtmlAttr.Static expects name and value arguments.", unwrapped.pos);
							} else {
								out.push(helperKwargName(expectTemplateString(params[0], "HtmlAttr.Static name must be a string literal."))
									+ ": " + quoteRubyStringForCode(expectTemplateString(params[1], "HtmlAttr.Static value must be a string literal.")));
							}
						case "Bool":
							if (params.length != 1) {
								Context.error("HtmlAttr.Bool expects one name argument.", unwrapped.pos);
							} else {
								out.push(helperKwargName(expectTemplateString(params[0], "HtmlAttr.Bool name must be a string literal.")) + ": true");
							}
						case "Expr":
							if (params.length != 2) {
								Context.error("HtmlAttr.Expr expects name and value arguments.", unwrapped.pos);
							} else {
								out.push(helperKwargName(expectTemplateString(params[0], "HtmlAttr.Expr name must be a string literal."))
									+ ": " + printTemplateExpr(params[1], scope));
							}
						case other:
							Context.error('Unsupported HtmlAttr constructor "$other" for HtmlNode.LinkTo.', unwrapped.pos);
					}
				case _:
					Context.error("HtmlNode.LinkTo attrs must contain HtmlAttr constructor expressions.", unwrapped.pos);
			}
		}
		return out;
	}

	static function lowerTemplatePartial(template:TypedExpr, locals:TypedExpr, scope:RailsTemplateScope):String {
		var path = extractTypedTemplatePath(template);
		if (path == null) {
			Context.error("HtmlNode.Partial expects Template.named(\"path\") as the template argument.", template.pos);
			return "";
		}
		var localsHash = lowerTemplateLocalsHash(locals, scope);
		return "<%= render partial: " + quoteRubyStringForCode(path) + ", locals: " + localsHash + " %>";
	}

	static function lowerTemplateLocalsHash(locals:TypedExpr, scope:RailsTemplateScope):String {
		return switch (unwrapTemplateExpr(locals).expr) {
			case TObjectDecl(fields):
				if (fields.length == 0) {
					Context.error("HtmlNode.Partial locals must include at least one named local.", locals.pos);
					"{}";
				} else {
					"{" + [for (field in fields) quoteRubyStringForCode(RubyNaming.toLocalName(field.name)) + " => " + printTemplateExpr(field.expr, scope)].join(", ") + "}";
				}
			case _:
				Context.error("HtmlNode.Partial locals must be an object literal so Rails local names are explicit.", locals.pos);
				"{}";
		}
	}

	static function extractTypedTemplatePath(template:TypedExpr):Null<String> {
		var unwrapped = unwrapTemplateExpr(template);
		return switch (unwrapped.expr) {
			case TCall(callee, [path]) if (isTemplateNamedCall(callee)):
				expectTemplateString(path, "Template.named expects a string literal path.");
			case _:
				null;
		}
	}

	static function isTemplateNamedCall(callee:TypedExpr):Bool {
		return switch (unwrapTemplateExpr(callee).expr) {
			case TField(_, access):
				fieldAccessName(access) == "named";
			case _:
				false;
		}
	}

	static function cloneTemplateScope(scope:RailsTemplateScope):RailsTemplateScope {
		var localNames:Map<Int, String> = [];
		for (key in scope.localNames.keys()) {
			localNames.set(key, scope.localNames.get(key));
		}
		var localObjectNames:Map<Int, String> = [];
		for (key in scope.localObjectNames.keys()) {
			localObjectNames.set(key, scope.localObjectNames.get(key));
		}
		return {localNames: localNames, localObjectNames: localObjectNames, formBuilderName: scope.formBuilderName};
	}

	static function templateCtorName(fn:TypedExpr, enumName:String):Null<String> {
		var unwrapped = unwrapTemplateExpr(fn);
		return switch (unwrapped.expr) {
			case TField(_, FEnum(enumRef, fieldRef)):
				var enumType = enumRef.get();
				if (enumType.name == enumName && enumType.pack.join(".") == "rails.action_view") {
					fieldRef.name;
				} else {
					null;
				}
			case _:
				null;
		}
	}

	static function expectTemplateArray(expr:TypedExpr, message:String):Array<TypedExpr> {
		return switch (unwrapTemplateExpr(expr).expr) {
			case TArrayDecl(values): values;
			case _:
				Context.error(message, expr.pos);
				[];
		}
	}

	static function expectTemplateString(expr:TypedExpr, message:String):String {
		return switch (unwrapTemplateExpr(expr).expr) {
			case TConst(TString(value)): value;
			case _:
				Context.error(message, expr.pos);
				"";
		}
	}

	static function printTemplateExpr(expr:TypedExpr, scope:RailsTemplateScope):String {
		var unwrapped = unwrapTemplateExpr(expr);
		return switch (unwrapped.expr) {
			case TLocal(v) if (scope.localNames.exists(v.id)):
				scope.localNames.get(v.id);
			case TConst(TNull): "nil";
			case TConst(TBool(value)): value ? "true" : "false";
			case TConst(TInt(value)): Std.string(value);
			case TConst(TFloat(value)): value;
			case TConst(TString(value)): quoteRubyStringForCode(value);
			case TArray(target, index): printTemplateExpr(target, scope) + "[" + printTemplateExpr(index, scope) + "]";
			case TArrayDecl(values): "[" + [for (value in values) printTemplateExpr(value, scope)].join(", ") + "]";
			case TBinop(op, lhs, rhs): printTemplateExpr(lhs, scope) + " " + binopToRuby(op) + " " + printTemplateExpr(rhs, scope);
			case TUnop(op, _, inner): unopToRuby(op) + printTemplateExpr(inner, scope);
			case TField({expr: TLocal(v)}, access) if (scope.localObjectNames.exists(v.id)):
				fieldAccessName(access);
			case TField(target, access): printTemplateExpr(target, scope) + "." + fieldAccessName(access);
			case TCall({expr: TField(_, FStatic(classRef, fieldRef))}, params):
				var classType = classRef.get();
				var receiver = rubyNativeName(classType.meta) ?? rubyConstantPath(classType.pack, classType.name);
				var method = rubyFieldName(fieldRef.get().name, fieldRef.get().meta);
				var args = [for (param in params) printTemplateExpr(param, scope)].join(", ");
				(receiver == "self" ? method : receiver + "." + method) + "(" + args + ")";
			case TCall({expr: TField(target, access)}, params):
				printTemplateExpr(target, scope) + "." + fieldAccessName(access) + "(" + [for (param in params) printTemplateExpr(param, scope)].join(", ") + ")";
			case TCall(callee, params):
				printTemplateExpr(callee, scope) + ".call(" + [for (param in params) printTemplateExpr(param, scope)].join(", ") + ")";
			case TIf(cond, eThen, eElse):
				"(if " + printTemplateExpr(cond, scope) + " then " + printTemplateExpr(eThen, scope) + " else "
					+ (eElse == null ? "nil" : printTemplateExpr(eElse, scope)) + " end)";
			case _:
				reflaxe.ruby.ast.RubyASTPrinter.printExpr(compileExpr(unwrapped));
		}
	}

	static function quoteHtmlAttr(value:String):String {
		return quoteRubyStringForCode(value);
	}

	static function helperKwargName(value:String):String {
		return ~/[^A-Za-z0-9_]/g.replace(value, "_");
	}

	static function isVoidHtmlElement(name:String):Bool {
		return ["area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"].indexOf(name) != -1;
	}

	static function railsTemplateOutputPath(path:String):String {
		var normalized = StringTools.replace(path, "\\", "/");
		while (StringTools.startsWith(normalized, "/")) {
			normalized = normalized.substr(1);
		}
		if (normalized == "" || normalized.indexOf("..") != -1) {
			return "app/views/invalid_template_path.html.erb";
		}
		if (!StringTools.endsWith(normalized, ".erb")) {
			normalized += ".html.erb";
		}
		return "app/views/" + normalized;
	}

	static function normalizeGeneratedText(value:String):String {
		var normalized = StringTools.replace(value == null ? "" : value, "\r\n", "\n").split("\r").join("\n");
		return StringTools.endsWith(normalized, "\n") ? normalized : normalized + "\n";
	}

	static function containsRawErb(value:String):Bool {
		return value != null && value.indexOf("<%") != -1;
	}

	function outputRelativeDir(dir:Null<String>, appOwned:Bool):Null<String> {
		var normalized = dir == null ? "" : dir;
		if (buildContext.railsMode && appOwned) {
			return normalized == "" ? buildContext.railsOutputRoot : buildContext.railsOutputRoot + "/" + normalized;
		}
		return normalized == "" ? null : normalized;
	}

	function outputRelativePath(path:String, runtimeOwned:Bool):String {
		if (buildContext.railsMode && runtimeOwned) {
			return buildContext.railsOutputRoot + "/" + path;
		}
		return path;
	}

	static function runtimeFileContent(name:String):String {
		var path = Path.join([findLibraryRoot(), "runtime", "hxruby", name]);
		if (!FileSystem.exists(path)) {
			Context.fatalError("Missing hxruby runtime file: " + path, Context.currentPos());
		}
		return File.getContent(path);
	}

	static function findLibraryRoot():String {
		var compilerPath = Context.resolvePath("reflaxe/ruby/RubyCompiler.hx");
		return Path.normalize(Path.join([Path.directory(compilerPath), "..", "..", ".."]));
	}

	static function isSysPrintCall(callee:TypedExpr):Bool {
		return switch (callee.expr) {
			case TField(_, FStatic(_, field)) | TField(_, FInstance(_, _, field)):
				var name = field.get().name;
				name == "print" || name == "println";
			case TField(_, FAnon(fieldRef)) | TField(_, FClosure(_, fieldRef)):
				var field = fieldRef.get();
				field.name == "print" || field.name == "println";
			case _:
				false;
		}
	}

	static function fieldAccessName(access:haxe.macro.Type.FieldAccess):String {
		return switch (access) {
			case FInstance(_, _, field) | FStatic(_, field): rubyFieldName(field.get().name, field.get().meta);
			case FAnon(fieldRef) | FClosure(_, fieldRef): rubyFieldName(fieldRef.get().name, fieldRef.get().meta);
			case FDynamic(name): RubyNaming.toMethodName(name);
			case FEnum(_, field): rubyFieldName(field.name, field.meta);
		}
	}

	static function fieldAccessRawName(access:haxe.macro.Type.FieldAccess):String {
		return switch (access) {
			case FInstance(_, _, field) | FStatic(_, field): field.get().name;
			case FAnon(fieldRef) | FClosure(_, fieldRef): fieldRef.get().name;
			case FDynamic(name): name;
			case FEnum(_, field): field.name;
		}
	}

	static function isArrayFieldAccess(access:haxe.macro.Type.FieldAccess):Bool {
		return switch (access) {
			case FInstance(classRef, _, _):
				var classType = classRef.get();
				fullTypeName(classType.pack, classType.name) == "Array";
			case _:
				false;
		}
	}

	static function hasFieldAccessMeta(access:haxe.macro.Type.FieldAccess, name:String):Bool {
		var meta = switch (access) {
			case FInstance(_, _, field) | FStatic(_, field): field.get().meta;
			case FAnon(fieldRef) | FClosure(_, fieldRef): fieldRef.get().meta;
			case FEnum(_, field): field.meta;
			case FDynamic(_): null;
		}
		return hasMeta(meta, name);
	}

	static function moduleTypeName(moduleType:ModuleType):String {
		return switch (moduleType) {
			case TClassDecl(classRef):
				var classType = classRef.get();
				coreRubyTypeName(classType.pack, classType.name) ?? rubyNativeName(classType.meta) ?? rubyConstantPath(classType.pack, classType.name);
			case TEnumDecl(enumRef):
				var enumType = enumRef.get();
				rubyNativeName(enumType.meta) ?? rubyConstantPath(enumType.pack, enumType.name);
			case TTypeDecl(typeRef):
				var defType = typeRef.get();
				rubyNativeName(defType.meta) ?? rubyConstantPath(defType.pack, defType.name);
			case TAbstract(abstractRef):
				var abstractType = abstractRef.get();
				rubyNativeName(abstractType.meta) ?? rubyConstantPath(abstractType.pack, abstractType.name);
		}
	}

	static function coreRubyTypeName(pack:Array<String>, name:String):Null<String> {
		return switch (fullTypeName(pack, name)) {
			case "String": "String";
			case "Array": "Array";
			case _: null;
		}
	}

	static function rubyConstantPath(pack:Array<String>, name:String):String {
		var parts = RubyNaming.modulePath(pack);
		parts.push(RubyNaming.toConstantName(name));
		return parts.join("::");
	}

	static function rubyFieldName(name:String, meta:Null<haxe.macro.Type.MetaAccess>):String {
		return rubyNativeName(meta) ?? RubyNaming.toMethodName(name);
	}

	static function rubyNativeName(meta:Null<haxe.macro.Type.MetaAccess>):Null<String> {
		if (meta == null || meta.extract == null) {
			return null;
		}
		var entries = meta.extract(":native");
		if (entries.length == 0) {
			return null;
		}
		var entry = entries[0];
		if (entry.params == null || entry.params.length == 0) {
			return null;
		}
		return switch (entry.params[0].expr) {
			case EConst(CString(value, _)) if (value.length > 0): value;
			case EConst(CIdent(value)) if (value.length > 0): value;
			case _: null;
		}
	}

	static function hasMeta(meta:Null<haxe.macro.Type.MetaAccess>, name:String):Bool {
		return meta != null && meta.has != null && meta.has(name);
	}

	static function railsModelTableName(classType:ClassType):Null<String> {
		var explicit = metaStringValue(classType.meta, ":railsModel");
		if (explicit != null) {
			return explicit;
		}
		return RubyNaming.fileName(classType.name) + "s";
	}

	static function metaStringValue(meta:Null<haxe.macro.Type.MetaAccess>, name:String):Null<String> {
		return metaStringParam(meta, name, 0);
	}

	static function metaStringParam(meta:Null<haxe.macro.Type.MetaAccess>, name:String, index:Int):Null<String> {
		if (meta == null || meta.extract == null) {
			return null;
		}
		var entries = meta.extract(name);
		if (entries.length == 0 || entries[0].params == null || entries[0].params.length <= index) {
			return null;
		}
		return switch (entries[0].params[index].expr) {
			case EConst(CString(value, _)) if (value.length > 0): value;
			case _: null;
		}
	}

	static function validationTargetName(field:ClassVarData):String {
		var explicit = metaStringValue(field.field.meta, ":validates");
		if (explicit != null) {
			return RubyNaming.toMethodName(explicit);
		}
		var name = field.field.name;
		var suffix = "Validation";
		if (StringTools.endsWith(name, suffix) && name.length > suffix.length) {
			name = name.substr(0, name.length - suffix.length);
		}
		return RubyNaming.toMethodName(name);
	}

	static function validationOptions(meta:Null<haxe.macro.Type.MetaAccess>):Array<String> {
		if (meta == null || meta.extract == null) {
			return [];
		}
		var entries = meta.extract(":validates");
		if (entries.length == 0 || entries[0].params == null || entries[0].params.length == 0) {
			return [];
		}
		var params = entries[0].params;
		var options = switch (params[0].expr) {
			case EObjectDecl(_): params[0];
			case _ if (params.length > 1): params[1];
			case _: null;
		}
		return options == null ? [] : metadataObjectOptions(options);
	}

	static function metadataObjectOptions(expr:haxe.macro.Expr):Array<String> {
		return switch (expr.expr) {
			case EObjectDecl(fields):
				[for (field in fields) RubyNaming.toMethodName(field.field) + ": " + metadataValueCode(field.expr)];
			case _:
				[];
		}
	}

	static function metadataValueCode(expr:haxe.macro.Expr):String {
		return switch (expr.expr) {
			case EConst(CIdent("true")): "true";
			case EConst(CIdent("false")): "false";
			case EConst(CIdent("null")): "nil";
			case EConst(CString(value, _)): quoteRubyStringForCode(value);
			case EConst(CInt(value, _)): value;
			case EConst(CFloat(value, _)): value;
			case EArrayDecl(values): "[" + [for (value in values) metadataValueCode(value)].join(", ") + "]";
			case EObjectDecl(fields): "{" + [for (field in fields) RubyNaming.toMethodName(field.field) + ": " + metadataValueCode(field.expr)].join(", ") + "}";
			case _: "nil";
		}
	}

	static function railsColumnBoolOption(meta:Null<haxe.macro.Type.MetaAccess>, name:String, fallback:Bool):Bool {
		var expr = railsColumnOption(meta, name);
		if (expr == null) {
			return fallback;
		}
		return switch (expr.expr) {
			case EConst(CIdent("true")): true;
			case EConst(CIdent("false")): false;
			case _: fallback;
		}
	}

	static function railsColumnStringOption(meta:Null<haxe.macro.Type.MetaAccess>, name:String):Null<String> {
		var expr = railsColumnOption(meta, name);
		if (expr == null) {
			return null;
		}
		return switch (expr.expr) {
			case EConst(CString(value, _)) if (value.length > 0): RubyNaming.toMethodName(value);
			case _: null;
		}
	}

	static function railsColumnValueOption(meta:Null<haxe.macro.Type.MetaAccess>, name:String):Null<String> {
		var expr = railsColumnOption(meta, name);
		return expr == null ? null : metadataValueCode(expr);
	}

	static function railsColumnOption(meta:Null<haxe.macro.Type.MetaAccess>, name:String):Null<haxe.macro.Expr> {
		if (meta == null || meta.extract == null) {
			return null;
		}
		var entries = meta.extract(":railsColumn");
		if (entries.length == 0 || entries[0].params == null || entries[0].params.length == 0) {
			return null;
		}
		return switch (entries[0].params[0].expr) {
			case EObjectDecl(fields):
				var found:Null<haxe.macro.Expr> = null;
				for (field in (fields : Array<RubyMetadataField>)) {
					if (field.field == name) {
						found = field.expr;
						break;
					}
				}
				found;
			case _:
				null;
		}
	}

	static function railsColumnTypeLabel(type:haxe.macro.Type):String {
		return switch (type) {
			case TType(ref, params) if (ref.get().name == "Null" && params.length == 1):
				railsColumnTypeLabel(params[0]);
			case TAbstract(ref, params) if (ref.get().name == "Null" && params.length == 1):
				railsColumnTypeLabel(params[0]);
			case TLazy(lazy):
				railsColumnTypeLabel(lazy());
			case _:
				typeLabel(type);
		}
	}

	static function isNullableType(type:haxe.macro.Type):Bool {
		return switch (type) {
			case TType(ref, _) if (ref.get().name == "Null"): true;
			case TAbstract(ref, _) if (ref.get().name == "Null"): true;
			case TLazy(lazy): isNullableType(lazy());
			case _: false;
		}
	}

	static function railsTypeName(haxeType:String):String {
		return switch (haxeType) {
			case "String": "string";
			case "Bool": "boolean";
			case "Int": "integer";
			case "Float": "float";
			case "Date": "date";
			case "Dynamic": "json";
			case _: RubyNaming.toMethodName(haxeType);
		}
	}

	static function typeLabel(type:haxe.macro.Type):String {
		return switch (type) {
			case TAbstract(ref, _): ref.get().name;
			case TInst(ref, _): ref.get().name;
			case TEnum(ref, _): ref.get().name;
			case TType(ref, _): ref.get().name;
			case TDynamic(_): "Dynamic";
			case TFun(_, _): "Function";
			case TAnonymous(_): "Anonymous";
			case TLazy(lazy): typeLabel(lazy());
			case TMono(_): "Unknown";
		}
	}

	static function rubySymbolLiteral(value:String):String {
		if (isSimpleRubySymbol(value)) {
			return ":" + value;
		}
		var escaped = value == null ? "" : value;
		escaped = StringTools.replace(escaped, "\\", "\\\\");
		escaped = StringTools.replace(escaped, "\"", "\\\"");
		return ":\"" + escaped + "\"";
	}

	static function isSimpleRubySymbol(value:String):Bool {
		if (value == null || value.length == 0) {
			return false;
		}
		var first = value.charCodeAt(0);
		if (!isRubyIdentStart(first)) {
			return false;
		}
		var limit = value.length;
		var last = value.charAt(value.length - 1);
		if (last == "!" || last == "?" || last == "=") {
			limit--;
		}
		for (i in 1...limit) {
			if (!isRubyIdentPart(value.charCodeAt(i))) {
				return false;
			}
		}
		return true;
	}

	static function isRubyIdentStart(code:Int):Bool {
		return code == 95 || (code >= 65 && code <= 90) || (code >= 97 && code <= 122);
	}

	static function isRubyIdentPart(code:Int):Bool {
		return isRubyIdentStart(code) || (code >= 48 && code <= 57);
	}

	static function localName(v:TVar):String {
		return RubyNaming.toLocalName(v.name) + "__hx" + v.id;
	}

	static function loopIteratorName(v:TVar, iterable:TypedExpr):String {
		var pos = Context.getPosInfos(iterable.pos);
		return "__hx_iter_" + localName(v) + "_" + pos.min;
	}

	static function binopToRuby(op:haxe.macro.Expr.Binop):String {
		return switch (op) {
			case OpAdd: "+";
			case OpSub: "-";
			case OpMult: "*";
			case OpDiv: "/";
			case OpMod: "%";
			case OpEq: "==";
			case OpNotEq: "!=";
			case OpGt: ">";
			case OpGte: ">=";
			case OpLt: "<";
			case OpLte: "<=";
			case OpBoolAnd: "&&";
			case OpBoolOr: "||";
			case OpAnd: "&";
			case OpOr: "|";
			case OpXor: "^";
			case OpShl: "<<";
			case OpShr | OpUShr: ">>";
			case OpAssign: "=";
			case OpAssignOp(inner): binopToRuby(inner);
			case _: "+";
		}
	}

	static function unopToRuby(op:haxe.macro.Expr.Unop):String {
		return switch (op) {
			case OpNot: "!";
			case OpNeg | OpNegBits: "-";
			case OpIncrement | OpDecrement: "";
			case _: "";
		}
	}

	static function printInlineExpr(expr:TypedExpr):String {
		return reflaxe.ruby.ast.RubyASTPrinter.printExpr(compileExpr(expr));
	}

	static function lambdaBody(expr:TypedExpr):String {
		return switch (expr.expr) {
			case TReturn(value):
				value == null ? "nil" : printInlineExpr(value);
			case TBlock(exprs) if (exprs.length > 0):
				lambdaBody(exprs[exprs.length - 1]);
			case _:
				printInlineExpr(expr);
		}
	}

	static function quoteRubyStringForCode(value:String):String {
		var escaped = value == null ? "" : value;
		escaped = StringTools.replace(escaped, "\\", "\\\\");
		escaped = StringTools.replace(escaped, "\"", "\\\"");
		return "\"" + escaped + "\"";
	}

	static function statementToInlineRuby(statement:RubyStatement):String {
		return switch (statement) {
			case RubyExprStatement(expr): reflaxe.ruby.ast.RubyASTPrinter.printExpr(expr);
			case RubyAssign(target, value): reflaxe.ruby.ast.RubyASTPrinter.printExpr(target) + " = " + reflaxe.ruby.ast.RubyASTPrinter.printExpr(value);
			case RubyReturn(value): value == null ? "return" : "return " + reflaxe.ruby.ast.RubyASTPrinter.printExpr(value);
			case RubyIfStmt(cond, thenBody, elseBody):
				var lines = ["if " + reflaxe.ruby.ast.RubyASTPrinter.printExpr(cond)];
				appendIndentedLines(lines, renderStatements(thenBody), 1);
				if (elseBody != null && elseBody.length > 0) {
					lines.push("else");
					appendIndentedLines(lines, renderStatements(elseBody), 1);
				}
				lines.push("end");
				lines.join("\n");
			case RubyWhileStmt(cond, body):
				var lines = ["while " + reflaxe.ruby.ast.RubyASTPrinter.printExpr(cond)];
				appendIndentedLines(lines, renderStatements(body), 1);
				lines.push("end");
				lines.join("\n");
			case RubyRawStatement(code): code;
			case RubyComment(text): "# " + text;
			case _: "# TODO: inline statement";
		}
	}

	static function RubyNilStatement():RubyStatement {
		return RubyExprStatement(RubyNil);
	}
}
#else
class RubyCompiler {
	public function new() {}
}
#end
