# Generated by reflaxe.ruby
$LOAD_PATH.unshift(__dir__)
require "action_controller/railtie"
require_relative "app/lib/railshx/runtime/hxruby/core"
require_relative "app/controllers/mixed_controller"
require_relative "app/lib/railshx/generated/main"
require_relative "app/lib/railshx/generated/services/typed_stats"
Main.main
