# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
module BlogEngine
  module Services
    class EngineGreeting
      def self.__hx_name()
        "blog_engine.services.EngineGreeting"
      end
      def self.message(name)
        return ("RailsHx engine says hello to " + name)
      end
    end
  end
end
