# Generated by reflaxe.ruby
# Placeholder output; lowering is implemented by later compiler beads.
class Counter
  class << self
    attr_accessor :value
  end
  @value = 0
  def self.next_()
    Counter.value = (Counter.value + 1)
    return Counter.value
  end
end
