# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Counter
  def self.__hx_name()
    "Counter"
  end
  class << self
    attr_accessor :value
  end
  @value = 0
  def self.next_()
    Counter.value = (Counter.value + 1)
    return Counter.value
  end
end
