# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "hxruby/core"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.main()
    Counter.value = 1
    puts(HXRuby.stringify(Counter.next_()))
    puts(HXRuby.stringify(Counter.label))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  Main.main()
end
