# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class Main
  def self.main()
    Counter.value = 1
    puts(HXRuby.stringify(Counter.next_()))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  require_relative "hxruby/core"
  Main.main()
end
