# Generated by reflaxe.ruby
# Rails model output; Zeitwerk path should match the Ruby constant.
require "active_record"
class AuditLog < ApplicationRecord
  self.table_name = "audit_logs"
  # haxe column event_count: Int
  def initialize(*args, **kwargs)
    args = args + [kwargs] unless kwargs.empty?
    super(*args)
  end
end
