# Generated by reflaxe.ruby
# Rails model output; Zeitwerk path should match the Ruby constant.
require "active_record"
class Todo < ApplicationRecord
  self.table_name = "todos"
  belongs_to :user, optional: false, foreign_key: "user_id", inverse_of: :todos
  enum :status, {open: "open", done: "done"}
  scope :incomplete, -> { where(completed: false) }
  scope :with_status, ->(status) { where(status: status) }
  default_scope -> { order(title: :asc) }
  # haxe column id: Int
  # haxe column title: String
  # haxe column completed: Bool
  # haxe column status: String
  # haxe column notes: Null
  # haxe column external_id: String
  # haxe column user_id: Int
  validates :title, presence: true, length: {minimum: 3}
  validates :notes, length: {maximum: 500}, allow_nil: true
  validates :external_id, presence: true, uniqueness: true, format: {with: /\A[a-z0-9-]+\z/}
  validates :status, inclusion: {within: ["open", "done"]}
  validates :user_id, numericality: {only_integer: true, greater_than: 0}
  before_validation :normalize_title
  after_commit :publish_lifecycle_event
  def initialize(*args, **kwargs)
    args = args + [kwargs] unless kwargs.empty?
    super(*args)
  end
  def normalize_title()
    nil
  end
  def publish_lifecycle_event()
    nil
  end
end
