# Generated by reflaxe.ruby
# Rails model output; Zeitwerk path should match the Ruby constant.
require "active_record"
class User < ApplicationRecord
  self.table_name = "users"
  has_many :todos, dependent: :destroy, inverse_of: :user
  has_many :todo_owners, through: :todos, source: :user
  # haxe column id: Int
  # haxe column name: String
  validates :name, exclusion: {within: ["admin", "root", "system"]}
  def initialize(*args, **kwargs)
    args = args + [kwargs] unless kwargs.empty?
    super(*args)
  end
end
