# Generated by reflaxe.ruby
# Rails job output; Zeitwerk path should match the Ruby constant.
require "active_job/railtie"
class DiscardProbeJob < ActiveJob::Base
  queue_as :critical
  discard_on ActiveJob::DeserializationError
  def perform(record_id)
    (raise ActiveJob::DeserializationError.new(("discard:" + record_id.to_s())))
  end
end
