# Generated by reflaxe.ruby
# Rails job output; Zeitwerk path should match the Ruby constant.
require "active_job/railtie"
require_relative "../lib/railshx/runtime/hxruby/core"
class DiscardProbeJob < ActiveJob::Base
  queue_as :critical
  discard_on ActiveJob::DeserializationError
  def perform(record_id)
    (raise ActiveJob::DeserializationError.new(("discard:" + HXRuby.stringify(record_id))))
  end
end
