# Generated by reflaxe.ruby
# Rails job output; Zeitwerk path should match the Ruby constant.
require "active_job/railtie"
class SendWelcomeEmailJob < ActiveJob::Base
  queue_as :mailers
  retry_on StandardError, wait: 5.seconds, attempts: 3
  discard_on ActiveJob::DeserializationError
  def perform(user_id, email)
    payload = ("welcome:" + email)
    Haxe::Log.trace(payload, {"fileName" => "jobs/SendWelcomeEmailJob.hx", "lineNumber" => 32, "className" => "jobs.SendWelcomeEmailJob", "methodName" => "perform"})
  end
end
