# Generated by RailsHx from @:railsRoutes.
# Source: routes.AppRoutes
# Do not edit directly unless you intend to take RailsHx ownership.

Rails.application.routes.draw do
  root "controllers/posts#index"
  get "posts/archive", to: "controllers/posts#archive", as: :archived_posts
  post "posts", to: "controllers/posts#create"
  match "posts/search", to: "controllers/posts#search", via: [:get, :post], as: :post_search
  get "photos(/:id)", to: "controllers/posts#show_optional", as: :photo_display
  get "files/*path", to: "controllers/posts#file", as: :file
  get "legacy/posts/:id", to: "legacy/posts#show", as: :legacy_post
  mount Sidekiq::Web => "/sidekiq", as: :sidekiq
  defaults format: "json" do
    constraints id: /[0-9]+/ do
      get "numeric_posts/:id", to: "controllers/posts#show", as: :numeric_post
    end
  end
  resources :posts, controller: "controllers/posts", except: [:destroy], param: :slug do
    collection do
      get "archived", to: "controllers/posts#archive", as: :archived_collection
    end
    member do
      patch "publish", to: "controllers/posts#publish", as: :publish_post
    end
  end
  resources :draft_posts, controller: "controllers/posts", only: [:new]
  resource :profile, controller: "controllers/profiles", only: [:show, :update]
  namespace :admin do
    get "posts/audit", to: "controllers/admin/posts#audit", as: :admin_post_audit
  end
  scope "/api", module: "api", as: :api do
    get "status", to: "controllers/health#show", as: :status
  end
  controller "controllers/health" do
    get "up", to: "controllers/health#show", as: :health
  end
end
