package reflaxe.ruby.rails;

import reflaxe.ruby.ast.RubyAST.RubyExpr;

/** The two Haxe map key representations supported by grouped ActiveRecord counts. **/
enum RailsActiveRecordGroupCountKeyKind {
	StringKey;
	IntKey;
}

/**
	Builds the Ruby-side result adapters for typed ActiveRecord queries.

	ActiveRecord returns arrays for multi-field `pluck` calls and hashes for
	grouped counts, while the Haxe APIs promise named row objects and typed Haxe
	maps. This service owns only that Rails-specific structural Ruby conversion.
	The compiler still validates model fields and result types before calling it.
**/
class RailsActiveRecordResultLowering {
	/** Renders the Rails bootstrap that loads this focused runtime ABI. **/
	public static function runtimeInitializer(corePath:String, mapsPath:String, quote:String->String):String {
		return [
			"# Generated by reflaxe.ruby",
			"# Grouped ActiveRecord results require the typed Haxe map ABI.",
			"require Rails.root.join(" + quote(corePath) + ")",
			"require Rails.root.join(" + quote(mapsPath) + ")",
			""
		].join("\n");
	}

	/** Maps the macro-owned ABI literal to the closed lowering decision. **/
	public static function groupCountKeyKind(value:Null<String>):Null<RailsActiveRecordGroupCountKeyKind> {
		return switch value {
			case "string": StringKey;
			case "int": IntKey;
			case _: null;
		};
	}

	/**
		Converts each pluck row into a fixed string-key hash.

		A one-column pluck may yield a scalar, so the block first normalizes the
		row to an array. Compiler-allocated names keep the generated block from
		capturing or overwriting a Haxe local with the same friendly name.
	**/
	public static function projection(rows:RubyExpr, keys:Array<String>, rowName:String, valuesName:String):RubyExpr {
		var row = RubyLocal(rowName);
		var values = RubyLocal(valuesName);
		return RubyCallableCall(rows, "map", [], {
			args: [rowName],
			body: [
				RubyAssign(values, RubyConditional(RubyCall(row, "is_a?", [RubyConstantPath("Array")]), row, RubyArray([row]))),
				RubyExprStatement(RubyHash([
					for (index => key in keys)
						{key: key, value: RubyIndex(values, RubyInt(Std.string(index)))}
				]))
			]
		});
	}

	/**
		Converts ActiveRecord's grouped-count hash into the promised Haxe map.

		A simple `entry` block parameter plus structural indexing preserves Ruby's
		key/value yield without adding a special block-destructuring AST shape.
	**/
	public static function groupedCount(counts:RubyExpr, keyKind:RailsActiveRecordGroupCountKeyKind, entryName:String, mapName:String):RubyExpr {
		var entry = RubyLocal(entryName);
		var map = RubyLocal(mapName);
		var key = RubyIndex(entry, RubyInt("0"));
		var value = RubyIndex(entry, RubyInt("1"));
		var mapPlan = switch keyKind {
			case StringKey: {mapClass: "Haxe::Ds::StringMap", keyMethod: "to_s"};
			case IntKey: {mapClass: "Haxe::Ds::IntMap", keyMethod: "to_i"};
		};
		return RubyCallableCall(counts, "each_with_object", [RubyPositionalArgument(RubyCall(RubyConstantPath(mapPlan.mapClass), "new", []))], {
			args: [entryName, mapName],
			body: [
				RubyExprStatement(RubyCall(map, "set", [RubyCall(key, mapPlan.keyMethod, []), RubyCall(value, "to_i", [])]))
			]
		});
	}
}
