package reflaxe.ruby.rails;

#if (macro || reflaxe_runtime)
import haxe.macro.Context;
import haxe.macro.Expr;
import haxe.macro.Type.ClassType;
import reflaxe.ruby.naming.RubyNaming;

typedef RailsTestArtifactPlan = {
	var outputPath:String;
	var adapter:RailsTestAdapter;
	var className:String;
	var requestTest:Bool;
}

/**
	Owns `@:railsTest` metadata, output identity, duplicate detection, and native
	Rails test-file rendering.

	RubyCompiler still lowers typed test bodies because that work shares the Ruby
	expression pipeline. This service accepts only the rendered body and include
	lines, so Rails artifact policy cannot depend back on the compiler root.
**/
class RailsTestArtifacts {
	var emittedPaths:Map<String, String> = new Map<String, String>();

	public function new() {}

	/** Clears per-compilation duplicate tracking before Reflaxe starts a new run. **/
	public function reset():Void {
		emittedPaths = new Map<String, String>();
	}

	/** Validates one test declaration and returns its complete native artifact identity. **/
	public function prepare(classType:ClassType, railsMode:Bool):Null<RailsTestArtifactPlan> {
		if (!railsMode) {
			Context.error("@:railsTest requires -D reflaxe_ruby_rails.", classType.pos);
			return null;
		}
		var adapter = adapterFor(classType);
		var testPath = metadataStringParam(classType.meta, ":railsTest", 0);
		if (testPath == null) {
			Context.error("@:railsTest expects a Rails test path string such as \"models/todo_haxe_test\".", classType.pos);
			return null;
		}
		var outputPath = switch (adapter) {
			case RailsMinitest:
				RailsArtifactPaths.validateTestPath(testPath, classType.pos, "@:railsTest");
				RailsArtifactPaths.testOutputPath(testPath);
			case RailsRspec:
				RailsArtifactPaths.validateSpecPath(testPath, classType.pos, "@:railsTest");
				RailsArtifactPaths.specOutputPath(testPath);
		}
		if (emittedPaths.exists(outputPath)) {
			Context.error('@:railsTest emits duplicate test/spec file ${outputPath}; first emitted by ${emittedPaths.get(outputPath)}.', classType.pos);
			return null;
		}
		emittedPaths.set(outputPath, fullTypeName(classType.pack, classType.name));
		return {
			outputPath: outputPath,
			adapter: adapter,
			className: RubyNaming.toConstantName(classType.name),
			requestTest: extendsType(classType, "rails.test.RequestTestCase")
		};
	}

	/** Renders byte-stable Minitest or RSpec source around compiler-lowered bodies. **/
	public static function render(plan:RailsTestArtifactPlan, body:Array<String>, includes:Array<String>):Array<String> {
		return switch (plan.adapter) {
			case RailsMinitest:
				var lines = ["# Generated by RailsHx from @:railsTest.",
					"require \"test_helper\"",
					"",
					"class "
					+ plan.className
					+ " < "
					+ (plan.requestTest ? "ActionDispatch::IntegrationTest" : "ActiveSupport::TestCase")];
				appendIncludesAndBody(lines, includes, body);
				lines;
			case RailsRspec:
				var lines = ["# Generated by RailsHx from @:railsTest.",
					"require \"rails_helper\"",
					"",
					"RSpec.describe "
					+ quoteRubyStringForCode(plan.className)
					+ ", type: :"
					+ (plan.requestTest ? "request" : "model")
					+ " do"];
				appendIncludesAndBody(lines, includes, body);
				lines;
		}
	}

	static function adapterFor(classType:ClassType):RailsTestAdapter {
		var value = metadataStringParam(classType.meta, ":railsTestAdapter", 0);
		return switch (value) {
			case null | "rails.minitest" | "minitest":
				RailsMinitest;
			case "rails.rspec" | "rspec":
				RailsRspec;
			case _:
				Context.error('@:railsTestAdapter must be "rails.minitest" or "rails.rspec".', classType.pos);
				RailsMinitest;
		}
	}

	static function appendIncludesAndBody(lines:Array<String>, includes:Array<String>, body:Array<String>):Void {
		for (moduleName in includes) {
			lines.push("  include " + moduleName);
		}
		for (line in body) {
			lines.push("  " + line);
		}
		lines.push("end");
	}

	static function extendsType(classType:ClassType, expectedFullName:String):Bool {
		var cursor = classType.superClass;
		while (cursor != null) {
			var superClass = cursor.t.get();
			if (fullTypeName(superClass.pack, superClass.name) == expectedFullName) {
				return true;
			}
			cursor = superClass.superClass;
		}
		return false;
	}

	static function metadataStringParam(meta:Null<haxe.macro.Type.MetaAccess>, name:String, index:Int):Null<String> {
		if (meta == null || meta.extract == null) {
			return null;
		}
		var entries = meta.extract(name);
		if (entries.length == 0 || entries[0].params == null || entries[0].params.length <= index) {
			return null;
		}
		return switch (entries[0].params[index].expr) {
			case EConst(CString(value, _)) if (value.length > 0): value;
			case _: null;
		}
	}

	static function fullTypeName(pack:Array<String>, name:String):String {
		return pack == null || pack.length == 0 ? name : pack.concat([name]).join(".");
	}

	static function quoteRubyStringForCode(value:String):String {
		var escaped = value == null ? "" : value;
		escaped = StringTools.replace(escaped, "\\", "\\\\");
		escaped = StringTools.replace(escaped, "\"", "\\\"");
		return "\"" + escaped + "\"";
	}
}
#end
