package reflaxe.ruby.rails;

#if (macro || reflaxe_runtime)
import haxe.macro.Context;
import haxe.macro.Expr;
import haxe.macro.Type.ClassType;
import reflaxe.data.ClassFuncData;
import reflaxe.ruby.naming.RubyNaming;

typedef RailsMailerPreviewArtifactPlan = {
	var outputPath:String;
	var className:String;
}

/**
	Owns `@:railsMailerPreview` metadata, output identity, method validation,
	duplicate detection, and Rails-native preview-file rendering.

	The compiler root supplies already-rendered Ruby methods and retains the
	owned-file write boundary; this service has no dependency on RubyCompiler.
**/
class RailsMailerPreviewArtifacts {
	var emittedPaths:Map<String, String> = new Map<String, String>();

	public function new() {}

	/** Clears per-compilation duplicate tracking before Reflaxe starts a new run. **/
	public function reset():Void {
		emittedPaths = new Map<String, String>();
	}

	/** Validates one preview declaration and returns its native artifact identity. **/
	public function prepare(classType:ClassType, railsMode:Bool):Null<RailsMailerPreviewArtifactPlan> {
		if (!railsMode) {
			Context.error("@:railsMailerPreview requires -D reflaxe_ruby_rails.", classType.pos);
			return null;
		}
		var previewPath = metadataStringParam(classType.meta, ":railsMailerPreview", 0);
		if (previewPath == null) {
			previewPath = RubyNaming.fileName(classType.name);
		}
		RailsArtifactPaths.validateMailerPreviewPath(previewPath, classType.pos, "@:railsMailerPreview");
		var outputPath = RailsArtifactPaths.mailerPreviewOutputPath(previewPath);
		if (emittedPaths.exists(outputPath)) {
			Context.error('@:railsMailerPreview emits duplicate preview file ${outputPath}; first emitted by ${emittedPaths.get(outputPath)}.', classType.pos);
			return null;
		}
		emittedPaths.set(outputPath, fullTypeName(classType.pack, classType.name));
		return {
			outputPath: outputPath,
			className: RubyNaming.toConstantName(classType.name)
		};
	}

	/** Enforces the zero-argument instance-method shape Rails preview discovery expects. **/
	public static function validateMethod(field:ClassFuncData):Void {
		if (field.isStatic) {
			Context.error("@:railsMailerPreview methods must be instance methods so Rails can expose them as previews.", field.field.pos);
		}
		if (field.args.length > 0) {
			Context.error("@:railsMailerPreview methods must not declare parameters; build preview inputs inside the method body.", field.field.pos);
		}
	}

	/** Renders byte-stable ActionMailer preview source around compiler-lowered methods. **/
	public static function render(plan:RailsMailerPreviewArtifactPlan, body:Array<String>):Array<String> {
		var lines = [
			"# Generated by RailsHx from @:railsMailerPreview.",
			"# Rails preview output; Rails discovers this under test/mailers/previews.",
			"require \"action_mailer/railtie\"",
			"",
			"class " + plan.className + " < ActionMailer::Preview"
		];
		for (line in body) {
			lines.push("  " + line);
		}
		lines.push("end");
		return lines;
	}

	static function metadataStringParam(meta:Null<haxe.macro.Type.MetaAccess>, name:String, index:Int):Null<String> {
		if (meta == null || meta.extract == null) {
			return null;
		}
		var entries = meta.extract(name);
		if (entries.length == 0 || entries[0].params == null || entries[0].params.length <= index) {
			return null;
		}
		return switch (entries[0].params[index].expr) {
			case EConst(CString(value, _)) if (value.length > 0): value;
			case _: null;
		}
	}

	static function fullTypeName(pack:Array<String>, name:String):String {
		return pack == null || pack.length == 0 ? name : pack.concat([name]).join(".");
	}
}
#end
