package reflaxe.ruby.rails;

#if (macro || reflaxe_runtime)
import haxe.macro.Context;
import haxe.macro.Expr;
import haxe.macro.Type.ClassType;
import haxe.macro.Type;
import haxe.macro.TypeTools;
import reflaxe.ruby.naming.RubyNaming;

typedef RailsTestArtifactPlan = {
	var outputPath:String;
	var adapter:RailsTestAdapter;
	var className:String;
	var kind:RailsTestArtifactKind;
}

enum RailsTestArtifactKind {
	ModelTest;
	RequestTest;
	ChannelTest(channelName:String);
}

/**
	Owns `@:railsTest` metadata, output identity, duplicate detection, and native
	Rails test-file rendering.

	RubyCompiler still lowers typed test bodies because that work shares the Ruby
	expression pipeline. This service accepts only the rendered body and include
	lines, so Rails artifact policy cannot depend back on the compiler root.
**/
class RailsTestArtifacts {
	var emittedPaths:Map<String, String> = new Map<String, String>();

	public function new() {}

	/** Clears per-compilation duplicate tracking before Reflaxe starts a new run. **/
	public function reset():Void {
		emittedPaths = new Map<String, String>();
	}

	/** Validates one test declaration and returns its complete native artifact identity. **/
	public function prepare(classType:ClassType, railsMode:Bool):Null<RailsTestArtifactPlan> {
		if (!railsMode) {
			Context.error("@:railsTest requires -D reflaxe_ruby_rails.", classType.pos);
			return null;
		}
		var adapter = adapterFor(classType);
		var testPath = metadataStringParam(classType.meta, ":railsTest", 0);
		if (testPath == null) {
			Context.error("@:railsTest expects a Rails test path string such as \"models/todo_haxe_test\".", classType.pos);
			return null;
		}
		var outputPath = switch (adapter) {
			case RailsMinitest:
				RailsArtifactPaths.validateTestPath(testPath, classType.pos, "@:railsTest");
				RailsArtifactPaths.testOutputPath(testPath);
			case RailsRspec:
				RailsArtifactPaths.validateSpecPath(testPath, classType.pos, "@:railsTest");
				RailsArtifactPaths.specOutputPath(testPath);
		}
		if (emittedPaths.exists(outputPath)) {
			Context.error('@:railsTest emits duplicate test/spec file ${outputPath}; first emitted by ${emittedPaths.get(outputPath)}.', classType.pos);
			return null;
		}
		emittedPaths.set(outputPath, fullTypeName(classType.pack, classType.name));
		var channelName = channelTestName(classType);
		if (channelName != null && adapter != RailsMinitest) {
			Context.error("@:railsChannelTest currently supports only the rails.minitest adapter because RailsHx has no verified RSpec ActionCable channel-test contract.",
				classType.pos);
		}
		return {
			outputPath: outputPath,
			adapter: adapter,
			className: RubyNaming.toConstantName(classType.name),
			kind: channelName != null ? ChannelTest(channelName) : (extendsType(classType, "rails.test.RequestTestCase") ? RequestTest : ModelTest)
		};
	}

	/** Renders byte-stable Minitest or RSpec source around compiler-lowered bodies. **/
	public static function render(plan:RailsTestArtifactPlan, body:Array<String>, includes:Array<String>):Array<String> {
		return switch (plan.adapter) {
			case RailsMinitest:
				var baseClass = switch (plan.kind) {
					case ModelTest: "ActiveSupport::TestCase";
					case RequestTest: "ActionDispatch::IntegrationTest";
					case ChannelTest(_): "ActionCable::Channel::TestCase";
				}
				var lines = [
					"# Generated by RailsHx from @:railsTest.",
					"require \"test_helper\"",
					"",
					"class " + plan.className + " < " + baseClass
				];
				switch (plan.kind) {
					case ChannelTest(channelName):
						lines.push("  tests " + channelName);
					case _:
				}
				appendIncludesAndBody(lines, includes, body);
				lines;
			case RailsRspec:
				var lines = ["# Generated by RailsHx from @:railsTest.",
					"require \"rails_helper\"",
					"",
					"RSpec.describe "
					+ quoteRubyStringForCode(plan.className)
					+ ", type: :"
					+ (plan.kind == RequestTest ? "request" : "model")
					+ " do"];
				appendIncludesAndBody(lines, includes, body);
				lines;
		}
	}

	/**
		Resolve the explicit channel owner for an ActionCable channel test.

		Rails cannot always infer the channel from a generated test class name, so
		`@:railsChannelTest(ChannelType)` records the same binding as Rails'
		`tests ChannelType`. Requiring an actual `@:railsChannel` type prevents a
		string from drifting away from the compiled channel contract.
	**/
	static function channelTestName(classType:ClassType):Null<String> {
		var entries = classType.meta.extract(":railsChannelTest");
		if (entries.length == 0) {
			if (extendsType(classType, "rails.test.ChannelTestCase")) {
				Context.error("Classes extending rails.test.ChannelTestCase must declare @:railsChannelTest(ChannelType).", classType.pos);
			}
			return null;
		}
		if (!extendsType(classType, "rails.test.ChannelTestCase")) {
			Context.error("@:railsChannelTest is only valid on a class extending rails.test.ChannelTestCase<TParams, TPayload>.", classType.pos);
		}
		if (entries[0].params == null || entries[0].params.length != 1) {
			Context.error("@:railsChannelTest expects one @:railsChannel type, for example @:railsChannelTest(TodosChannel).", entries[0].pos);
		}
		var channelExpr = entries[0].params[0];
		var channelClass = switch (typePath(channelExpr.expr)) {
			case null: null;
			case path:
				switch (Context.getType(path)) {
					case TInst(ref, _): ref.get();
					case _: null;
				}
		}
		if (channelClass == null || !channelClass.meta.has(":railsChannel")) {
			Context.error("@:railsChannelTest expects a class annotated with @:railsChannel.", channelExpr.pos);
		}
		validateChannelContract(classType, channelClass, channelExpr.pos);
		return RubyNaming.toConstantName(channelClass.name);
	}

	/**
		Prove that the test's generic params/payload are the selected channel's
		actual contract. Without this check a test could compile with convenient
		but false types while Rails exercised a different channel signature.
	**/
	static function validateChannelContract(testClass:ClassType, channelClass:ClassType, pos:Position):Void {
		var testContract = inheritedTypeArgs(testClass, "rails.test.ChannelTestCase");
		var channelContract = inheritedTypeArgs(channelClass, "rails.action_cable.Channel");
		if (testContract == null || channelContract == null || testContract.length != 2 || channelContract.length != 2) {
			Context.error("@:railsChannelTest could not resolve both ChannelTestCase<TParams, TPayload> and Channel<TParams, TPayload> contracts.", pos);
		}
		for (index in 0...2) {
			if (TypeTools.toString(Context.follow(testContract[index])) != TypeTools.toString(Context.follow(channelContract[index]))) {
				Context.error("@:railsChannelTest generic params and payload must exactly match the selected @:railsChannel contract.", pos);
			}
		}
	}

	static function inheritedTypeArgs(classType:ClassType, expectedFullName:String):Null<Array<Type>> {
		var cursor = classType.superClass;
		while (cursor != null) {
			var superClass = cursor.t.get();
			var actualParams = cursor.params;
			if (fullTypeName(superClass.pack, superClass.name) == expectedFullName) {
				return actualParams;
			}
			if (superClass.superClass == null) {
				return null;
			}
			var parent = superClass.superClass;
			cursor = {
				t: parent.t,
				params: [
					for (parentParam in parent.params)
						TypeTools.applyTypeParameters(parentParam, superClass.params, actualParams)
				]
			};
		}
		return null;
	}

	static function typePath(expr:ExprDef):Null<String> {
		return switch (expr) {
			case EConst(CIdent(name)): name;
			case EField(owner, name):
				var prefix = typePath(owner.expr);
				prefix == null ? null : prefix + "." + name;
			case _: null;
		}
	}

	static function adapterFor(classType:ClassType):RailsTestAdapter {
		var value = metadataStringParam(classType.meta, ":railsTestAdapter", 0);
		return switch (value) {
			case null | "rails.minitest" | "minitest":
				RailsMinitest;
			case "rails.rspec" | "rspec":
				RailsRspec;
			case _:
				Context.error('@:railsTestAdapter must be "rails.minitest" or "rails.rspec".', classType.pos);
				RailsMinitest;
		}
	}

	static function appendIncludesAndBody(lines:Array<String>, includes:Array<String>, body:Array<String>):Void {
		for (moduleName in includes) {
			lines.push("  include " + moduleName);
		}
		for (line in body) {
			lines.push("  " + line);
		}
		lines.push("end");
	}

	static function extendsType(classType:ClassType, expectedFullName:String):Bool {
		var cursor = classType.superClass;
		while (cursor != null) {
			var superClass = cursor.t.get();
			if (fullTypeName(superClass.pack, superClass.name) == expectedFullName) {
				return true;
			}
			cursor = superClass.superClass;
		}
		return false;
	}

	static function metadataStringParam(meta:Null<haxe.macro.Type.MetaAccess>, name:String, index:Int):Null<String> {
		if (meta == null || meta.extract == null) {
			return null;
		}
		var entries = meta.extract(name);
		if (entries.length == 0 || entries[0].params == null || entries[0].params.length <= index) {
			return null;
		}
		return switch (entries[0].params[index].expr) {
			case EConst(CString(value, _)) if (value.length > 0): value;
			case _: null;
		}
	}

	static function fullTypeName(pack:Array<String>, name:String):String {
		return pack == null || pack.length == 0 ? name : pack.concat([name]).join(".");
	}

	static function quoteRubyStringForCode(value:String):String {
		var escaped = value == null ? "" : value;
		escaped = StringTools.replace(escaped, "\\", "\\\\");
		escaped = StringTools.replace(escaped, "\"", "\\\"");
		return "\"" + escaped + "\"";
	}
}
#end
