# Generated by reflaxe.ruby
$LOAD_PATH.unshift(__dir__)
require_relative "engines/blog/app/haxe_gen/hxruby/core"
require_relative "engines/blog/app/haxe_gen/blog_engine/services/engine_greeting"
require_relative "engines/blog/app/haxe_gen/main"
Main.main
