# Generated by reflaxe.ruby
# Rails model output; Zeitwerk path should match the Ruby constant.
require "active_record"
module Models
  class Todo < ::ApplicationRecord
    self.table_name = "todos"
    def self.__hx_rails_schema()
      {
        table_name: "todos",
        timestamps: true,
        columns: [
          {name: :id, haxe_name: "id", ruby_name: "id", haxe_type: "Int", rails_type: :bigint, nullable: false, default: nil, primary_key: true, index: false, unique: false, db_type: :bigint},
          {name: :title, haxe_name: "title", ruby_name: "title", haxe_type: "String", rails_type: :string, nullable: false, default: nil, primary_key: false, index: true, unique: false, db_type: nil},
          {name: :notes, haxe_name: "notes", ruby_name: "notes", haxe_type: "String", rails_type: :text, nullable: false, default: "", primary_key: false, index: false, unique: false, db_type: :text},
          {name: :is_completed, haxe_name: "isCompleted", ruby_name: "is_completed", haxe_type: "Bool", rails_type: :boolean, nullable: false, default: false, primary_key: false, index: false, unique: false, db_type: nil},
          {name: :user_id, haxe_name: "userId", ruby_name: "user_id", haxe_type: "Int", rails_type: :integer, nullable: false, default: nil, primary_key: false, index: true, unique: false, db_type: nil}
        ]
      }
    end
    def self.typed_column_count()
      __hx_rails_schema()[:columns].length
    end
    belongs_to :user, optional: false, foreign_key: "user_id", inverse_of: :todos
    # haxe column id: Int
    # haxe column title: String
    # haxe column notes: String
    # haxe column is_completed: Bool
    # haxe column user_id: Int
    validates :title, presence: true
    validates :user_id, numericality: {only_integer: true, greater_than: 0}
    before_validation :normalize_title
    def initialize(*args, **kwargs)
      args = args + [kwargs] unless kwargs.empty?
      super(*args)
    end
    def normalize_title()
      if (self.title != nil)
        self.title = self.title.strip()
      end
      if (self.notes != nil)
        self.notes = self.notes.strip()
      end
    end
    def self.incomplete()
      return Models::Todo.where(is_completed: false)
    end
  end
end
