# Generated by reflaxe.ruby
# Rails model output; Zeitwerk path should match the Ruby constant.
require "active_record"
module Models
  class Todo < ActiveRecord::Base
    self.table_name = "todos"
    belongs_to :user
    # haxe column title: String
    # haxe column is_completed: Bool
    # haxe column user_id: Int
    validates :title, presence: true
    def initialize()
      super()
    end
    def self.incomplete()
      return Models::Todo.where(is_completed: false)
    end
  end
end
