# Generated by reflaxe.ruby
# Rails model output; Zeitwerk path should match the Ruby constant.
require "active_record"
module Models
  class User < ActiveRecord::Base
    self.table_name = "users"
    has_many :todos
    # haxe column name: String
    validates :name, presence: true
    def initialize()
      super()
    end
  end
end
