# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
module Services
  class TypedStats
    def self.__hx_name()
      "services.TypedStats"
    end
    def self.summary(items__hx0)
      return (("Typed Haxe summarized " + items__hx0.length) + " Rails surfaces.")
    end
    def self.confidence_label()
      return "Ruby called a generated Haxe service with no adapter."
    end
  end
end
