# Generated by reflaxe.ruby
# Rails mailer output; Zeitwerk path should match the Ruby constant.
require "action_mailer/railtie"
class UserMailer < ActionMailer::Base
  def welcome(email, name, message)
    self.attachments()["welcome.txt"] = message
    self.attachments().inline()["welcome.csv"] = {content: ((("name,message\n" + name) + ",") + message), mime_type: "text/csv"}
    locals_product_name = nil
    locals_name = nil
    locals_message = nil
    locals_name = name
    locals_message = message
    locals_product_name = "RailsHx"
    self.mail(to: email, from: "team@example.test", cc: ["ops@example.test"], reply_to: "reply@example.test", subject: "Welcome to typed RailsHx mail", layout: false) do |format|
      format.html { self.render(template: "mailers/user_mailer/welcome", locals: {message: locals_message, name: locals_name, product_name: locals_product_name}) }
      format.text { self.render(template: "mailers/user_mailer/welcome.text", locals: {message: locals_message, name: locals_name, product_name: locals_product_name}) }
    end
  end
  def welcome_from_params()
    email = params[:email]
    name = params[:name]
    message = params[:message]
    self.attachments()["welcome.txt"] = message
    self.attachments().inline()["welcome.csv"] = {content: ((("name,message\n" + name) + ",") + message), mime_type: "text/csv"}
    locals_product_name = nil
    locals_name = nil
    locals_message = nil
    locals_name = name
    locals_message = message
    locals_product_name = "RailsHx"
    return self.mail(to: email, from: "team@example.test", cc: ["ops@example.test"], reply_to: "reply@example.test", subject: "Welcome to typed RailsHx parameterized mail", layout: false) do |format|
      format.html { self.render(template: "mailers/user_mailer/welcome", locals: {message: locals_message, name: locals_name, product_name: locals_product_name}) }
      format.text { self.render(template: "mailers/user_mailer/welcome.text", locals: {message: locals_message, name: locals_name, product_name: locals_product_name}) }
    end
  end
end
