# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
module BlockApi
  def self.__hx_name()
    "BlockApi"
  end
  def self.__hx_fields()
    {instance: ["visit"], static: []}
  end
end
