# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "block_base"
class BlockChild < BlockBase
  def self.__hx_name()
    "BlockChild"
  end
  def self.__hx_fields()
    {instance: ["visit"], static: []}
  end
  def initialize()
    super()
  end
  def visit(value, &block)
    if (block == nil)
      raise(ArgumentError, "required block missing for visit")
    end
    return ("child:" + super((value + 1), &block))
  end
end
