# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "hxruby/core"
class BlockBase
  def self.__hx_name()
    "BlockBase"
  end
  def self.__hx_fields()
    {instance: ["plain", "recursive", "visit"], static: []}
  end
  def initialize()
    nil
  end
  def plain(value)
    return ("plain:" + HXRuby.stringify(value))
  end
  def visit(value)
    return yield(value)
  end
  def recursive(value, &block)
    if (block == nil)
      raise(ArgumentError, "required block missing for recursive")
    end
    return ((value <= 0) ? block.call(value) : self.recursive((value - 1), &block))
  end
end
