# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require "active_support/concern"
module CallableConcern
  def self.__hx_name()
    "CallableConcern"
  end
  def self.__hx_fields()
    {instance: ["concernVisit"], static: []}
  end
  extend ActiveSupport::Concern
  def concern_visit(value)
    return yield(value)
  end
end
