# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
module CallableModule
  def self.__hx_name()
    "CallableModule"
  end
  def self.__hx_fields()
    {instance: ["moduleVisit"], static: []}
  end
  def module_visit(value)
    return yield(value)
  end
end
