# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class ConcernCallableReceiver
  def self.__hx_name()
    "ConcernCallableReceiver"
  end
  def self.__hx_fields()
    {instance: ["concernVisit"], static: []}
  end
  include CallableConcern
  def initialize()
    nil
  end
end
