# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "block_api"
class InterfaceWorker
  def self.__hx_name()
    "InterfaceWorker"
  end
  def self.__hx_fields()
    {instance: ["visit"], static: []}
  end
  include BlockApi
  def initialize()
    nil
  end
  def visit(value)
    return yield((value + 1))
  end
end
