# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "hxruby/core"
class KeywordBase
  def self.__hx_name()
    "KeywordBase"
  end
  def self.__hx_fields()
    {instance: ["configure"], static: []}
  end
  def initialize()
    nil
  end
  def configure(prefix:, **optional_keywords)
    # Preserve optional keyword presence separately from explicit nil and reject undeclared keys.
    unknown_keywords = (optional_keywords.keys() - [:suffix])
    if (!unknown_keywords.empty?())
      raise(ArgumentError, ("unknown keyword(s) for configure: " + unknown_keywords.inspect()))
    end
    return (prefix + (optional_keywords.key?(:suffix) ? (":" + HXRuby.stringify(optional_keywords[:suffix])) : ":missing"))
  end
end
