# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "keyword_base"
class KeywordChild < KeywordBase
  def self.__hx_name()
    "KeywordChild"
  end
  def self.__hx_fields()
    {instance: ["configure"], static: []}
  end
  def initialize()
    super()
  end
  def configure(prefix:, **optional_keywords)
    # Preserve optional keyword presence separately from explicit nil and reject undeclared keys.
    unknown_keywords = (optional_keywords.keys() - [:suffix])
    if (!unknown_keywords.empty?())
      raise(ArgumentError, ("unknown keyword(s) for configure: " + unknown_keywords.inspect()))
    end
    return ("child:" + super(prefix: prefix, **(optional_keywords.key?(:suffix) ? {suffix: optional_keywords[:suffix]} : {})))
  end
end
