# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "hxruby/core"
class Main
  def self.__hx_name()
    "Main"
  end
  def self.__hx_fields()
    {instance: [], static: ["main"]}
  end
  def self.main()
    child = BlockChild.new()
    puts(HXRuby.stringify(child.visit(1) { |value| ("direct:" + HXRuby.stringify(value)) }))
    base = child
    puts(HXRuby.stringify(base.visit(2) { |value__hx1| ("base:" + HXRuby.stringify(value__hx1)) }))
    puts(HXRuby.stringify(child.recursive(2) { |value__hx2| ("recursive:" + HXRuby.stringify(value__hx2)) }))
    worker = InterfaceWorker.new()
    api = worker
    puts(HXRuby.stringify(worker.visit(3) { |value__hx3| ("impl:" + HXRuby.stringify(value__hx3)) }))
    puts(HXRuby.stringify(api.visit(4) { |value__hx4| ("api:" + HXRuby.stringify(value__hx4)) }))
    static_block = ->(*haxe_args) do
      # Adapt this Haxe function value's positional carriers to Ruby keywords and block syntax.
      callable_block = haxe_args.pop()
      StaticCallables.decorate(*haxe_args, &callable_block)
    end
    puts(HXRuby.stringify(static_block.call(5, ->(value__hx5) { ("static-value:" + HXRuby.stringify(value__hx5)) })))
    instance_block = ->(*haxe_args__hx1) do
      # Adapt this Haxe function value's positional carriers to Ruby keywords and block syntax.
      callable_block__hx1 = haxe_args__hx1.pop()
      child.visit(*haxe_args__hx1, &callable_block__hx1)
    end
    puts(HXRuby.stringify(instance_block.call(6, ->(value__hx6) { ("instance-value:" + HXRuby.stringify(value__hx6)) })))
    interface_block = ->(*haxe_args__hx2) do
      # Adapt this Haxe function value's positional carriers to Ruby keywords and block syntax.
      callable_block__hx2 = haxe_args__hx2.pop()
      api.visit(*haxe_args__hx2, &callable_block__hx2)
    end
    puts(HXRuby.stringify(interface_block.call(7, ->(value__hx7) { ("interface-value:" + HXRuby.stringify(value__hx7)) })))
    puts(HXRuby.stringify(child.visit(begin
      positional = WorkerFactory.positional_value()
      positional = 15
      positional
    end) { |value__hx8| ("positional:" + HXRuby.stringify(value__hx8)) }))
    puts(HXRuby.stringify(("positional-evaluations:" + HXRuby.stringify(WorkerFactory.positional_evaluations))))
    effectful_plain = WorkerFactory.make().method(:plain)
    puts(HXRuby.stringify(effectful_plain.call(8)))
    puts(HXRuby.stringify(("plain-factory-count:" + HXRuby.stringify(WorkerFactory.created))))
    effectful_block = begin
      # Evaluate the method-value receiver once at capture, matching Haxe expression semantics.
      callable_receiver = WorkerFactory.make()
      ->(*haxe_args__hx3) do
        # Adapt this Haxe function value's positional carriers to Ruby keywords and block syntax.
        callable_block__hx3 = haxe_args__hx3.pop()
        callable_receiver.visit(*haxe_args__hx3, &callable_block__hx3)
      end
    end
    puts(HXRuby.stringify(effectful_block.call(8, ->(value__hx9) { ("effectful:" + HXRuby.stringify(value__hx9)) })))
    puts(HXRuby.stringify(("factory-count:" + HXRuby.stringify(WorkerFactory.created))))
    native_child = NativeBlockChild.new()
    puts(HXRuby.stringify(native_child.transform!(9) { |value__hx10| ("direct-native:" + HXRuby.stringify(value__hx10)) }))
    native_value = ->(*haxe_args__hx4) do
      # Adapt this Haxe function value's positional carriers to Ruby keywords and block syntax.
      callable_block__hx4 = haxe_args__hx4.pop()
      native_child.transform!(*haxe_args__hx4, &callable_block__hx4)
    end
    puts(HXRuby.stringify(native_value.call(10, ->(value__hx11) { ("captured-native:" + HXRuby.stringify(value__hx11)) })))
    static_keyword = ->(*haxe_args__hx5) do
      # Adapt this Haxe function value's positional carriers to Ruby keywords and block syntax.
      keyword_options = haxe_args__hx5.delete_at(0)
      StaticCallables.label(prefix: keyword_options["prefix"], **(keyword_options.key?("suffix") ? {suffix: keyword_options["suffix"]} : {}))
    end
    puts(HXRuby.stringify(("static-keyword:" + static_keyword.call({"prefix" => "one"}))))
    optional_block = ->(*haxe_args__hx6) do
      # Adapt this Haxe function value's positional carriers to Ruby keywords and block syntax.
      callable_block__hx5 = ((haxe_args__hx6.length() > 1) ? haxe_args__hx6.pop() : nil)
      StaticCallables.optional(*haxe_args__hx6, &callable_block__hx5)
    end
    puts(HXRuby.stringify(optional_block.call(11)))
    puts(HXRuby.stringify(optional_block.call(12, ->(value__hx12) { ("optional-value:" + HXRuby.stringify(value__hx12)) })))
    combined = ->(*haxe_args__hx7) do
      # Adapt this Haxe function value's positional carriers to Ruby keywords and block syntax.
      callable_block__hx6 = haxe_args__hx7.pop()
      keyword_options__hx1 = haxe_args__hx7.delete_at(0)
      StaticCallables.compose(prefix: keyword_options__hx1["prefix"], **(keyword_options__hx1.key?("suffix") ? {suffix: keyword_options__hx1["suffix"]} : {}), &callable_block__hx6)
    end
    puts(HXRuby.stringify(combined.call({"prefix" => "combined"}, ->(value__hx13) { ("combined-value:" + value__hx13) })))
    rest_value = StaticCallables.method(:join)
    puts(HXRuby.stringify(rest_value.call("rest:", 1, 2)))
    spread = [3, 4]
    puts(HXRuby.stringify(rest_value.call("spread:", *spread)))
    keyword = KeywordChild.new()
    keyword_value = ->(*haxe_args__hx8) do
      # Adapt this Haxe function value's positional carriers to Ruby keywords and block syntax.
      keyword_options__hx2 = haxe_args__hx8.delete_at(0)
      keyword.configure(prefix: keyword_options__hx2["prefix"], **(keyword_options__hx2.key?("suffix") ? {suffix: keyword_options__hx2["suffix"]} : {}))
    end
    puts(HXRuby.stringify(keyword_value.call({"prefix" => "two", "suffix" => nil})))
    module_value = begin
      # Evaluate the method-value receiver once at capture, matching Haxe expression semantics.
      callable_receiver__hx1 = ModuleCallableReceiver.new()
      ->(*haxe_args__hx9) do
        # Adapt this Haxe function value's positional carriers to Ruby keywords and block syntax.
        callable_block__hx7 = haxe_args__hx9.pop()
        callable_receiver__hx1.module_visit(*haxe_args__hx9, &callable_block__hx7)
      end
    end
    puts(HXRuby.stringify(module_value.call(13, ->(value__hx14) { ("module:" + HXRuby.stringify(value__hx14)) })))
    concern_value = begin
      # Evaluate the method-value receiver once at capture, matching Haxe expression semantics.
      callable_receiver__hx2 = ConcernCallableReceiver.new()
      ->(*haxe_args__hx10) do
        # Adapt this Haxe function value's positional carriers to Ruby keywords and block syntax.
        callable_block__hx8 = haxe_args__hx10.pop()
        callable_receiver__hx2.concern_visit(*haxe_args__hx10, &callable_block__hx8)
      end
    end
    puts(HXRuby.stringify(concern_value.call(14, ->(value__hx15) { ("concern:" + HXRuby.stringify(value__hx15)) })))
  end
end
if __FILE__ == $PROGRAM_NAME
  $LOAD_PATH.unshift(__dir__)
  Main.main()
end
