# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class ModuleCallableReceiver
  def self.__hx_name()
    "ModuleCallableReceiver"
  end
  def self.__hx_fields()
    {instance: ["moduleVisit"], static: []}
  end
  include CallableModule
  def initialize()
    nil
  end
end
