# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class NativeBlockBase
  def self.__hx_name()
    "NativeBlockBase"
  end
  def self.__hx_fields()
    {instance: ["transform"], static: []}
  end
  def initialize()
    nil
  end
  def transform!(value)
    return yield(value)
  end
end
