# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "native_block_base"
class NativeBlockChild < NativeBlockBase
  def self.__hx_name()
    "NativeBlockChild"
  end
  def self.__hx_fields()
    {instance: ["transform"], static: []}
  end
  def initialize()
    super()
  end
  def transform!(value, &block)
    if (block == nil)
      raise(ArgumentError, "required block missing for transform!")
    end
    return ("native:" + super((value + 1), &block))
  end
end
