# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
require_relative "hxruby/core"
class StaticCallables
  def self.__hx_name()
    "StaticCallables"
  end
  def self.__hx_fields()
    {instance: [], static: ["compose", "decorate", "join", "label", "optional"]}
  end
  def self.decorate(value)
    return yield(value)
  end
  def self.label(prefix:, **optional_keywords)
    # Preserve optional keyword presence separately from explicit nil and reject undeclared keys.
    unknown_keywords = (optional_keywords.keys() - [:suffix])
    if (!unknown_keywords.empty?())
      raise(ArgumentError, ("unknown keyword(s) for self.label: " + unknown_keywords.inspect()))
    end
    return (prefix + (optional_keywords.key?(:suffix) ? (":" + HXRuby.stringify(optional_keywords[:suffix])) : ":missing"))
  end
  def self.optional(value, &block)
    return ((block == nil) ? ("optional:" + HXRuby.stringify(value)) : block.call(value))
  end
  def self.compose(prefix:, **optional_keywords)
    # Preserve optional keyword presence separately from explicit nil and reject undeclared keys.
    unknown_keywords = (optional_keywords.keys() - [:suffix])
    if (!unknown_keywords.empty?())
      raise(ArgumentError, ("unknown keyword(s) for self.compose: " + unknown_keywords.inspect()))
    end
    return yield(StaticCallables.label(prefix: prefix, **(optional_keywords.key?(:suffix) ? {suffix: optional_keywords[:suffix]} : {})))
  end
  def self.join(prefix, *values)
    return (prefix + values.dup().join(","))
  end
end
