# Generated by reflaxe.ruby
# Generated type shell for Ruby output.
class WorkerFactory
  def self.__hx_name()
    "WorkerFactory"
  end
  def self.__hx_fields()
    {instance: [], static: ["created", "make"]}
  end
  class << self
    attr_accessor :created
  end
  @created = 0
  def self.make()
    WorkerFactory.created = (WorkerFactory.created + 1)
    return BlockChild.new()
  end
end
